import type { DuelBoardState, FieldCard } from '../../shared/types/field.js';

export function createMockDuelState(): DuelBoardState {
  // User Hand Cards (5 cards)
  const userHand: FieldCard[] = [
    {
      id: 'hand-u-1',
      code: 46986414,
      name: 'Dark Magician',
      controller: 0,
      location: 'hand',
      sequence: 0,
      position: 'faceup_attack',
      atk: 2500,
      def: 2100,
      baseAtk: 2500,
      baseDef: 2100,
      level: 7,
      attribute: 'DARK',
      race: 'Spellcaster',
      description: 'The ultimate wizard in terms of attack and defense.',
    },
    {
      id: 'hand-u-2',
      code: 40640057,
      name: 'Kuriboh',
      controller: 0,
      location: 'hand',
      sequence: 1,
      position: 'faceup_attack',
      atk: 300,
      def: 200,
      baseAtk: 300,
      baseDef: 200,
      level: 1,
      attribute: 'DARK',
      race: 'Fiend',
      description:
        'During damage calculation, if an opponent\'s monster attacks (Quick Effect): You can discard this card; you take no battle damage from that battle.',
    },
    {
      id: 'hand-u-3',
      code: 12580477,
      name: 'Raigeki',
      controller: 0,
      location: 'hand',
      sequence: 2,
      position: 'faceup_spell',
      level: 0,
      attribute: 'SPELL',
      race: 'Normal',
      description: "Destroy all monsters your opponent controls.",
    },
    {
      id: 'hand-u-4',
      code: 4206964,
      name: 'Trap Hole',
      controller: 0,
      location: 'hand',
      sequence: 3,
      position: 'facedown_spell',
      level: 0,
      attribute: 'TRAP',
      race: 'Normal',
      description:
        'When your opponent Normal or Flip Summons 1 monster with 1000 or more ATK: Target that monster; destroy that target.',
    },
    {
      id: 'hand-u-5',
      code: 15025844,
      name: 'Mystical Elf',
      controller: 0,
      location: 'hand',
      sequence: 4,
      position: 'faceup_defense',
      atk: 800,
      def: 2000,
      baseAtk: 800,
      baseDef: 2000,
      level: 4,
      attribute: 'LIGHT',
      race: 'Spellcaster',
      description: 'A delicate elf that lacks offense, but has a terrific defense backed by mystical power.',
    },
  ];

  // Opponent Hand Cards (5 cards - hidden/card backs)
  const opponentHand: FieldCard[] = [
    {
      id: 'hand-ai-1',
      code: 0,
      name: 'Hidden Card',
      controller: 1,
      location: 'hand',
      sequence: 0,
      position: 'facedown_spell',
    },
    {
      id: 'hand-ai-2',
      code: 0,
      name: 'Hidden Card',
      controller: 1,
      location: 'hand',
      sequence: 1,
      position: 'facedown_spell',
    },
    {
      id: 'hand-ai-3',
      code: 0,
      name: 'Hidden Card',
      controller: 1,
      location: 'hand',
      sequence: 2,
      position: 'facedown_spell',
    },
    {
      id: 'hand-ai-4',
      code: 0,
      name: 'Hidden Card',
      controller: 1,
      location: 'hand',
      sequence: 3,
      position: 'facedown_spell',
    },
    {
      id: 'hand-ai-5',
      code: 0,
      name: 'Hidden Card',
      controller: 1,
      location: 'hand',
      sequence: 4,
      position: 'facedown_spell',
    },
  ];

  // User Graveyard (3 cards, top is Summoned Skull)
  const userGraveyard: FieldCard[] = [
    {
      id: 'gy-u-1',
      code: 13039848,
      name: 'Giant Soldier of Stone',
      controller: 0,
      location: 'graveyard',
      sequence: 0,
      position: 'faceup_defense',
      atk: 1300,
      def: 2000,
      baseAtk: 1300,
      baseDef: 2000,
      level: 3,
      attribute: 'EARTH',
      race: 'Rock',
      description: 'A giant warrior made of stone. A punch from this creature has earth-shaking power.',
    },
    {
      id: 'gy-u-2',
      code: 41392891,
      name: 'Feral Imp',
      controller: 0,
      location: 'graveyard',
      sequence: 1,
      position: 'faceup_attack',
      atk: 1300,
      def: 1400,
      baseAtk: 1300,
      baseDef: 1400,
      level: 4,
      attribute: 'DARK',
      race: 'Fiend',
      description: 'A playful little fiend that lurks in the dark, waiting to attack an unwary enemy.',
    },
    {
      id: 'gy-u-3',
      code: 70781052,
      name: 'Summoned Skull',
      controller: 0,
      location: 'graveyard',
      sequence: 2,
      position: 'faceup_attack',
      atk: 2500,
      def: 1200,
      baseAtk: 2500,
      baseDef: 1200,
      level: 6,
      attribute: 'DARK',
      race: 'Fiend',
      description: 'A fiend with dark powers for confusing the enemy. Among the Fiend-Type monsters, this monster boasts considerable strength.',
    },
  ];

  // User Banished (1 card)
  const userBanished: FieldCard[] = [
    {
      id: 'ban-u-1',
      code: 90357090,
      name: 'Silver Fang',
      controller: 0,
      location: 'banished',
      sequence: 0,
      position: 'faceup_attack',
      atk: 1200,
      def: 800,
      baseAtk: 1200,
      baseDef: 800,
      level: 3,
      attribute: 'EARTH',
      race: 'Beast',
      description: 'A snow wolf that\'s beautiful to the eye, but absolutely lethal in battle.',
    },
  ];

  // Opponent Graveyard (2 cards, top is La Jinn)
  const opponentGraveyard: FieldCard[] = [
    {
      id: 'gy-ai-1',
      code: 25833572,
      name: 'Ookazi',
      controller: 1,
      location: 'graveyard',
      sequence: 0,
      position: 'faceup_spell',
      level: 0,
      attribute: 'SPELL',
      race: 'Normal',
      description: 'Inflict 800 damage to your opponent.',
    },
    {
      id: 'gy-ai-2',
      code: 97590747,
      name: 'La Jinn the Mystical Genie of the Lamp',
      controller: 1,
      location: 'graveyard',
      sequence: 1,
      position: 'faceup_attack',
      atk: 1800,
      def: 1000,
      baseAtk: 1800,
      baseDef: 1000,
      level: 4,
      attribute: 'DARK',
      race: 'Fiend',
      description: 'A genial genie that has bound itself to serve whoever holds its magic lamp.',
    },
  ];

  // Opponent Banished (0 cards)
  const opponentBanished: FieldCard[] = [];

  return {
    userField: {
      playerId: 0,
      name: 'Yugi Muto',
      title: 'King of Games',
      series: 'DM',
      avatar: 'yugi-muto',
      characterId: 'yugi-muto',
      currentLp: 8000,
      maxLp: 8000,
      isTurn: true,

      // 5 Monster Zones
      monsterZones: [
        // Zone 0: Dark Magician (Face-up Attack)
        {
          id: 'mz-u-0',
          code: 46986414,
          name: 'Dark Magician',
          controller: 0,
          location: 'monster',
          sequence: 0,
          position: 'faceup_attack',
          atk: 2500,
          def: 2100,
          baseAtk: 2500,
          baseDef: 2100,
          level: 7,
          attribute: 'DARK',
          race: 'Spellcaster',
          description: 'The ultimate wizard in terms of attack and defense.',
        },
        // Zone 1: Celtic Guardian (Face-up Defense, Rotated 90°)
        {
          id: 'mz-u-1',
          code: 91152256,
          name: 'Celtic Guardian',
          controller: 0,
          location: 'monster',
          sequence: 1,
          position: 'faceup_defense',
          atk: 1400,
          def: 1200,
          baseAtk: 1400,
          baseDef: 1200,
          level: 4,
          attribute: 'EARTH',
          race: 'Warrior',
          description: 'An elf who learned to wield a sword, he baffles enemies with lightning-fast attacks.',
        },
        // Zone 2: Man-Eater Bug (Face-down Defense "Set", Rotated 90° with Card Back)
        {
          id: 'mz-u-2',
          code: 54652250,
          name: 'Man-Eater Bug',
          controller: 0,
          location: 'monster',
          sequence: 2,
          position: 'facedown_defense',
          atk: 450,
          def: 600,
          baseAtk: 450,
          baseDef: 600,
          level: 2,
          attribute: 'EARTH',
          race: 'Insect',
          description: 'FLIP: Target 1 monster on the field; destroy that target.',
        },
        null,
        null,
      ],

      // 5 Spell/Trap Zones
      spellTrapZones: [
        // STZ 0: Mirror Force (Face-down "Set")
        {
          id: 'st-u-0',
          code: 44095762,
          name: 'Mirror Force',
          controller: 0,
          location: 'spell-trap',
          sequence: 0,
          position: 'facedown_spell',
          level: 0,
          attribute: 'TRAP',
          race: 'Normal',
          description: 'When an opponent\'s monster declares an attack: Destroy all your opponent\'s Attack Position monsters.',
        },
        // STZ 1: Swords of Revealing Light (Face-up Active)
        {
          id: 'st-u-1',
          code: 72302403,
          name: 'Swords of Revealing Light',
          controller: 0,
          location: 'spell-trap',
          sequence: 1,
          position: 'faceup_spell',
          level: 0,
          attribute: 'SPELL',
          race: 'Normal',
          description:
            'After this card\'s activation, it remains on the field, but you must destroy it during the End Phase of your opponent\'s 3rd turn. When this card is activated: If your opponent controls a face-down monster, flip all monsters they control face-up. While this card is face-up on the field, your opponent\'s monsters cannot declare an attack.',
        },
        null,
        null,
        null,
      ],

      // Field Zone
      fieldZone: {
        id: 'field-u',
        code: 59197169,
        name: 'Yami',
        controller: 0,
        location: 'field',
        sequence: 0,
        position: 'faceup_spell',
        level: 0,
        attribute: 'SPELL',
        race: 'Field',
        description: 'All Fiend and Spellcaster monsters on the field gain 200 ATK/DEF, also all Fairy monsters on the field lose 200 ATK/DEF.',
      },

      graveyard: userGraveyard,
      banished: userBanished,
      deckCount: 34,
      extraDeckCount: 3,
      hand: userHand,
    },

    opponentField: {
      playerId: 1,
      name: 'Seto Kaiba',
      title: 'KaibaCorp President',
      series: 'DM',
      avatar: 'seto-kaiba',
      characterId: 'seto-kaiba',
      currentLp: 8000,
      maxLp: 8000,
      isTurn: false,

      // 5 Opponent Monster Zones
      monsterZones: [
        // Zone 0: Blue-Eyes White Dragon (Face-up Attack)
        {
          id: 'mz-ai-0',
          code: 89631139,
          name: 'Blue-Eyes White Dragon',
          controller: 1,
          location: 'monster',
          sequence: 0,
          position: 'faceup_attack',
          atk: 3000,
          def: 2500,
          baseAtk: 3000,
          baseDef: 2500,
          level: 8,
          attribute: 'LIGHT',
          race: 'Dragon',
          description: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome beast and lived to tell the tale.',
        },
        // Zone 1: Vorse Raider (Face-up Attack)
        {
          id: 'mz-ai-1',
          code: 14898066,
          name: 'Vorse Raider',
          controller: 1,
          location: 'monster',
          sequence: 1,
          position: 'faceup_attack',
          atk: 1900,
          def: 1200,
          baseAtk: 1900,
          baseDef: 1200,
          level: 4,
          attribute: 'DARK',
          race: 'Beast-Warrior',
          description: 'This wicked Beast-Warrior does every horrid thing imaginable and simply loves it. His axe bears the scars of countless victims.',
        },
        // Zone 2: Face-down Defense "Set" Monster (Redacted for Viewer)
        {
          id: 'mz-ai-2',
          code: 0,
          name: 'Face-Down Card',
          controller: 1,
          location: 'monster',
          sequence: 2,
          position: 'facedown_defense',
          description:
            'This card is currently face-down in Defense Position on your opponent’s field. Its identity and effects remain hidden.',
        },
        null,
        null,
      ],

      // 5 Opponent Spell/Trap Zones
      spellTrapZones: [
        // STZ 0: Face-down Set Spell/Trap (Redacted for Viewer)
        {
          id: 'st-ai-0',
          code: 0,
          name: 'Face-Down Card',
          controller: 1,
          location: 'spell-trap',
          sequence: 0,
          position: 'facedown_spell',
          description:
            'This card is currently face-down on your opponent’s field. Its identity and effects remain hidden.',
        },
        // STZ 1: Dark Hole (Face-up Continuous or Pending)
        {
          id: 'st-ai-1',
          code: 53129443,
          name: 'Dark Hole',
          controller: 1,
          location: 'spell-trap',
          sequence: 1,
          position: 'faceup_spell',
          level: 0,
          attribute: 'SPELL',
          race: 'Normal',
          description: 'Destroy all monsters on the field.',
        },
        null,
        null,
        null,
      ],

      // Field Zone
      fieldZone: {
        id: 'field-ai',
        code: 50913601,
        name: 'Mountain',
        controller: 1,
        location: 'field',
        sequence: 0,
        position: 'faceup_spell',
        level: 0,
        attribute: 'SPELL',
        race: 'Field',
        description: 'All Dragon, Winged Beast, and Thunder monsters on the field gain 200 ATK/DEF.',
      },

      graveyard: opponentGraveyard,
      banished: opponentBanished,
      deckCount: 35,
      extraDeckCount: 2,
      hand: opponentHand,
    },

    extraMonsterZones: [null, null], // 2 Extra Monster Zones between players (inert in v1)
    turnNumber: 1,
    currentPhase: 'M1',
    activePrompt: null,
    phaseGuideText: 'Main Phase 1: You may Normal Summon 1 monster, Set Spells/Traps, or change Battle Positions.',
    winner: null,
  };
}
