import type { DeckDefinition } from './deckValidatorHelper.ts';

export const DM_AUTHENTIC_DECKS: DeckDefinition[] = [
  // ===========================================================================
  // 1. Yugi Muto
  // ===========================================================================
  {
    id: 'yugi-muto_deck_1',
    characterId: 'yugi-muto',
    name: 'Silent & Gadget Arsenal',
    archetype: 'Gadget / Silent LV',
    description: 'Yugi Muto\'s ceremonial masterpiece deck featuring the mechanical Gadget trio, the evolving Silent LV warriors, and the apocalyptic Gandora the Dragon of Destruction.',
    signatureCards: ['Silent Swordsman LV7', 'Gandora the Dragon of Destruction', 'Silent Magician LV8'],
    main: [
      ['Silent Swordsman LV3', 2],
      ['Silent Swordsman LV5', 2],
      ['Silent Swordsman LV7', 1],
      ['Silent Magician LV4', 2],
      ['Silent Magician LV8', 1],
      ['Green Gadget', 2],
      ['Red Gadget', 2],
      ['Yellow Gadget', 2],
      ['Gandora the Dragon of Destruction', 1],
      ['Marshmallon', 1],
      ['Giant Soldier of Stone', 2],
      ['Big Shield Gardna', 1],
      ['Watapon', 1],
      ['Toy Magician', 2],
      ['Morphing Jar', 1],
      ['Sangan', 1],
      ['Level Up!', 2],
      ['Level Modulation', 1],
      ['Swords of Revealing Light', 1],
      ['Pot of Greed', 1],
      ['Graceful Charity', 1],
      ['Monster Reborn', 1],
      ['Card Destruction', 1],
      ['Marshmallon Glasses', 1],
      ['Magical Dimension', 2],
      ['Soul Exchange', 1],
      ['Stronghold the Moving Fortress', 2],
      ['Mirror Force', 1],
      ['Magician\'s Circle', 2],
      ['Shift', 1],
    ],
  },
  {
    id: 'yugi-muto_deck_2',
    characterId: 'yugi-muto',
    name: 'Magna Warrior & Silent Magician',
    archetype: 'Magnet Warrior / Rock',
    description: 'Yugi\'s electromagnetic rock deck uniting Alpha, Beta, and Gamma to summon the mighty Valkyrion the Magna Warrior alongside Silent Magician.',
    signatureCards: ['Valkyrion the Magna Warrior', 'Silent Magician LV8', 'Alpha The Magnet Warrior'],
    main: [
      ['Alpha The Magnet Warrior', 3],
      ['Beta The Magnet Warrior', 3],
      ['Gamma The Magnet Warrior', 3],
      ['Valkyrion the Magna Warrior', 2],
      ['Silent Magician LV4', 3],
      ['Silent Magician LV8', 2],
      ['Giant Soldier of Stone', 3],
      ['Big Shield Gardna', 1],
      ['Sangan', 1],
      ['Morphing Jar', 1],
      ['Level Up!', 2],
      ['Level Modulation', 2],
      ['Magical Dimension', 2],
      ['Swords of Revealing Light', 1],
      ['Pot of Greed', 1],
      ['Graceful Charity', 1],
      ['Monster Reborn', 1],
      ['Card Destruction', 1],
      ['Dark Hole', 1],
      ['Premature Burial', 1],
      ['Call of the Haunted', 2],
      ['Mirror Force', 1],
      ['Spellbinding Circle', 2],
    ],
  },

  // ===========================================================================
  // 2. Yami Yugi
  // ===========================================================================
  {
    id: 'yami-yugi_deck_1',
    characterId: 'yami-yugi',
    name: 'Duelist Kingdom Exodia & Chaos',
    archetype: 'Spellcaster / Warrior',
    description: 'The Pharaoh\'s legendary Duelist Kingdom deck featuring the unstoppable Exodia the Forbidden One, Black Luster Soldier, Gaia the Dragon Champion, and Summoned Skull.',
    signatureCards: ['Exodia the Forbidden One', 'Black Luster Soldier', 'Dark Magician'],
    main: [
      ['Exodia the Forbidden One', 1],
      ['Right Arm of the Forbidden One', 1],
      ['Left Arm of the Forbidden One', 1],
      ['Right Leg of the Forbidden One', 1],
      ['Left Leg of the Forbidden One', 1],
      ['Dark Magician', 2],
      ['Summoned Skull', 2],
      ['Gaia The Fierce Knight', 2],
      ['Curse of Dragon', 2],
      ['Celtic Guardian', 2],
      ['Catapult Turtle', 1],
      ['Mammoth Graveyard', 1],
      ['Feral Imp', 2],
      ['Silver Fang', 2],
      ['Beaver Warrior', 2],
      ['Winged Dragon, Guardian of the Fortress #1', 2],
      ['Kuriboh', 2],
      ['Black Luster Soldier', 1],
      ['Black Luster Ritual', 1],
      ['Polymerization', 2],
      ['Swords of Revealing Light', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Card Destruction', 1],
      ['Makiu, the Magical Mist', 1],
      ['Multiply', 1],
      ['Mirror Force', 1],
      ['Spellbinding Circle', 2],
    ],
    extra: [
      ['Gaia the Dragon Champion', 2],
    ],
  },
  {
    id: 'yami-yugi_deck_2',
    characterId: 'yami-yugi',
    name: 'Battle City Slifer & Dark Magician',
    archetype: 'Dark Magician / Egyptian God',
    description: 'Atem\'s Battle City championship deck centered on the Ultimate Wizard Dark Magician, Dark Magician Girl, Buster Blader, and the divine Egyptian God Slifer the Sky Dragon.',
    signatureCards: ['Slifer the Sky Dragon', 'Dark Magician', 'Dark Paladin'],
    main: [
      ['Slifer the Sky Dragon', 1],
      ['Dark Magician', 3],
      ['Dark Magician Girl', 2],
      ['Buster Blader', 2],
      ['Skilled Dark Magician', 2],
      ['Skilled White Magician', 1],
      ['Magician\'s Valkyria', 2],
      ['Big Shield Gardna', 1],
      ['Berfomet', 1],
      ['Gazelle the King of Mythical Beasts', 2],
      ["King's Knight", 2],
      ["Queen's Knight", 2],
      ["Jack's Knight", 2],
      ['Kuriboh', 1],
      ['Breaker the Magical Warrior', 1],
      ['Polymerization', 2],
      ['Dark Magic Curtain', 1],
      ['Thousand Knives', 1],
      ['Dark Magic Attack', 1],
      ['Card of Safe Return', 1],
      ['Pot of Greed', 1],
      ['Graceful Charity', 1],
      ['Monster Reborn', 1],
      ['Premature Burial', 1],
      ['De-Fusion', 1],
      ['Magical Dimension', 1],
      ['Magic Cylinder', 1],
      ['Mirror Force', 1],
      ['Magician\'s Circle', 1],
    ],
    extra: [
      ['Dark Paladin', 2],
      ['Chimera the Flying Mythical Beast', 2],
      ['Arcana Knight Joker', 1],
    ],
  },
  {
    id: 'yami-yugi_deck_3',
    characterId: 'yami-yugi',
    name: 'Legendary Dragon of Timaeus',
    archetype: 'Dark Magician / Legendary Dragon',
    description: 'The ancient bonds of Atem awakened through The Eye of Timaeus, merging Dark Magician and Dark Magician Girl into draconic knights against the darkness.',
    signatureCards: ['The Eye of Timaeus', 'Dark Magician the Dragon Knight', 'Dark Magician Girl the Dragon Knight'],
    main: [
      ['Dark Magician', 3],
      ['Dark Magician Girl', 2],
      ['Apprentice Illusion Magician', 2],
      ['Magician\'s Rod', 3],
      ['Magician\'s Robe', 2],
      ['Breaker the Magical Warrior', 1],
      ['Watapon', 1],
      ['Kuriboh', 1],
      ['The Eye of Timaeus', 3],
      ['Dark Magical Circle', 3],
      ['Illusion Magic', 2],
      ['Dark Magic Curtain', 1],
      ['Dark Magic Attack', 1],
      ['Dark Magic Inheritance', 1],
      ['Thousand Knives', 1],
      ['Berserker Soul', 1],
      ['Pot of Greed', 1],
      ['Graceful Charity', 1],
      ['Monster Reborn', 1],
      ['Secret Village of the Spellcasters', 1],
      ['Magician Navigation', 3],
      ['Eternal Soul', 3],
      ['Dark Renewal', 1],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Dark Magician the Dragon Knight', 2],
      ['Dark Magician Girl the Dragon Knight', 2],
      ['Amulet Dragon', 2],
      ['The Dark Magicians', 1],
    ],
  },

  // ===========================================================================
  // 3. Seto Kaiba
  // ===========================================================================
  {
    id: 'seto-kaiba_deck_1',
    characterId: 'seto-kaiba',
    name: 'Duelist Kingdom Blue-Eyes Ultimate',
    archetype: 'Blue-Eyes / Beatdown',
    description: 'Kaiba\'s ruthless Duelist Kingdom power deck featuring three legendary Blue-Eyes White Dragons and their catastrophic fusion, Blue-Eyes Ultimate Dragon.',
    signatureCards: ['Blue-Eyes White Dragon', 'Blue-Eyes Ultimate Dragon'],
    main: [
      ['Blue-Eyes White Dragon', 3],
      ['Battle Ox', 3],
      ['La Jinn the Mystical Genie of the Lamp', 3],
      ['Vorse Raider', 3],
      ['Saggi the Dark Clown', 2],
      ['Ryu-Kishin Powered', 2],
      ['Lord of D.', 2],
      ['Kaiser Sea Horse', 2],
      ['The Flute of Summoning Dragon', 2],
      ['Polymerization', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Ancient Rules', 1],
      ['De-Fusion', 1],
      ['Shrink', 2],
      ['Crush Card Virus', 2],
      ['Shadow Spell', 2],
      ['Ring of Destruction', 1],
      ['Negate Attack', 2],
      ['Trap Hole', 3],
    ],
    extra: [
      ['Blue-Eyes Ultimate Dragon', 3],
    ],
  },
  {
    id: 'seto-kaiba_deck_2',
    characterId: 'seto-kaiba',
    name: 'Battle City Obelisk & XYZ Cannon',
    archetype: 'Blue-Eyes / XYZ Machine / Egyptian God',
    description: 'Kaiba\'s Battle City high-tech arsenal, combining the supreme divine wrath of Obelisk the Tormentor with XYZ-Dragon Cannon and Blue-Eyes White Dragon.',
    signatureCards: ['Obelisk the Tormentor', 'XYZ-Dragon Cannon', 'Blue-Eyes White Dragon'],
    main: [
      ['Obelisk the Tormentor', 1],
      ['Blue-Eyes White Dragon', 3],
      ['X-Head Cannon', 3],
      ['Y-Dragon Head', 3],
      ['Z-Metal Tank', 3],
      ['Luster Dragon', 2],
      ['Blade Knight', 2],
      ['Vorse Raider', 2],
      ['Kaiser Sea Horse', 2],
      ['Cyber Jar', 1],
      ['Morphing Jar', 1],
      ['Enemy Controller', 3],
      ['Cost Down', 2],
      ['Shrink', 2],
      ['Pot of Greed', 1],
      ['Graceful Charity', 1],
      ['Monster Reborn', 1],
      ['Heavy Storm', 1],
      ['Crush Card Virus', 1],
      ['Ring of Destruction', 1],
      ['Interdimensional Matter Transporter', 2],
      ['Cloning', 2],
    ],
    extra: [
      ['XYZ-Dragon Cannon', 2],
      ['XY-Dragon Cannon', 2],
      ['XZ-Tank Cannon', 2],
      ['Blue-Eyes Ultimate Dragon', 1],
    ],
  },

  // ===========================================================================
  // 4. Joey Wheeler
  // ===========================================================================
  {
    id: 'joey-wheeler_deck_1',
    characterId: 'joey-wheeler',
    name: 'Duelist Kingdom Gamble & Dragons',
    archetype: 'Red-Eyes / Warrior / Gamble',
    description: 'Joey Wheeler\'s passionate underdog deck from Duelist Kingdom, starring Red-Eyes Black Dragon, Time Wizard, Flame Swordsman, and Thousand Dragon.',
    signatureCards: ['Red-Eyes Black Dragon', 'Time Wizard', 'Thousand Dragon'],
    main: [
      ['Red-Eyes Black Dragon', 1],
      ['Baby Dragon', 3],
      ['Time Wizard', 3],
      ['Swordsman of Landstar', 3],
      ['Alligator\'s Sword', 2],
      ['Axe Raider', 2],
      ['Garoozis', 2],
      ['Battle Steer', 2],
      ['Gearfried the Iron Knight', 2],
      ['Little-Winguard', 2],
      ['Polymerization', 2],
      ['Shield & Sword', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Graceful Dice', 3],
      ['Salamandra', 1],
      ['Kunai with Chain', 3],
      ['Skull Dice', 3],
      ['Trap Hole', 3],
    ],
    extra: [
      ['Thousand Dragon', 2],
      ['Flame Swordsman', 2],
    ],
  },
  {
    id: 'joey-wheeler_deck_2',
    characterId: 'joey-wheeler',
    name: 'Battle City Warrior & Jinzo',
    archetype: 'Warrior / Jinzo / Red-Eyes',
    description: 'Joey Wheeler\'s Battle City championship deck featuring the trap-annihilating Jinzo, Gearfried the Iron Knight, Rocket Warrior, and Red-Eyes Black Dragon.',
    signatureCards: ['Jinzo', 'Red-Eyes Black Dragon', 'Gearfried the Iron Knight'],
    main: [
      ['Red-Eyes Black Dragon', 1],
      ['Jinzo', 1],
      ['Gearfried the Iron Knight', 3],
      ['Panther Warrior', 2],
      ['Rocket Warrior', 2],
      ['Alligator\'s Sword', 2],
      ['Baby Dragon', 2],
      ['Time Wizard', 2],
      ['Little-Winguard', 2],
      ['Goblin Attack Force', 2],
      ['Swordsman of Landstar', 2],
      ['Polymerization', 2],
      ['Scapegoat', 2],
      ['Graceful Dice', 2],
      ['Question', 1],
      ['Shield & Sword', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Giant Trunade', 1],
      ['Foolish Burial', 1],
      ['Skull Dice', 2],
      ['Roulette Spider', 1],
      ['Fairy Box', 1],
      ['Magical Arm Shield', 1],
      ['Bottomless Trap Hole', 1],
      ['Kunai with Chain', 2],
    ],
    extra: [
      ['Alligator\'s Sword Dragon', 2],
      ['Thousand Dragon', 2],
      ['Flame Swordsman', 1],
    ],
  },

  // ===========================================================================
  // 5. Téa Gardner
  // ===========================================================================
  {
    id: 'tea-gardner_deck_1',
    characterId: 'tea-gardner',
    name: 'Angelic Friendship & St. Joan',
    archetype: 'Fairy / Life Point Gain',
    description: 'Téa Gardner\'s compassionate fairy deck from Nightmare Troubadour, Tag Force, and the Virtual World, utilizing continuous Life Point regeneration and St. Joan.',
    signatureCards: ['St. Joan', 'Dunames Dark Witch', 'Fire Princess'],
    main: [
      ['Dunames Dark Witch', 3],
      ['Fire Princess', 3],
      ['Darklord Marie', 2],
      ['The Forgiving Maiden', 2],
      ['Maha Vailo', 2],
      ['Dancing Elf', 2],
      ['Happy Lover', 2],
      ['Gellenduo', 2],
      ['Shining Angel', 2],
      ['Polymerization', 2],
      ['Solemn Wishes', 3],
      ['Dian Keto the Cure Master', 2],
      ['Gift of the Mystical Elf', 2],
      ['Silver Bow and Arrow', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Graceful Charity', 1],
      ['Waboku', 3],
      ['Draining Shield', 2],
      ['Bad Reaction to Simochi', 1],
      ['Magic Cylinder', 1],
    ],
    extra: [
      ['St. Joan', 2],
    ],
  },

  // ===========================================================================
  // 6. Tristan Taylor
  // ===========================================================================
  {
    id: 'tristan-taylor_deck_1',
    characterId: 'tristan-taylor',
    name: 'Battleguard & Cyber Assault',
    archetype: 'Warrior / Machine',
    description: 'Tristan Taylor\'s hard-hitting brawler deck from Duel Links, featuring Roboyarou, Robolady, Super Roboyarou, and the mighty Battleguard brothers.',
    signatureCards: ['Super Roboyarou', 'Lava Battleguard', 'Swamp Battleguard'],
    main: [
      ['Roboyarou', 3],
      ['Robolady', 3],
      ['Lava Battleguard', 3],
      ['Swamp Battleguard', 3],
      ['Command Knight', 3],
      ['Total Defense Shogun', 2],
      ['Acrobat Monkey', 2],
      ['Berserk Gorilla', 2],
      ['The Fiend Megacyber', 2],
      ['Swift Gaia the Fierce Knight', 1],
      ['Polymerization', 3],
      ['Fusion Sage', 2],
      ['Battleguard Howling', 3],
      ['Reinforcement of the Army', 1],
      ['The Warrior Returning Alive', 2],
      ['Kunai with Chain', 2],
      ['Scapegoat', 2],
      ['Shield & Sword', 1],
      ['Waboku', 2],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Super Roboyarou', 2],
      ['Super Robolady', 2],
    ],
  },

  // ===========================================================================
  // 7. Mai Valentine
  // ===========================================================================
  {
    id: 'mai-valentine_deck_1',
    characterId: 'mai-valentine',
    name: 'Duelist Kingdom Harpie Swarm',
    archetype: 'Harpie / Winged Beast',
    description: 'Mai Valentine\'s classic fragrance tactic deck multiplying Harpie Ladies with Elegant Egotist and buffing Harpie\'s Pet Dragon.',
    signatureCards: ['Harpie Lady Sisters', 'Harpie\'s Pet Dragon', 'Cyber Harpie Lady'],
    main: [
      ['Cyber Harpie Lady', 1],
      ['Harpie Lady 1', 1],
      ['Harpie Lady 2', 1],
      ['Harpie Queen', 1],
      ['Harpie Lady Sisters', 2],
      ['Harpie\'s Pet Dragon', 2],
      ['Harpie\'s Pet Baby Dragon', 1],
      ['Harpie Channeler', 3],
      ['Harpie Harpist', 3],
      ['Birdface', 3],
      ['Sonic Duck', 2],
      ['Elegant Egotist', 3],
      ['Harpie\'s Feather Duster', 1],
      ['Cyber Shield', 2],
      ['Swords of Revealing Light', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Graceful Charity', 1],
      ['Mirror Wall', 2],
      ['Hysteric Party', 3],
      ['Icarus Attack', 3],
      ['Shadow of Eyes', 2],
    ],
  },
  {
    id: 'mai-valentine_deck_2',
    characterId: 'mai-valentine',
    name: 'Battle City Amazoness & Harpies',
    archetype: 'Amazoness / Harpie',
    description: 'Mai\'s aggressive Battle City tournament deck merging ferocious Amazoness combatants with the tactical strikes of Harpie Ladies.',
    signatureCards: ['Amazoness Swords Woman', 'Amazoness Fighter', 'Harpie Lady 1'],
    main: [
      ['Amazoness Swords Woman', 3],
      ['Amazoness Fighter', 3],
      ['Amazoness Paladin', 3],
      ['Amazoness Trainee', 1],
      ['Amazoness Chain Master', 2],
      ['Amazoness Princess', 3],
      ['Cyber Harpie Lady', 1],
      ['Harpie Lady 1', 1],
      ['Harpie Lady 2', 1],
      ['Harpie\'s Pet Baby Dragon', 2],
      ['Amazoness Call', 3],
      ['Amazoness Heirloom', 2],
      ['Harpie\'s Feather Duster', 1],
      ['Reinforcement of the Army', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Amazoness Archers', 2],
      ['Amazoness Onslaught', 3],
      ['Mirror Wall', 2],
      ['Dramatic Rescue', 2],
      ['Waboku', 2],
    ],
  },

  // ===========================================================================
  // 8. Bakura Ryou (Yami Bakura)
  // ===========================================================================
  {
    id: 'bakura-ryou_deck_1',
    characterId: 'bakura-ryou',
    name: 'Battle City Destiny Board',
    archetype: 'Fiend / Destiny Board / Occult',
    description: 'Yami Bakura\'s chilling occult deck spelling the inevitable F-I-N-A-L doom through Destiny Board and the horrifying Dark Necrofear.',
    signatureCards: ['Dark Necrofear', 'Destiny Board', 'Spirit Message "I"'],
    main: [
      ['Dark Necrofear', 2],
      ['Headless Knight', 3],
      ['The Gross Ghost of Fled Dreams', 3],
      ['Jowgen the Spiritualist', 2],
      ['Sangan', 1],
      ['Morphing Jar', 1],
      ['Puppet Master', 2],
      ['Gernia', 2],
      ['Dark Ruler Ha Des', 1],
      ['Destiny Board', 2],
      ['Spirit Message "I"', 1],
      ['Spirit Message "N"', 1],
      ['Spirit Message "A"', 1],
      ['Spirit Message "L"', 1],
      ['Dark Sanctuary', 3],
      ['The Dark Door', 2],
      ['The Shallow Grave', 2],
      ['Card Destruction', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Call of the Haunted', 2],
      ['Zoma the Spirit', 2],
      ['Mirror Force', 1],
      ['Just Desserts', 2],
    ],
  },

  // ===========================================================================
  // 9. Marik Ishtar (Yami Marik)
  // ===========================================================================
  {
    id: 'marik-ishtar_deck_1',
    characterId: 'marik-ishtar',
    name: 'Immortal Winged Dragon of Ra',
    archetype: 'Egyptian God / Burn & Torture',
    description: 'Yami Marik\'s sadistic torture deck unleashing Lava Golem, Nightmare Wheel, and the ultimate divine beast, The Winged Dragon of Ra.',
    signatureCards: ['The Winged Dragon of Ra', 'Lava Golem', 'The Winged Dragon of Ra - Sphere Mode'],
    main: [
      ['The Winged Dragon of Ra', 2],
      ['The Winged Dragon of Ra - Sphere Mode', 1],
      ['The Winged Dragon of Ra - Immortal Phoenix', 1],
      ['Lava Golem', 2],
      ['Juragedo', 3],
      ['Holding Arms', 2],
      ['Holding Legs', 2],
      ['Bowganian', 2],
      ['Drillago', 2],
      ['Gil Garth', 2],
      ['Viser Des', 2],
      ['Helpoemer', 1],
      ['Dark Jeroid', 2],
      ['Ancient Chant', 3],
      ['Mound of the Bound Creator', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Dark Hole', 1],
      ['Card of Sanctity', 1],
      ['Card of Safe Return', 1],
      ['Metal Reflect Slime', 3],
      ['Nightmare Wheel', 3],
      ['Coffin Seller', 2],
      ['Mirror Force', 1],
    ],
  },

  // ===========================================================================
  // 10. Maximillion Pegasus
  // ===========================================================================
  {
    id: 'maximillion-pegasus_deck_1',
    characterId: 'maximillion-pegasus',
    name: 'Toon World Kingdom',
    archetype: 'Toon',
    description: 'The creator of Duel Monsters reveals his whimsical and invincible cartoon creations popping straight out of Toon World.',
    signatureCards: ['Toon Kingdom', 'Blue-Eyes Toon Dragon', 'Toon Dark Magician Girl'],
    main: [
      ['Blue-Eyes Toon Dragon', 2],
      ['Toon Dark Magician Girl', 2],
      ['Toon Summoned Skull', 2],
      ['Toon Cyber Dragon', 1],
      ['Toon Buster Blader', 1],
      ['Toon Mermaid', 3],
      ['Toon Masked Sorcerer', 3],
      ['Toon Gemini Elf', 3],
      ['Manga Ryu-Ran', 1],
      ['Toon Kingdom', 3],
      ['Toon World', 2],
      ['Toon Table of Contents', 3],
      ['Comic Hand', 2],
      ['Shadow Toon', 2],
      ['Toon Rollback', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Toon Briefcase', 3],
      ['Toon Mask', 3],
      ['Mirror Force', 1],
    ],
  },
  {
    id: 'maximillion-pegasus_deck_2',
    characterId: 'maximillion-pegasus',
    name: 'Relinquished & Thousand-Eyes Restrict',
    archetype: 'Illusion / Ritual / Fusion',
    description: 'Pegasus\'s horrifying dark illusion deck absorbing opposing monsters as equip spells with Relinquished and Thousand-Eyes Restrict.',
    signatureCards: ['Relinquished', 'Thousand-Eyes Restrict', 'Black Illusion Ritual'],
    main: [
      ['Relinquished', 3],
      ['Thousand-Eyes Idol', 3],
      ['Dark-Eyes Illusionist', 3],
      ['Illusionist Faceless Mage', 2],
      ['Jigen Bakudan', 2],
      ['Manju of the Ten Thousand Hands', 3],
      ['Senju of the Thousand Hands', 3],
      ['Sonic Bird', 3],
      ['Black Illusion Ritual', 3],
      ['Polymerization', 2],
      ['Fusion Sage', 2],
      ['Preparation of Rites', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Waboku', 3],
      ['Ring of Destruction', 1],
      ['Mirror Force', 1],
      ['Magic Cylinder', 1],
      ['Secret Pass to the Treasures', 1],
    ],
    extra: [
      ['Thousand-Eyes Restrict', 3],
    ],
  },

  // ===========================================================================
  // 11. Bandit Keith
  // ===========================================================================
  {
    id: 'bandit-keith_deck_1',
    characterId: 'bandit-keith',
    name: 'Duelist Kingdom Heavy Machines',
    archetype: 'Machine / Coin Toss',
    description: 'Bandit Keith\'s American Machine arsenal gunning down enemies with Blowback Dragon, Twin-Barrel Dragon, Machine King, and heavy Metalmorph upgrades.',
    signatureCards: ['Blowback Dragon', 'Twin-Barrel Dragon', 'Metalzoa'],
    main: [
      ['Blowback Dragon', 3],
      ['Twin-Barrel Dragon', 3],
      ['Slot Machine', 2],
      ['Blast Sphere', 3],
      ['Machine King', 2],
      ['Pendulum Machine', 2],
      ['Launcher Spider', 2],
      ['Zoa', 2],
      ['Metalzoa', 1],
      ['Heavy Mech Support Platform', 3],
      ['Dekoichi the Battlechanted Locomotive', 3],
      ['7 Completed', 3],
      ['Heavy Storm', 1],
      ['Limiter Removal', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Metalmorph', 3],
      ['Time Machine', 2],
      ['Second Coin Toss', 2],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
    ],
  },

  // ===========================================================================
  // 12. Weevil Underwood
  // ===========================================================================
  {
    id: 'weevil-underwood_deck_1',
    characterId: 'weevil-underwood',
    name: 'Perfect Great Moth Evolution',
    archetype: 'Insect / Evolution',
    description: 'Weevil Underwood\'s signature forest deck defending the Cocoon of Evolution until the cataclysmic Perfectly Ultimate Great Moth emerges.',
    signatureCards: ['Perfectly Ultimate Great Moth', 'Cocoon of Evolution', 'Great Moth'],
    main: [
      ['Larvae Moth', 2],
      ['Cocoon of Evolution', 3],
      ['Great Moth', 2],
      ['Perfectly Ultimate Great Moth', 1],
      ['Basic Insect', 3],
      ['Gokibore', 2],
      ['Killer Needle', 2],
      ['Flying Kamakiri #1', 3],
      ['Pinch Hopper', 3],
      ['4-Starred Ladybug of Doom', 2],
      ['Forest', 3],
      ['Laser Cannon Armor', 3],
      ['Swords of Revealing Light', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Insect Barrier', 3],
      ['DNA Surgery', 3],
      ['Mirror Force', 1],
      ['Corrosive Scales', 2],
    ],
  },
  {
    id: 'weevil-underwood_deck_2',
    characterId: 'weevil-underwood',
    name: 'Battle City Insect Queen Swarm',
    archetype: 'Insect / Swarm',
    description: 'Weevil\'s Battle City swarm deck infesting the opponent\'s cards with Parasite Paracide and feeding the mighty Insect Queen.',
    signatureCards: ['Insect Queen', 'Parasite Paracide', 'Insect Barrier'],
    main: [
      ['Insect Queen', 2],
      ['Parasite Paracide', 3],
      ['Pinch Hopper', 3],
      ['Flying Kamakiri #1', 3],
      ['Howling Insect', 3],
      ['Skull-Mark Ladybug', 2],
      ['Girochin Kuwagata', 2],
      ['Insect Princess', 2],
      ['Insect Barrier', 3],
      ['DNA Surgery', 3],
      ['Insect Imitation', 2],
      ['Eradicating Aerosol', 2],
      ['Verdant Sanctuary', 3],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Mirror Force', 1],
      ['Threatening Roar', 3],
      ['Spider Web', 2],
    ],
  },

  // ===========================================================================
  // 13. Rex Raptor
  // ===========================================================================
  {
    id: 'rex-raptor_deck_1',
    characterId: 'rex-raptor',
    name: 'Duelist Kingdom Dinosaur Rampage',
    archetype: 'Dinosaur / Dragon',
    description: 'Rex Raptor\'s Jurassic beatdown deck from Duelist Kingdom, starring Two-Headed King Rex, Uraby, Crawling Dragon #2, and Serpent Night Dragon.',
    signatureCards: ['Two-Headed King Rex', 'Serpent Night Dragon', 'Red-Eyes Black Dragon'],
    main: [
      ['Two-Headed King Rex', 3],
      ['Uraby', 3],
      ['Crawling Dragon #2', 3],
      ['Gilasaurus', 3],
      ['Black Tyranno', 2],
      ['Tyranno Infinity', 2],
      ['Hydrogeddon', 3],
      ['Serpent Night Dragon', 1],
      ['Red-Eyes Black Dragon', 1],
      ['Wasteland', 3],
      ['Jurassic World', 3],
      ['Fossil Dig', 3],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Tail Swipe', 2],
      ['Survival Instinct', 2],
      ['Trap Hole', 3],
      ['Mirror Force', 1],
    ],
  },

  // ===========================================================================
  // 14. Mako Tsunami
  // ===========================================================================
  {
    id: 'mako-tsunami_deck_1',
    characterId: 'mako-tsunami',
    name: 'Ocean Realm & Legendary Fisherman',
    archetype: 'WATER / Sea Serpent / Fish',
    description: 'Mako Tsunami\'s oceanic powerhouse deck hiding beneath the tidal waves of A Legendary Ocean and striking with The Legendary Fisherman and Amphibian Beast.',
    signatureCards: ['The Legendary Fisherman', 'Amphibian Beast', 'A Legendary Ocean'],
    main: [
      ['The Legendary Fisherman', 3],
      ['The Legendary Fisherman II', 2],
      ['Amphibian Beast', 2],
      ['Kairyu-Shin', 2],
      ['Great White', 3],
      ['Abyss Soldier', 3],
      ['Giga Gagagigo', 3],
      ['Star Boy', 2],
      ['Warrior of Atlantis', 3],
      ['Jellyfish', 2],
      ['Fortress Whale', 1],
      ['Fortress Whale\'s Oath', 1],
      ['A Legendary Ocean', 3],
      ['Big Wave Small Wave', 2],
      ['Salvage', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Torrential Tribute', 1],
      ['Tornado Wall', 2],
      ['Sea Stealth Attack', 2],
    ],
  },

  // ===========================================================================
  // 15. Ishizu Ishtar
  // ===========================================================================
  {
    id: 'ishizu-ishtar_deck_1',
    characterId: 'ishizu-ishtar',
    name: 'Gravekeeper\'s & Exchange of the Spirit',
    archetype: 'Earth Fairy / Gravekeeper / Deck Mill',
    description: 'Ishizu Ishtar\'s Millennium Necklace prophetic deck manipulating graveyard states and reversing destinies with Exchange of the Spirit.',
    signatureCards: ['Exchange of the Spirit', 'Keldo', 'Mudora'],
    main: [
      ['Keldo', 3],
      ['Mudora', 3],
      ['Agido', 3],
      ['Kelbek', 3],
      ['Zolga', 3],
      ['Gravekeeper\'s Spy', 3],
      ['Gravekeeper\'s Guard', 2],
      ['Gravekeeper\'s Spear Soldier', 2],
      ['Necrovalley', 3],
      ['Terraforming', 1],
      ['Gravekeeper\'s Stele', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Card Destruction', 1],
      ['Exchange of the Spirit', 1],
      ['Blast Held by a Tribute', 2],
      ['Rite of Spirit', 3],
      ['Mirror Force', 1],
      ['Waboku', 2],
    ],
  },

  // ===========================================================================
  // 16. Odion
  // ===========================================================================
  {
    id: 'odion_deck_1',
    characterId: 'odion',
    name: 'Temple of the Kings & Apophis',
    archetype: 'Continuous Trap / Trap Monster',
    description: 'Odion\'s stoic trap fortress deck punishing attackers through Embodiment of Apophis and releasing the forbidden Mystical Beast of Serket.',
    signatureCards: ['Mystical Beast of Serket', 'Temple of the Kings', 'Embodiment of Apophis'],
    main: [
      ['Mystical Beast of Serket', 2],
      ['Dark Jeroid', 3],
      ['Aswan Apparition', 3],
      ['Gravekeeper\'s Assailant', 3],
      ['Temple of the Kings', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Swords of Revealing Light', 1],
      ['Embodiment of Apophis', 3],
      ['Zoma the Spirit', 3],
      ['Tiki Soul', 3],
      ['Tiki Curse', 3],
      ['Curse of Darkness', 2],
      ['Dark Room of Nightmare', 2],
      ['Judgment of Anubis', 2],
      ['Imperial Custom', 3],
      ['Mirror Force', 1],
      ['Metal Reflect Slime', 2],
    ],
  },

  // ===========================================================================
  // 17. Espa Roba
  // ===========================================================================
  {
    id: 'espa-roba_deck_1',
    characterId: 'espa-roba',
    name: 'Jinzo Psychic Shockwave',
    archetype: 'Jinzo / Machine Stun',
    description: 'Espa Roba\'s psychic transmission deck nullifying all traps on the field with Jinzo, Jinzo - Returner, and Jinzo - Lord.',
    signatureCards: ['Jinzo', 'Jinzo - Lord', 'Psychic Shockwave'],
    main: [
      ['Jinzo', 2],
      ['Jinzo - Returner', 3],
      ['Jinzo - Jector', 3],
      ['Jinzo #7', 2],
      ['Jinzo - Lord', 1],
      ['Reflect Bounder', 3],
      ['Cyber-Tech Alligator', 2],
      ['The Fiend Megacyber', 2],
      ['Mind on Air', 2],
      ['Amplifier', 2],
      ['Heavy Storm', 1],
      ['Limiter Removal', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Brain Control', 1],
      ['Psychic Shockwave', 3],
      ['Bottomless Trap Hole', 2],
      ['Threatening Roar', 3],
      ['Trap Hole', 2],
      ['Compulsory Evacuation Device', 2],
      ['Mirror Force', 1],
    ],
  },

  // ===========================================================================
  // 18. Arkana
  // ===========================================================================
  {
    id: 'arkana_deck_1',
    characterId: 'arkana',
    name: 'Show of Illusion & Red Dark Magician',
    archetype: 'Dark Magician / Ectoplasmer Burn',
    description: 'Arkana\'s deadly Pandora magic show sacrificing monsters to Ectoplasmer and commanding his ruthless red-robed Dark Magician.',
    signatureCards: ['Dark Magician', 'Ectoplasmer', 'Malice Doll of Demise'],
    main: [
      ['Dark Magician', 3],
      ['Malice Doll of Demise', 3],
      ['Skilled Dark Magician', 3],
      ['Apprentice Magician', 3],
      ['Old Vindictive Magician', 3],
      ['Breaker the Magical Warrior', 2],
      ['Ectoplasmer', 3],
      ['Dark Magic Curtain', 2],
      ['Thousand Knives', 2],
      ['Dark Magic Attack', 1],
      ['Mystic Box', 2],
      ['Magical Dimension', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Magician\'s Circle', 3],
      ['Nightmare Wheel', 2],
      ['Mirror Force', 1],
      ['Call of the Haunted', 2],
      ['Waboku', 2],
    ],
  },

  // ===========================================================================
  // 19. Rafael
  // ===========================================================================
  {
    id: 'rafael_deck_1',
    characterId: 'rafael',
    name: 'Guardians of Sacred Light',
    archetype: 'Guardian / Equip Spell',
    description: 'Rafael\'s deep bond with his monsters refusing to send them to the graveyard, commanding Guardian Eatos and ancestral guardian weapons.',
    signatureCards: ['Guardian Eatos', 'Guardian Grarl', 'Arsenal Summoner'],
    main: [
      ['Guardian Eatos', 3],
      ['Guardian Grarl', 3],
      ['Guardian Baou', 2],
      ['Guardian Kay\'est', 2],
      ['Guardian Ceal', 2],
      ['Guardian Elma', 2],
      ['Arsenal Summoner', 3],
      ['Gravity Axe - Grarl', 3],
      ['Wicked-Breaking Flamberge - Baou', 2],
      ['Rod of the Mind\'s Eye', 2],
      ['Shooting Star Bow - Ceal', 2],
      ['Butterfly Dagger - Elma', 1],
      ['Celestial Sword - Eatos', 3],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Swords of Revealing Light', 1],
      ['Reinforcement of the Army', 1],
      ['Hidden Armory', 3],
      ['Mirror Force', 1],
      ['Dimensional Prison', 2],
    ],
  },

  // ===========================================================================
  // 20. Dartz
  // ===========================================================================
  {
    id: 'dartz_deck_1',
    characterId: 'dartz',
    name: 'Orichalcos Seal of Atlantis',
    archetype: 'Orichalcos / High ATK',
    description: 'Dartz\'s 10,000-year-old Atlantean empire deck channeling the malevolent power of The Seal of Orichalcos and Orichalcos Shunoros.',
    signatureCards: ['The Seal of Orichalcos', 'Orichalcos Shunoros'],
    main: [
      ['Orichalcos Shunoros', 2],
      ['Vorse Raider', 3],
      ['Gene-Warped Warwolf', 3],
      ['Luster Dragon', 3],
      ['Archfiend Soldier', 3],
      ['Mad Dog of Darkness', 3],
      ['Breaker the Magical Warrior', 2],
      ['Sangan', 1],
      ['Morphing Jar', 1],
      ['The Seal of Orichalcos', 2],
      ['Terraforming', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Swords of Revealing Light', 1],
      ['Call of the Haunted', 2],
      ['Mirror Force', 1],
      ['Torrential Tribute', 1],
      ['Bottomless Trap Hole', 2],
      ['Solemn Judgment', 2],
    ],
  },

  // ===========================================================================
  // Additional Authentic Canon Expansions
  // ===========================================================================

  // 1. Yami Yugi - Ceremonial Battle Three Egyptian Gods
  {
    id: 'yami-yugi_deck_4',
    characterId: 'yami-yugi',
    name: 'Ceremonial Battle: Three Egyptian Gods',
    archetype: 'Egyptian God / Royal Court',
    description: 'Atem\'s transcendent final deck summoning all three Egyptian Gods simultaneously through the Royal Court Face Knights and Arcana Knight Joker.',
    signatureCards: ['Slifer the Sky Dragon', 'Obelisk the Tormentor', 'The Winged Dragon of Ra'],
    main: [
      ['Slifer the Sky Dragon', 1],
      ['Obelisk the Tormentor', 1],
      ['The Winged Dragon of Ra', 1],
      ['King\'s Knight', 3],
      ['Queen\'s Knight', 3],
      ['Jack\'s Knight', 3],
      ['Dark Magician', 2],
      ['Dark Magician Girl', 1],
      ['Buster Blader', 1],
      ['Big Shield Gardna', 2],
      ['Watapon', 1],
      ['Polymerization', 2],
      ['Fusion Sage', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Card of Sanctity', 1],
      ['Swords of Revealing Light', 1],
      ['Reinforcement of the Army', 1],
      ['The Warrior Returning Alive', 2],
      ['Thousand Knives', 1],
      ['Dark Magic Attack', 1],
      ['Mirror Force', 1],
      ['Magical Hats', 2],
      ['Spellbinding Circle', 2],
      ['Call of the Haunted', 2],
      ['Solemn Judgment', 1],
    ],
    extra: [
      ['Arcana Knight Joker', 2],
      ['Dark Paladin', 2],
    ],
  },

  // 2. Yugi Muto - Magician Girls & Gadget Dimension
  {
    id: 'yugi-muto_deck_3',
    characterId: 'yugi-muto',
    name: 'Magician Girls & Gadget Dimension',
    archetype: 'Magician Girl / Gadget Dimension',
    description: 'Yugi Muto\'s canonical Dark Side of Dimensions deck linking the six Magician Girls with Gold and Silver Gadget recursion and defensive dimension barriers.',
    signatureCards: ['Berry Magician Girl', 'Dark Magician Girl', 'Gold Gadget'],
    main: [
      ['Berry Magician Girl', 3],
      ['Chocolate Magician Girl', 3],
      ['Apple Magician Girl', 3],
      ['Lemon Magician Girl', 2],
      ['Kiwi Magician Girl', 2],
      ['Dark Magician Girl', 2],
      ['Dark Magician', 1],
      ['Gold Gadget', 3],
      ['Silver Gadget', 3],
      ['Marshmacaron', 3],
      ['Clear Kuriboh', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Dark Magic Curtain', 1],
      ['Magicians\' Defense', 2],
      ['Dimension Sphinx', 2],
      ['Dimension Guardian', 2],
      ['Dimension Mirage', 2],
      ['Dig of Destiny', 1],
      ['Spiritual Swords of Revealing Light', 1],
    ],
  },

  // 3. Seto Kaiba - Neo Blue-Eyes Chaos MAX Ritual
  {
    id: 'seto-kaiba_deck_3',
    characterId: 'seto-kaiba',
    name: 'Neo Blue-Eyes Chaos MAX Ritual',
    archetype: 'Blue-Eyes / Chaos Ritual',
    description: 'Kaiba\'s supreme modern transcendence deck summoning the invincible Blue-Eyes Chaos MAX Dragon with Chaos Form and fusing Neo Blue-Eyes Ultimate Dragon.',
    signatureCards: ['Blue-Eyes Chaos MAX Dragon', 'Chaos Form', 'Blue-Eyes Alternative White Dragon'],
    main: [
      ['Blue-Eyes Chaos MAX Dragon', 3],
      ['Blue-Eyes Alternative White Dragon', 3],
      ['Blue-Eyes White Dragon', 3],
      ['Deep-Eyes White Dragon', 1],
      ['Assault Wyvern', 3],
      ['Krystal Dragon', 2],
      ['Manju of the Ten Thousand Hands', 3],
      ['The White Stone of Legend', 2],
      ['Chaos Form', 3],
      ['Dragon Shrine', 3],
      ['Dragon\'s Fighting Spirit', 2],
      ['Trade-In', 3],
      ['Polymerization', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Burst Stream of Destruction', 2],
      ['Mirror Force', 1],
      ['Interdimensional Matter Transporter', 2],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 1],
    ],
    extra: [
      ['Neo Blue-Eyes Ultimate Dragon', 3],
      ['Blue-Eyes Ultimate Dragon', 2],
    ],
  },

  // 4. Seto Kaiba - Crush Card & Virus Lockdown
  {
    id: 'seto-kaiba_deck_4',
    characterId: 'seto-kaiba',
    name: 'Crush Card & Virus Lockdown',
    archetype: 'Virus Control / Beatdown',
    description: 'Kaiba\'s classic video-game control deck decimating the opponent\'s hand and field with Crush Card Virus and Deck Devastation Virus while commanding high-ATK beaters.',
    signatureCards: ['Crush Card Virus', 'Deck Devastation Virus', 'Doomcaliber Knight'],
    main: [
      ['Blue-Eyes White Dragon', 3],
      ['Doomcaliber Knight', 3],
      ['Vorse Raider', 3],
      ['Blade Knight', 3],
      ['Peten the Dark Clown', 3],
      ['Kaiser Sea Horse', 2],
      ['Different Dimension Dragon', 2],
      ['Sangan', 1],
      ['Enemy Controller', 3],
      ['Shrink', 3],
      ['Cost Down', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Polymerization', 2],
      ['Crush Card Virus', 2],
      ['Deck Devastation Virus', 2],
      ['Ring of Destruction', 1],
      ['Shadow Spell', 2],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Blue-Eyes Ultimate Dragon', 2],
    ],
  },

  // 5. Joey Wheeler - The Claw of Hermos & Lord of the Red
  {
    id: 'joey-wheeler_deck_3',
    characterId: 'joey-wheeler',
    name: 'The Claw of Hermos & Lord of the Red',
    archetype: 'Hermos / Red-Eyes Ritual',
    description: 'Joey\'s Waking the Dragons armory wielding The Claw of Hermos to forge dragon weapons alongside the explosive ritual armor of Lord of the Red.',
    signatureCards: ['The Claw of Hermos', 'Lord of the Red', 'Red-Eyes Black Dragon Sword'],
    main: [
      ['Lord of the Red', 2],
      ['Red-Eyes Black Dragon', 3],
      ['Gearfried the Swordmaster', 1],
      ['Gearfried the Iron Knight', 3],
      ['Rocket Warrior', 3],
      ['Time Wizard', 2],
      ['Baby Dragon', 2],
      ['Alligator\'s Sword', 2],
      ['Manju of the Ten Thousand Hands', 3],
      ['The Claw of Hermos', 3],
      ['Red-Eyes Transmigration', 2],
      ['Release Restraint', 2],
      ['Dangerous Machine Type-6', 2],
      ['Polymerization', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Graceful Dice', 2],
      ['Skull Dice', 2],
      ['Kunai with Chain', 2],
    ],
    extra: [
      ['Red-Eyes Black Dragon Sword', 2],
      ['Time Magic Hammer', 2],
      ['Rocket Hermos Cannon', 2],
      ['Thousand Dragon', 1],
      ['Alligator\'s Sword Dragon', 1],
    ],
  },

  // 6. Marik Ishtar - Slime Control & Torture Lockdown
  {
    id: 'marik-ishtar_deck_2',
    characterId: 'marik-ishtar',
    name: 'Slime Control & Torture Lockdown',
    archetype: 'Slime Control / Stall Burn',
    description: 'Marik\'s agonizing Battle City control deck locking down the field with Revival Jam, Jam Defender, and Metal Reflect Slime while inflicting torture burn with Lava Golem.',
    signatureCards: ['Revival Jam', 'Jam Defender', 'Metal Reflect Slime'],
    main: [
      ['Revival Jam', 3],
      ['Humanoid Slime', 3],
      ['Worm Drake', 2],
      ['Lava Golem', 2],
      ['Bowganian', 3],
      ['Drillago', 2],
      ['Holding Legs', 2],
      ['Holding Arms', 2],
      ['Jam Breeding Machine', 3],
      ['Card of Safe Return', 2],
      ['Infinite Cards', 2],
      ['Nightmare\'s Steelcage', 2],
      ['Polymerization', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Jam Defender', 3],
      ['Metal Reflect Slime', 3],
      ['Coffin Seller', 2],
    ],
    extra: [
      ['Humanoid Worm Drake', 2],
    ],
  },

  // 7. Mako Tsunami - Ocean Lord Levia-Dragon Daedalus
  {
    id: 'mako-tsunami_deck_2',
    characterId: 'mako-tsunami',
    name: 'Ocean Lord Levia-Dragon Daedalus',
    archetype: 'Umi / Daedalus Tsunami',
    description: 'Mako\'s devastating video-game boss deck sacrificing A Legendary Ocean to wipe the entire opponent\'s field with Levia-Dragon - Daedalus and Neo-Daedalus.',
    signatureCards: ['Levia-Dragon - Daedalus', 'Ocean Dragon Lord - Neo-Daedalus', 'A Legendary Ocean'],
    main: [
      ['Levia-Dragon - Daedalus', 3],
      ['Ocean Dragon Lord - Neo-Daedalus', 2],
      ['The Legendary Fisherman', 2],
      ['Warrior of Atlantis', 3],
      ['Codarus', 3],
      ['Amphibian Beast', 2],
      ['Abyssal Kingshark', 2],
      ['Hydrogeddon', 3],
      ['A Legendary Ocean', 3],
      ['Big Wave Small Wave', 2],
      ['Sea Stealth Attack', 2],
      ['Salvage', 2],
      ['Terraforming', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Tornado Wall', 2],
      ['Torrential Tribute', 1],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
      ['Gravity Bind', 2],
    ],
  },

  // 8. Yami Bakura - Dark Master - Zorc & Occult Fiends
  {
    id: 'bakura-ryou_deck_2',
    characterId: 'bakura-ryou',
    name: 'Dark Master - Zorc & Occult Fiends',
    archetype: 'Zorc Ritual / Occult Fiend',
    description: 'Bakura\'s dark video-game ritual deck rolling the die of doom with Dark Master - Zorc while disrupting opposing boards with Doomcaliber Knight and occult fiends.',
    signatureCards: ['Dark Master - Zorc', 'Contract with the Dark Master', 'Doomcaliber Knight'],
    main: [
      ['Dark Master - Zorc', 3],
      ['Dark Necrofear', 2],
      ['Doomcaliber Knight', 3],
      ['Headless Knight', 3],
      ['Man-Eater Bug', 3],
      ['Newdoria', 3],
      ['Jowgen the Spiritualist', 2],
      ['Sangan', 1],
      ['Morphing Jar', 1],
      ['Contract with the Dark Master', 3],
      ['Dark Sanctuary', 2],
      ['The Dark Door', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Card Destruction', 1],
      ['Dark Core', 2],
      ['Just Desserts', 3],
      ['Mirror Force', 1],
      ['Call of the Haunted', 2],
      ['Solemn Judgment', 1],
    ],
  },

  // 9. Mai Valentine - Seal of Orichalcos Harpie Flight
  {
    id: 'mai-valentine_deck_3',
    characterId: 'mai-valentine',
    name: 'Seal of Orichalcos Harpie Flight',
    archetype: 'Orichalcos / Harpie',
    description: 'Mai\'s corrupted Doma deck boosting her Harpie flock with The Seal of Orichalcos and executing sweeping aerial assaults with Harpie Lady Phoenix Formation.',
    signatureCards: ['The Seal of Orichalcos', 'Harpie Lady Phoenix Formation', 'Cyber Harpie Lady'],
    main: [
      ['The Seal of Orichalcos', 2],
      ['Harpie Lady 1', 1],
      ['Harpie Lady 2', 1],
      ['Cyber Harpie Lady', 1],
      ['Harpie Lady Sisters', 2],
      ['Harpie\'s Pet Baby Dragon', 2],
      ['Harpie\'s Pet Dragon', 2],
      ['Harpie Channeler', 3],
      ['Harpie Harpist', 3],
      ['Harpie Queen', 3],
      ['Birdface', 2],
      ['Harpie Lady Phoenix Formation', 2],
      ['Elegant Egotist', 3],
      ['Harpie\'s Feather Duster', 1],
      ['Cyber Shield', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Hysteric Party', 3],
      ['Icarus Attack', 3],
      ['Mirror Wall', 2],
    ],
  },

  // 10. Rex Raptor - Seal of Orichalcos Tyrant Dinosaur
  {
    id: 'rex-raptor_deck_2',
    characterId: 'rex-raptor',
    name: 'Seal of Orichalcos Tyrant Dinosaur',
    archetype: 'Orichalcos / Dragon Dinosaur',
    description: 'Rex Raptor\'s Doma deck combining prehistoric carnivores and high-level dragons under The Seal of Orichalcos with Tyrant Dragon and Black Tyranno.',
    signatureCards: ['The Seal of Orichalcos', 'Tyrant Dragon', 'Black Tyranno'],
    main: [
      ['The Seal of Orichalcos', 2],
      ['Tyrant Dragon', 2],
      ['Black Tyranno', 2],
      ['Gilasaurus', 3],
      ['Element Saurus', 3],
      ['Hyper Hammerhead', 3],
      ['Babycerasaurus', 3],
      ['Hydrogeddon', 3],
      ['Two-Headed King Rex', 3],
      ['Jurassic World', 3],
      ['Fossil Dig', 3],
      ['Tail Swipe', 2],
      ['Terraforming', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Survival Instinct', 2],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
    ],
  },

  // 11. Rafael - Dark Rafael: Guardian Dreadscythe
  {
    id: 'rafael_deck_2',
    characterId: 'rafael',
    name: 'Dark Rafael: Guardian Dreadscythe',
    archetype: 'Guardian / Dark Dreadscythe',
    description: 'Rafael giving in to the darkness: unleashing Guardian Dreadscythe and Reaper Scythe - Dreadscythe to drain the strength of fallen souls in both graveyards.',
    signatureCards: ['Guardian Dreadscythe', 'Reaper Scythe - Dreadscythe', 'Guardian Eatos'],
    main: [
      ['Guardian Dreadscythe', 2],
      ['Guardian Eatos', 3],
      ['Guardian Baou', 3],
      ['Guardian Grarl', 2],
      ['Guardian Ceal', 2],
      ['Arsenal Summoner', 3],
      ['Morphing Jar', 1],
      ['Sangan', 1],
      ['Reaper Scythe - Dreadscythe', 2],
      ['Celestial Sword - Eatos', 2],
      ['Wicked-Breaking Flamberge - Baou', 2],
      ['Gravity Axe - Grarl', 2],
      ['Shooting Star Bow - Ceal', 2],
      ['Soul Charge', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Heavy Storm', 1],
      ['Dark Hole', 1],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 2],
      ['Bottomless Trap Hole', 2],
      ['Threatening Roar', 2],
    ],
  },
];

