import type { DeckDefinition } from './deckValidatorHelper.ts';

export const FIVE_DS_AUTHENTIC_DECKS: DeckDefinition[] = [
  // ===========================================================================
  // 1. Yusei Fudo
  // ===========================================================================
  {
    id: 'yusei-fudo_deck_1',
    characterId: 'yusei-fudo',
    name: 'Junk & Stardust Synchro',
    archetype: 'Junk / Stardust Synchro',
    description: "Yusei Fudo's signature Synchro deck combining Junk Synchron, Doppelwarrior, and Quillbolt Hedgehog to summon Junk Warrior, Stardust Dragon, and Shooting Star Dragon.",
    signatureCards: ['Stardust Dragon', 'Junk Warrior', 'Junk Synchron'],
    main: [
      ['Junk Synchron', 3],
      ['Quickdraw Synchron', 2],
      ['Doppelwarrior', 3],
      ['Quillbolt Hedgehog', 3],
      ['Tuningware', 2],
      ['Level Eater', 2],
      ['Synchron Explorer', 2],
      ['Sonic Chick', 1],
      ['Shield Wing', 1],
      ['Debris Dragon', 2],
      ['Dandylion', 1],
      ['Effect Veiler', 2],
      ['Unknown Synchron', 1],
      ['Tuning', 3],
      ['Pot of Avarice', 1],
      ['Reinforcement of the Army', 1],
      ['One for One', 1],
      ['Monster Reborn', 1],
      ['Foolish Burial', 1],
      ['Mind Control', 1],
      ['Scrap-Iron Scarecrow', 2],
      ['Starlight Road', 2],
      ['Graceful Revival', 2],
    ],
    extra: [
      ['Stardust Dragon', 2],
      ['Junk Warrior', 2],
      ['Formula Synchron', 2],
      ['Shooting Star Dragon', 1],
      ['Junk Archer', 1],
      ['Junk Destroyer', 1],
      ['Nitro Warrior', 1],
      ['Turbo Warrior', 1],
      ['Drill Warrior', 1],
      ['Junk Berserker', 1],
      ['Armory Arm', 1],
    ],
  },
  {
    id: 'yusei-fudo_deck_2',
    characterId: 'yusei-fudo',
    name: 'Majestic Star Acceleration',
    archetype: 'Majestic / Stardust Synchro',
    description: "Yusei's cosmic dragon deck channeling Majestic Dragon and Stardust Xiaolong to unleash the miraculous power of Majestic Star Dragon.",
    signatureCards: ['Majestic Star Dragon', 'Shooting Star Dragon', 'Stardust Dragon'],
    main: [
      ['Majestic Dragon', 2],
      ['Stardust Xiaolong', 2],
      ['Junk Synchron', 3],
      ['Debris Dragon', 2],
      ['Turbo Synchron', 2],
      ['Nitro Synchron', 2],
      ['Bri Synchron', 1],
      ['Hyper Synchron', 1],
      ['Quillbolt Hedgehog', 2],
      ['Card Ejector', 1],
      ['Effect Veiler', 2],
      ['Level Eater', 2],
      ['Tuning', 3],
      ['Cards of Consonance', 2],
      ['Pot of Avarice', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Mystical Space Typhoon', 2],
      ['One for One', 1],
      ['Scrap-Iron Scarecrow', 2],
      ['Starlight Road', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 1],
    ],
    extra: [
      ['Majestic Star Dragon', 2],
      ['Shooting Star Dragon', 1],
      ['Stardust Dragon', 2],
      ['Formula Synchron', 2],
      ['Junk Warrior', 2],
      ['Nitro Warrior', 1],
      ['Turbo Warrior', 1],
      ['Armory Arm', 1],
    ],
  },

  // ===========================================================================
  // 2. Jack Atlas
  // ===========================================================================
  {
    id: 'jack-atlas_deck_1',
    characterId: 'jack-atlas',
    name: 'Red Dragon Resonator King',
    archetype: 'Red Dragon Archfiend / Resonator',
    description: "The King's supreme power deck commanding Dark, Flare, and Creation Resonators alongside Vice Dragon to summon Red Dragon Archfiend and double-tune into Red Nova Dragon.",
    signatureCards: ['Red Dragon Archfiend', 'Red Nova Dragon', 'Dark Resonator'],
    main: [
      ['Dark Resonator', 3],
      ['Flare Resonator', 3],
      ['Creation Resonator', 3],
      ['Force Resonator', 2],
      ['Clock Resonator', 2],
      ['Barrier Resonator', 2],
      ['Vice Dragon', 3],
      ['Battle Fader', 3],
      ['Mad Archfiend', 3],
      ['Twin-Shield Defender', 2],
      ['Strong Wind Dragon', 2],
      ['Power Breaker', 2],
      ['Scarlet Security', 2],
      ['Resonator Engine', 2],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Crimson Fire', 2],
      ['Mirror Force', 1],
      ['Call of the Haunted', 1],
    ],
    extra: [
      ['Red Dragon Archfiend', 3],
      ['Red Nova Dragon', 2],
      ['Exploder Dragonwing', 2],
      ['Chaos King Archfiend', 2],
    ],
  },

  // ===========================================================================
  // 3. Crow Hogan
  // ===========================================================================
  {
    id: 'crow-hogan_deck_1',
    characterId: 'crow-hogan',
    name: 'Blackwing Whirlwind Assault',
    archetype: 'Blackwing / Synchro Swarm',
    description: "Crow Hogan's lightning-fast Blackwing deck swarming the field with Bora, Shura, Gale, and Kalut under Black Whirlwind to summon Blackwing Armor Master.",
    signatureCards: ['Blackwing Armor Master', 'Blackwing - Gale the Whirlwind', 'Black Whirlwind'],
    main: [
      ['Blackwing - Bora the Spear', 3],
      ['Blackwing - Shura the Blue Flame', 3],
      ['Blackwing - Kalut the Moon Shadow', 3],
      ['Blackwing - Blizzard the Far North', 3],
      ['Blackwing - Sirocco the Dawn', 2],
      ['Blackwing - Gale the Whirlwind', 1],
      ['Blackwing - Breeze the Zephyr', 2],
      ['Blackwing - Vayu the Emblem of Honor', 2],
      ['Blackwing - Zephyros the Elite', 1],
      ['Dark Armed Dragon', 1],
      ['Black Whirlwind', 3],
      ['Against the Wind', 2],
      ['Cards for Black Feathers', 2],
      ['Allure of Darkness', 2],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Icarus Attack', 3],
      ['Delta Crow - Anti Reverse', 2],
      ['Black Return', 2],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Blackwing Armor Master', 3],
      ['Blackwing Armed Wing', 3],
      ['Black-Winged Dragon', 2],
      ['Blackwing - Silverwind the Ascendant', 2],
    ],
  },

  // ===========================================================================
  // 4. Akiza Izinski
  // ===========================================================================
  {
    id: 'akiza-izinski_deck_1',
    characterId: 'akiza-izinski',
    name: 'Black Rose Botanical Destruction',
    archetype: 'Plant / Black Rose Synchro',
    description: "The Black Rose's fearsome botanical deck manipulating Rose Tokens with Black Garden and tuning Twilight Rose Knight to wipe the field with Black Rose Dragon.",
    signatureCards: ['Black Rose Dragon', 'Splendid Rose', 'Black Garden'],
    main: [
      ['Botanical Lion', 3],
      ['Lord Poison', 3],
      ['Twilight Rose Knight', 3],
      ['Blue Rose Dragon', 3],
      ['Gigaplant', 2],
      ['Lonefire Blossom', 2],
      ['Tytannial, Princess of Camellias', 2],
      ['Copy Plant', 2],
      ['Spore', 1],
      ['Dandylion', 1],
      ['Phoenixian Cluster Amaryllis', 1],
      ['Naturia Cherries', 2],
      ['Black Garden', 3],
      ['Mark of the Rose', 2],
      ['Super Solar Nutrient', 2],
      ['Miracle Fertilizer', 2],
      ['Seed of Deception', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Wall of Thorns', 2],
      ['Blossom Bombardment', 1],
    ],
    extra: [
      ['Black Rose Dragon', 3],
      ['Splendid Rose', 2],
      ['Queen of Thorns', 2],
    ],
  },

  // ===========================================================================
  // 5. Leo
  // ===========================================================================
  {
    id: 'leo_deck_1',
    characterId: 'leo',
    name: 'Morphtronic Power Tool Assembly',
    archetype: 'Morphtronic / Equip Synchro',
    description: "Leo's inventive household appliance deck morphing between attack and defense modes to search Equip Spells with Power Tool Dragon and evolve into Life Stream Dragon.",
    signatureCards: ['Power Tool Dragon', 'Morphtronic Celfon', 'Double Tool C&D'],
    main: [
      ['Morphtronic Celfon', 3],
      ['Morphtronic Radion', 3],
      ['Morphtronic Boomboxen', 3],
      ['Morphtronic Scopen', 3],
      ['Morphtronic Remoten', 3],
      ['Morphtronic Magnen', 2],
      ['Morphtronic Lantron', 2],
      ['Morphtronic Datatron', 2],
      ['Morphtronic Videon', 2],
      ['Morphtronic Repair Unit', 3],
      ['Morphtronic Accelerator', 3],
      ['Morphtronic Map', 2],
      ['Double Tool C&D', 3],
      ['Mage Power', 1],
      ['United We Stand', 1],
      ['Monster Reborn', 1],
      ['Morphtransition', 1],
      ['Morphtronic Monitron', 1],
      ['Morphtronic Forcefield', 1],
    ],
    extra: [
      ['Power Tool Dragon', 3],
      ['Life Stream Dragon', 2],
      ['Formula Synchron', 2],
    ],
  },

  // ===========================================================================
  // 6. Luna
  // ===========================================================================
  {
    id: 'luna_deck_1',
    characterId: 'luna',
    name: 'Ancient Fairy Forest Sanctuary',
    archetype: 'Fairy / Forest Sanctuary',
    description: "Luna's gentle spirit deck protecting Life Points with Kuribon and Spirit Barrier while utilizing Ancient Forest to bring forth Ancient Fairy Dragon.",
    signatureCards: ['Ancient Fairy Dragon', 'Kuribon', 'Ancient Forest'],
    main: [
      ['Kuribon', 3],
      ['Regulus', 3],
      ['Sunlight Unicorn', 3],
      ['Sunny Pixie', 3],
      ['Spore', 1],
      ['Nettles', 2],
      ['Fairy Archer', 2],
      ['Watapon', 2],
      ['Spirit of the Breeze', 2],
      ['Golden Flying Fish', 1],
      ['Ancient Forest', 3],
      ['The Sanctuary in the Sky', 2],
      ['Terraforming', 1],
      ['Horn of the Unicorn', 2],
      ['Fairy Wind', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Spirit Barrier', 3],
      ['Pixie Ring', 1],
      ['Damage Condenser', 1],
      ['Wall of Revealing Light', 1],
    ],
    extra: [
      ['Ancient Fairy Dragon', 3],
      ['Stardust Dragon', 1],
    ],
  },

  // ===========================================================================
  // 7. Kalin Kessler
  // ===========================================================================
  {
    id: 'kalin-kessler_deck_1',
    characterId: 'kalin-kessler',
    name: 'Infernity Handless Doom',
    archetype: 'Infernity / Dark Synchro',
    description: "Kalin Kessler's devastating 'Handless Combo' deck activating unstoppable effects when holding zero cards in hand to loop Infernity Archfiend into Infernity Doom Dragon.",
    signatureCards: ['Infernity Doom Dragon', 'Infernity Archfiend', 'Hundred Eyes Dragon'],
    main: [
      ['Infernity Archfiend', 3],
      ['Infernity Necromancer', 3],
      ['Infernity Mirage', 3],
      ['Infernity Beetle', 3],
      ['Infernity Avenger', 3],
      ['Infernity Guardian', 2],
      ['Infernity Beast', 2],
      ['Infernity Destroyer', 2],
      ['Infernity Launcher', 2],
      ['ZERO-MAX', 2],
      ['Foolish Burial', 1],
      ['One for One', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Infernity Inferno', 3],
      ['Infernity Barrier', 3],
      ['Infernity Break', 3],
      ['Infernity Force', 1],
      ['Torrential Tribute', 1],
    ],
    extra: [
      ['Infernity Doom Dragon', 3],
      ['Hundred Eyes Dragon', 3],
    ],
  },

  // ===========================================================================
  // 8. Antinomy
  // ===========================================================================
  {
    id: 'antinomy_deck_1',
    characterId: 'antinomy',
    name: 'T.G. Accel Synchro Mechanics',
    archetype: 'Tech Genus / Accel Synchro',
    description: "Antinomy's futuristic scientific deck replacing destroyed Tech Genus monsters to perform Top Clear Mind and Delta Accel Synchro Summon T.G. Halberd Cannon.",
    signatureCards: ['T.G. Halberd Cannon', 'T.G. Blade Blaster', 'T.G. Hyper Librarian'],
    main: [
      ['T.G. Rush Rhino', 3],
      ['T.G. Warwolf', 3],
      ['T.G. Striker', 3],
      ['T.G. Cyber Magician', 3],
      ['T.G. Catapult Dragon', 3],
      ['T.G. Jet Falcon', 2],
      ['TGX1-HL', 3],
      ['TGX300', 2],
      ['TGX3-DX2', 2],
      ['Pot of Avarice', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Mystical Space Typhoon', 2],
      ['TG1-EM1', 3],
      ['TG-SX1', 2],
      ['Solemn Judgment', 1],
      ['Mirror Force', 1],
      ['Call of the Haunted', 2],
      ['Bottomless Trap Hole', 2],
    ],
    extra: [
      ['T.G. Halberd Cannon', 2],
      ['T.G. Blade Blaster', 2],
      ['T.G. Wonder Magician', 3],
      ['T.G. Hyper Librarian', 3],
      ['T.G. Recipro Dragonfly', 2],
      ['T.G. Power Gladiator', 2],
    ],
  },

  // ===========================================================================
  // 9. Sherry LeBlanc
  // ===========================================================================
  {
    id: 'sherry-leblanc_deck_1',
    characterId: 'sherry-leblanc',
    name: 'Fleur Floral Chivalry',
    archetype: 'Fleur / Noble Warrior',
    description: "Sherry LeBlanc's noble French cavalry deck synchronizing Fleur Synchron and Sorciere de Fleur into Chevalier de Fleur and Baronne de Fleur.",
    signatureCards: ['Chevalier de Fleur', 'Baronne de Fleur', 'Fleur Synchron'],
    main: [
      ['Fleur Synchron', 3],
      ['Sorciere de Fleur', 2],
      ['Necro Fleur', 3],
      ['D.D. Warrior Lady', 2],
      ['Freed the Brave Wanderer', 2],
      ['Honest', 2],
      ['Soul of Purity and Light', 2],
      ['Darklord Marie', 2],
      ['The Forgiving Maiden', 2],
      ['Polymerization', 2],
      ['Future Fusion', 1],
      ['Burial from a Different Dimension', 1],
      ['D.D.R. - Different Dimension Reincarnation', 2],
      ['Reinforcement of the Army', 1],
      ['The Warrior Returning Alive', 2],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Liberty at Last!', 3],
      ['Z-ONE', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 2],
    ],
    extra: [
      ['Chevalier de Fleur', 3],
      ['Baronne de Fleur', 2],
      ['St. Joan', 2],
    ],
  },

  // ===========================================================================
  // 10. Zone
  // ===========================================================================
  {
    id: 'zone_deck_1',
    characterId: 'zone',
    name: 'Timelord Celestial Judgment',
    archetype: 'Timelord / High Fairy',
    description: "The leader of Yliaster's apocalyptic deck wielding the indestructible avatars Metaion and Sandaion to manifest the godlike power of Sephylon, the Ultimate Timelord.",
    signatureCards: ['Sephylon, the Ultimate Timelord', 'Metaion, the Timelord', 'Sandaion, the Timelord'],
    main: [
      ['Sephylon, the Ultimate Timelord', 2],
      ['Sandaion, the Timelord', 3],
      ['Metaion, the Timelord', 3],
      ['Master Hyperion', 3],
      ['Archlord Kristya', 2],
      ['Athena', 2],
      ['Tethys, Goddess of Light', 2],
      ['Hecatrice', 3],
      ['Splendid Venus', 2],
      ['Valhalla, Hall of the Fallen', 3],
      ['Celestial Transformation', 3],
      ['Cards from the Sky', 2],
      ['Trade-In', 3],
      ['Terraforming', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Z-ONE', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
    ],
    extra: [],
  },

  // ===========================================================================
  // 11. Carly Carmine
  // ===========================================================================
  {
    id: 'carly-carmine_deck_1',
    characterId: 'carly-carmine',
    name: 'Fortune Lady Divination',
    archetype: 'Fortune Lady / Spellcaster',
    description: "Carly Carmine's astrological deck whose Fortune Ladies grow stronger with every Standby Phase, drawing cards with Fortune Lady Water and banishing threats with Fortune's Future.",
    signatureCards: ['Fortune Lady Light', 'Fortune Lady Dark', "Fortune's Future"],
    main: [
      ['Fortune Lady Light', 3],
      ['Fortune Lady Dark', 3],
      ['Fortune Lady Fire', 3],
      ['Fortune Lady Water', 3],
      ['Fortune Lady Wind', 2],
      ['Fortune Lady Earth', 2],
      ['Solitaire Magician', 2],
      ['Cat\'s Ear Tribe', 2],
      ["Fortune's Future", 3],
      ['Time Passage', 3],
      ['Magical Dimension', 2],
      ['One for One', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Bending Destiny', 3],
      ['Inherited Fortune', 2],
      ['Slip of Fortune', 2],
      ['Compulsory Evacuation Device', 2],
    ],
    extra: [
      ['Arcanite Magician', 2],
    ],
  },

  // ===========================================================================
  // 12. Rex Goodwin
  // ===========================================================================
  {
    id: 'rex-goodwin_deck_1',
    characterId: 'rex-goodwin',
    name: 'Inca Eclipse - Sun & Moon Dragons',
    archetype: 'Inca / Dual Synchro',
    description: "Rex Goodwin's high-priest deck orchestrating the endless cycle of day and night by synchronizing Sun Dragon Inti and Moon Dragon Quilla.",
    signatureCards: ['Sun Dragon Inti', 'Moon Dragon Quilla', 'Oracle of the Sun'],
    main: [
      ['Oracle of the Sun', 3],
      ['Fire Ant Ascator', 3],
      ['Supay', 3],
      ['Apocatequil', 3],
      ['Weeping Idol', 3],
      ['Earthbound Immortal Wiraqocha Rasca', 1],
      ['Cyber Dragon', 2],
      ['Temple of the Sun', 3],
      ['Destruct Potion', 3],
      ['Call of the Reaper', 3],
      ['Pot of Avarice', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Terraforming', 1],
      ['Mystical Space Typhoon', 2],
      ['Limit Reverse', 3],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 2],
    ],
    extra: [
      ['Sun Dragon Inti', 3],
      ['Moon Dragon Quilla', 3],
    ],
  },

  // ===========================================================================
  // 13. Roman Goodwin
  // ===========================================================================
  {
    id: 'roman-goodwin_deck_1',
    characterId: 'roman-goodwin',
    name: 'Dark Spider Underground Web',
    archetype: 'Spider / Dark Synchro',
    description: "The leader of the Dark Signers' web of entrapment shifting opposing monsters into defense position to summon Underground Arachnid and Earthbound Immortal Uru.",
    signatureCards: ['Underground Arachnid', 'Earthbound Immortal Uru', 'Mother Spider'],
    main: [
      ['Earthbound Immortal Uru', 2],
      ['Mother Spider', 3],
      ['Spyder Spider', 3],
      ['Dark Spider', 3],
      ['Ground Spider', 3],
      ['Relinquished Spider', 3],
      ['Informer Spider', 2],
      ['Spider Web', 3],
      ["Spiders' Lair", 3],
      ['Verdant Sanctuary', 2],
      ['Terraforming', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Spider Egg', 3],
      ['Lair Wire', 3],
      ['Mirror Force', 1],
      ['Call of the Haunted', 2],
      ['Solemn Judgment', 1],
    ],
    extra: [
      ['Underground Arachnid', 3],
    ],
  },

  // ===========================================================================
  // 14. Misty Tredwell
  // ===========================================================================
  {
    id: 'misty-tredwell_deck_1',
    characterId: 'misty-tredwell',
    name: "Reptilianne Gorgon's Gaze",
    archetype: 'Reptilianne / Reptile Control',
    description: "Misty Tredwell's petrifying reptile deck reducing enemy monster ATK to 0 to steal them with Reptilianne Viper or tribute them for Reptilianne Vaskii.",
    signatureCards: ['Reptilianne Vaskii', 'Reptilianne Medusa', 'Reptilianne Hydra'],
    main: [
      ['Reptilianne Vaskii', 2],
      ['Reptilianne Medusa', 2],
      ['Reptilianne Gorgon', 3],
      ['Reptilianne Viper', 3],
      ['Reptilianne Scylla', 3],
      ['Reptilianne Gardna', 3],
      ['Earthbound Immortal Ccarayhua', 1],
      ['Evil Dragon Ananta', 2],
      ['Reptilianne Spawn', 3],
      ['Reptilianne Poison', 3],
      ['Molting Escape', 3],
      ['Snake Whistle', 3],
      ["Viper's Rebirth", 2],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Offering to the Snake Deity', 3],
      ['Damage = Reptile', 2],
    ],
    extra: [
      ['Reptilianne Hydra', 3],
    ],
  },

  // ===========================================================================
  // 15. Greiger
  // ===========================================================================
  {
    id: 'greiger_deck_1',
    characterId: 'greiger',
    name: 'Reactor Flying Fortress SKY FIRE',
    archetype: 'Reactor / Machine Burn',
    description: "Greiger's heavy artillery deck combining Summon, Spell, and Trap Reactors to bombard opponent activations and send Flying Fortress SKY FIRE onto the field.",
    signatureCards: ['Flying Fortress SKY FIRE', 'Dark Strike Fighter', 'Earthbound Immortal Chacu Challhua'],
    main: [
      ['Flying Fortress SKY FIRE', 2],
      ['Summon Reactor ・SK', 3],
      ['Spell Reactor ・RE', 3],
      ['Trap Reactor ・Y FI', 3],
      ['Earthbound Immortal Chacu Challhua', 1],
      ['Black Salvo', 3],
      ['Cyber Dragon', 2],
      ['Dekoichi the Battlechanted Locomotive', 3],
      ['Heavy Mech Support Platform', 2],
      ['Limiter Removal', 1],
      ['Heavy Storm', 1],
      ['Dark Hole', 1],
      ['Monster Reborn', 1],
      ['Pot of Avarice', 1],
      ['Mystical Space Typhoon', 2],
      ['Fake Explosion', 3],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Torrential Tribute', 1],
      ['Bottomless Trap Hole', 2],
      ['Call of the Haunted', 2],
      ['Threatening Roar', 1],
    ],
    extra: [
      ['Dark Strike Fighter', 3],
    ],
  },

  // ===========================================================================
  // 16. Aporia
  // ===========================================================================
  {
    id: 'aporia_deck_1',
    characterId: 'aporia',
    name: 'Meklord Astro & Emperors',
    archetype: 'Meklord / Anti-Synchro Machine',
    description: "Aporia's ultimate embodiment of despair absorbing opposing Synchro Monsters using Meklord Emperors Wisel, Granel, and Skiel to summon Meklord Astro Mekanikle.",
    signatureCards: ['Meklord Astro Mekanikle', 'Meklord Emperor Wisel', 'Fortissimo the Mobile Fortress'],
    main: [
      ['Meklord Astro Mekanikle', 2],
      ['Meklord Astro Dragon Asterisk', 1],
      ['Meklord Emperor Wisel', 2],
      ['Meklord Emperor Granel', 2],
      ['Meklord Emperor Skiel', 2],
      ['Meklord Army of Wisel', 3],
      ['Meklord Army of Granel', 3],
      ['Meklord Army of Skiel', 3],
      ['Cyber Dragon', 2],
      ['Fortissimo the Mobile Fortress', 3],
      ['Meklord Fortress', 2],
      ['Boon of the Meklord Emperor', 3],
      ['Limiter Removal', 1],
      ['Dark Hole', 1],
      ['Monster Reborn', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Mektimed Blast', 2],
      ['Chaos Infinity', 2],
      ['Torrential Tribute', 1],
      ['Mirror Force', 1],
    ],
    extra: [],
  },

  // ===========================================================================
  // 17. Paradox
  // ===========================================================================
  {
    id: 'paradox_deck_1',
    characterId: 'paradox',
    name: 'Malefic Paradox Sin Dragons',
    archetype: 'Malefic / Field Beatdown',
    description: "The time-traveling Paradox's corrupting deck sending legendary dragons from the Extra and Main Decks to summon massive 4000 ATK Malefic beasts under Malefic World.",
    signatureCards: ['Malefic Cyber End Dragon', 'Malefic Rainbow Dragon', 'Malefic Stardust Dragon'],
    main: [
      ['Malefic Cyber End Dragon', 3],
      ['Malefic Rainbow Dragon', 3],
      ['Malefic Stardust Dragon', 3],
      ['Malefic Blue-Eyes White Dragon', 3],
      ['Malefic Red-Eyes Black Dragon', 2],
      ['Malefic Parallel Gear', 3],
      ['Rainbow Dragon', 2],
      ['Blue-Eyes White Dragon', 2],
      ['Red-Eyes Black Dragon', 2],
      ['Malefic World', 3],
      ['Terraforming', 2],
      ['Malefic Claw Stream', 3],
      ['Trade-In', 2],
      ['Allure of Darkness', 2],
      ['Pot of Duality', 2],
      ['Skill Drain', 2],
      ['Solemn Judgment', 1],
    ],
    extra: [
      ['Malefic Paradox Dragon', 3],
      ['Cyber End Dragon', 3],
      ['Stardust Dragon', 3],
    ],
  },

  // ===========================================================================
  // 18. Tetsu Trudge
  // ===========================================================================
  {
    id: 'tetsu-trudge_deck_1',
    characterId: 'tetsu-trudge',
    name: 'Security Police & Goyo Beatdown',
    archetype: 'Security Police / Synchro',
    description: "Sector Security Officer Trudge's pursuit deck locking down criminal duelists with Jutte Fighter, Torapart, and the commanding authority of Goyo Guardian.",
    signatureCards: ['Goyo Guardian', 'Montage Dragon', 'Jutte Fighter'],
    main: [
      ['Montage Dragon', 2],
      ['Handcuffs Dragon', 2],
      ['Jutte Fighter', 3],
      ['Torapart', 3],
      ['Search Striker', 3],
      ['Pursuit Chaser', 2],
      ['Samurai Sword Baron', 2],
      ['Stygian Street Patrol', 3],
      ['Stygian Security', 3],
      ['Tactical Espionage Expert', 2],
      ['Reinforcement of the Army', 1],
      ['The Warrior Returning Alive', 2],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Swords of Revealing Light', 1],
      ['Mystical Space Typhoon', 2],
      ['Broken Blocker', 2],
      ['Security Orb', 2],
      ['Wiretap', 2],
      ['Call of the Haunted', 1],
    ],
    extra: [
      ['Goyo Guardian', 3],
      ['Stygian Sergeants', 2],
      ['Colossal Fighter', 2],
    ],
  },

  // ===========================================================================
  // 19. Sayer
  // ===========================================================================
  {
    id: 'sayer_deck_1',
    characterId: 'sayer',
    name: 'Arcadia Psychic Transcendence',
    archetype: 'Psychic / Synchro',
    description: "The Arcadia Movement leader's psychic assault deck paying Life Points to trigger mental supremacy and summon Thought Ruler Archfiend and Hyper Psychic Blaster.",
    signatureCards: ['Thought Ruler Archfiend', 'Hyper Psychic Blaster', 'Emergency Teleport'],
    main: [
      ['Krebons', 3],
      ['Psychic Commander', 3],
      ['Silent Psychic Wizard', 3],
      ['Mind Master', 1],
      ['Telekinetic Shocker', 2],
      ['Destructotron', 2],
      ['Pandaborg', 2],
      ['Psychic Jumper', 2],
      ['Emergency Teleport', 2],
      ['Brain Research Lab', 3],
      ['Psychic Path', 2],
      ['Telekinetic Power Well', 2],
      ['Terraforming', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Mind Over Matter', 3],
      ['Psychic Overload', 2],
      ['Psychic Rejuvenation', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Torrential Tribute', 1],
    ],
    extra: [
      ['Thought Ruler Archfiend', 2],
      ['Hyper Psychic Blaster', 2],
      ['Magical Android', 2],
      ['Psychic Lifetrancer', 2],
    ],
  },

  // ===========================================================================
  // 20. Halldor
  // ===========================================================================
  {
    id: 'halldor_deck_1',
    characterId: 'halldor',
    name: 'Nordic Gods Aesir Descent',
    archetype: 'Nordic / Aesir Synchro',
    description: "Team Ragnarok's captain's deck uniting the Nordic Ascendant, Nordic Beasts, and Nordic Alfar to summon the all-powerful Norse gods Odin, Thor, and Loki.",
    signatureCards: ['Odin, Father of the Aesir', 'Thor, Lord of the Aesir', 'Loki, Lord of the Aesir'],
    main: [
      ['Vanadis of the Nordic Ascendant', 3],
      ['Valkyrie of the Nordic Ascendant', 3],
      ['Mimir of the Nordic Ascendant', 2],
      ['Tanngrisnir of the Nordic Beasts', 3],
      ['Tanngnjostr of the Nordic Beasts', 3],
      ['Guldfaxe of the Nordic Beasts', 2],
      ['Garmr of the Nordic Beasts', 2],
      ['Ljosalf of the Nordic Alfar', 2],
      ['Svartalf of the Nordic Alfar', 2],
      ['The Nordic Lights', 2],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Pot of Avarice', 1],
      ['Mystical Space Typhoon', 2],
      ['Nordic Relic Gungnir', 2],
      ['Nordic Relic Brisingamen', 2],
      ['Nordic Relic Draupnir', 2],
      ['Nordic Relic Laevateinn', 1],
      ['Gleipnir, the Fetters of Fenrir', 2],
      ['Solemn Authority', 1],
      ['Solemn Judgment', 1],
    ],
    extra: [
      ['Odin, Father of the Aesir', 2],
      ['Thor, Lord of the Aesir', 2],
      ['Loki, Lord of the Aesir', 2],
    ],
  },

  // 19. Crow Hogan - Blackwing Vayu Turbo & Black-Winged Dragon
  {
    id: 'crow-hogan_deck_2',
    characterId: 'crow-hogan',
    name: 'Blackwing Vayu Turbo & Black-Winged Dragon',
    archetype: 'Blackwing / Vayu GY Synchro',
    description: "Crow's premier tournament-grade graveyard strategy banishing Vayu and high-level Blackwings from the GY to summon Silverwind and shielding with Black-Winged Dragon.",
    signatureCards: ['Blackwing - Vayu the Emblem of Honor', 'Black-Winged Dragon', 'Blackwing - Silverwind the Ascendant'],
    main: [
      ['Blackwing - Vayu the Emblem of Honor', 3],
      ['Blackwing - Sirocco the Dawn', 3],
      ['Blackwing - Elphin the Raven', 2],
      ['Blackwing - Bora the Spear', 3],
      ['Blackwing - Shura the Blue Flame', 3],
      ['Blackwing - Kalut the Moon Shadow', 3],
      ['Blackwing - Gale the Whirlwind', 1],
      ['Blackwing - Blizzard the Far North', 2],
      ['Dark Grepher', 2],
      ['Armageddon Knight', 2],
      ['Burial from a Different Dimension', 1],
      ['Allure of Darkness', 2],
      ['Black Whirlwind', 3],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Dark Hole', 1],
      ['Icarus Attack', 3],
      ['Delta Crow - Anti Reverse', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 2],
    ],
    extra: [
      ['Black-Winged Dragon', 2],
      ['Blackwing - Silverwind the Ascendant', 2],
      ['Blackwing Armor Master', 3],
      ['Blackwing Armed Wing', 3],
    ],
  },

  // 20. Kalin Kessler - Dark Signer Ccapac Apu & Hundred Eyes
  {
    id: 'kalin-kessler_deck_2',
    characterId: 'kalin-kessler',
    name: 'Dark Signer Ccapac Apu & Hundred Eyes',
    archetype: 'Infernity / Dark Signer Giant',
    description: "Kalin's terrifying Dark Signer deck unleashing Earthbound Immortal Ccapac Apu for 3000 direct damage and Hundred Eyes Dragon copying fallen Infernity effects.",
    signatureCards: ['Earthbound Immortal Ccapac Apu', 'Hundred Eyes Dragon', 'Infernity Archfiend'],
    main: [
      ['Earthbound Immortal Ccapac Apu', 2],
      ['Infernity Archfiend', 3],
      ['Infernity Necromancer', 3],
      ['Infernity Guardian', 3],
      ['Infernity Beast', 2],
      ['Infernity Destroyer', 2],
      ['Infernity Dwarf', 2],
      ['Infernity Mirage', 3],
      ['Infernity Beetle', 3],
      ['Infernity Launcher', 2],
      ['ZERO-MAX', 2],
      ['Foolish Burial', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Infernity Inferno', 3],
      ['Infernity Barrier', 3],
      ['Infernity Break', 3],
      ['Call of the Earthbound', 2],
      ['Roar of the Earthbound Immortal', 1],
    ],
    extra: [
      ['Hundred Eyes Dragon', 3],
      ['Infernity Doom Dragon', 2],
    ],
  },

  // 21. Greiger - Dark Signer Chacu Challhua Whale
  {
    id: 'greiger_deck_2',
    characterId: 'greiger',
    name: 'Dark Signer Chacu Challhua Whale',
    archetype: 'Dark Signer / Killer Whale Machine',
    description: "Greiger as a Dark Signer commanding Earthbound Immortal Chacu Challhua to attack from defense position and burn for half DEF, backed by Dark Strike Fighter.",
    signatureCards: ['Earthbound Immortal Chacu Challhua', 'Dark Strike Fighter', 'Black Salvo'],
    main: [
      ['Earthbound Immortal Chacu Challhua', 2],
      ['Black Salvo', 3],
      ['Dekoichi the Battlechanted Locomotive', 3],
      ['Cyber Dragon', 2],
      ['Heavy Mech Support Platform', 3],
      ['Mechanicalchaser', 3],
      ['Blast Sphere', 2],
      ['Limiter Removal', 1],
      ['Heavy Storm', 1],
      ['Dark Hole', 1],
      ['Monster Reborn', 1],
      ['Pot of Avarice', 1],
      ['Mystical Space Typhoon', 2],
      ['Call of the Earthbound', 2],
      ['Roar of the Earthbound Immortal', 2],
      ['Earthbound Immortal Revival', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Torrential Tribute', 1],
      ['Bottomless Trap Hole', 2],
      ['Threatening Roar', 2],
      ['Call of the Haunted', 2],
    ],
    extra: [
      ['Dark Strike Fighter', 3],
    ],
  },

  // 22. Rex Goodwin - Dark Signer Supreme God Wiraqocha Rasca
  {
    id: 'rex-goodwin_deck_2',
    characterId: 'rex-goodwin',
    name: 'Dark Signer Supreme God Wiraqocha Rasca',
    archetype: 'Inca / Supreme God Condor',
    description: "Rex Goodwin unleashing the 100th Dark Signer God Earthbound Immortal Wiraqocha Rasca to discard the opponent's hand and drop their Life Points directly to 1.",
    signatureCards: ['Earthbound Immortal Wiraqocha Rasca', 'Sun Dragon Inti', 'Moon Dragon Quilla'],
    main: [
      ['Earthbound Immortal Wiraqocha Rasca', 2],
      ['Oracle of the Sun', 3],
      ['Fire Ant Ascator', 3],
      ['Supay', 3],
      ['Apocatequil', 3],
      ['Weeping Idol', 3],
      ['Cyber Dragon', 2],
      ['Temple of the Sun', 3],
      ['Destruct Potion', 3],
      ['Call of the Reaper', 3],
      ['Pot of Avarice', 1],
      ['Monster Reborn', 1],
      ['Dark Hole', 1],
      ['Terraforming', 1],
      ['Mystical Space Typhoon', 2],
      ['Roar of the Earthbound Immortal', 2],
      ['Earthbound Immortal Revival', 2],
      ['Call of the Earthbound', 2],
      ['Limit Reverse', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
    ],
    extra: [
      ['Sun Dragon Inti', 3],
      ['Moon Dragon Quilla', 3],
    ],
  },
];

