import type { DeckDefinition } from './deckValidatorHelper.ts';

export const GX_AUTHENTIC_DECKS: DeckDefinition[] = [
  // ===========================================================================
  // 1. Jaden Yuki
  // ===========================================================================
  {
    id: 'jaden-yuki_deck_1',
    characterId: 'jaden-yuki',
    name: 'Classic Elemental HERO',
    archetype: 'Elemental HERO / Fusion',
    description: 'Jaden Yuki\'s iconic early Duel Academy deck uniting Avian, Burstinatrix, Clayman, and Sparkman to summon Flame Wingman and Shining Flare Wingman.',
    signatureCards: ['Elemental HERO Flame Wingman', 'Elemental HERO Shining Flare Wingman', 'Skyscraper'],
    main: [
      ['Elemental HERO Sparkman', 3],
      ['Elemental HERO Clayman', 3],
      ['Elemental HERO Burstinatrix', 2],
      ['Elemental HERO Avian', 2],
      ['Elemental HERO Bubbleman', 2],
      ['Elemental HERO Wildheart', 2],
      ['Elemental HERO Bladedge', 1],
      ['Winged Kuriboh', 2],
      ['Wroughtweiler', 2],
      ['King of the Swamp', 2],
      ['Polymerization', 3],
      ['Miracle Fusion', 2],
      ['Fusion Sage', 2],
      ['Fusion Recovery', 1],
      ['Skyscraper', 2],
      ['R - Righteous Justice', 1],
      ['E - Emergency Call', 2],
      ['Reinforcement of the Army', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Hero Signal', 2],
      ['A Hero Emerges', 2],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Elemental HERO Flame Wingman', 2],
      ['Elemental HERO Shining Flare Wingman', 2],
      ['Elemental HERO Thunder Giant', 2],
      ['Elemental HERO Rampart Blaster', 2],
      ['Elemental HERO Wildedge', 1],
      ['Elemental HERO Mariner', 1],
    ],
  },
  {
    id: 'jaden-yuki_deck_2',
    characterId: 'jaden-yuki',
    name: 'Neo-Spacian Contact Fusion',
    archetype: 'Elemental HERO / Neo-Spacian',
    description: 'Jaden\'s cosmic deck summoning Elemental HERO Neos and executing contact fusions with the six Neo-Spacians without Polymerization.',
    signatureCards: ['Elemental HERO Neos', 'Neo-Spacian Grand Mole', 'Neo Space'],
    main: [
      ['Elemental HERO Neos', 3],
      ['Neo-Spacian Grand Mole', 1],
      ['Neo-Spacian Flare Scarab', 2],
      ['Neo-Spacian Aqua Dolphin', 2],
      ['Neo-Spacian Air Hummingbird', 2],
      ['Neo-Spacian Dark Panther', 2],
      ['Neo-Spacian Glow Moss', 2],
      ['Cross Porter', 2],
      ['Elemental HERO Prisma', 2],
      ['Neo Space', 3],
      ['Fake Hero', 2],
      ['Convert Contact', 3],
      ['Contact Out', 2],
      ['Space Gift', 2],
      ['O - Oversoul', 2],
      ['E - Emergency Call', 2],
      ['Reinforcement of the Army', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Hero Signal', 2],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Elemental HERO Flare Neos', 2],
      ['Elemental HERO Aqua Neos', 2],
      ['Elemental HERO Grand Neos', 2],
      ['Elemental HERO Air Neos', 1],
      ['Elemental HERO Dark Neos', 2],
      ['Elemental HERO Glow Neos', 1],
      ['Elemental HERO Magma Neos', 1],
      ['Elemental HERO Storm Neos', 1],
    ],
  },
  {
    id: 'jaden-yuki_deck_3',
    characterId: 'jaden-yuki',
    name: 'Rainbow Neos & Supreme HERO',
    archetype: 'HERO / Rainbow Dragon / Super Poly',
    description: 'Jaden\'s Season 4 pinnacle deck uniting Elemental HERO Neos and Jesse\'s Rainbow Dragon with Super Polymerization and Miracle Contact.',
    signatureCards: ['Rainbow Neos', 'Elemental HERO Stratos', 'Super Polymerization'],
    main: [
      ['Elemental HERO Neos', 3],
      ['Rainbow Dragon', 2],
      ['Elemental HERO Stratos', 1],
      ['Elemental HERO Honest Neos', 2],
      ['Elemental HERO Prisma', 3],
      ['Elemental HERO Wildheart', 2],
      ['Honest', 2],
      ['King of the Swamp', 2],
      ['Polymerization', 2],
      ['Super Polymerization', 2],
      ['Miracle Contact', 3],
      ['Miracle Fusion', 2],
      ['E - Emergency Call', 3],
      ['A Hero Lives', 2],
      ['Reinforcement of the Army', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Call of the Haunted', 2],
      ['Hero Signal', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
    ],
    extra: [
      ['Rainbow Neos', 3],
      ['Elemental HERO The Shining', 2],
      ['Elemental HERO Absolute Zero', 2],
      ['Elemental HERO Gaia', 2],
      ['Elemental HERO Great Tornado', 2],
    ],
  },

  // ===========================================================================
  // 2. Zane Truesdale
  // ===========================================================================
  {
    id: 'zane-truesdale_deck_1',
    characterId: 'zane-truesdale',
    name: 'Cyber Dragon Power Bond',
    archetype: 'Cyber Dragon / Machine Fusion',
    description: 'The Kaiser\'s flawless academy deck combining Cyber Dragons with Power Bond to summon the 8000 ATK Cyber End Dragon.',
    signatureCards: ['Cyber Dragon', 'Cyber End Dragon', 'Power Bond'],
    main: [
      ['Cyber Dragon', 3],
      ['Proto-Cyber Dragon', 3],
      ['Cyber Valley', 3],
      ['Cyber Phoenix', 3],
      ['Cyber Kirin', 2],
      ['Cyber Eltanin', 1],
      ['Shining Angel', 3],
      ['Power Bond', 3],
      ['Overload Fusion', 2],
      ['Cyber Repair Plant', 3],
      ['Evolution Burst', 2],
      ['Limiter Removal', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Cyber Network', 2],
      ['Bottomless Trap Hole', 2],
      ['Call of the Haunted', 1],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Cyber End Dragon', 3],
      ['Cyber Twin Dragon', 3],
      ['Chimeratech Overdragon', 2],
      ['Chimeratech Fortress Dragon', 2],
    ],
  },
  {
    id: 'zane-truesdale_deck_2',
    characterId: 'zane-truesdale',
    name: 'Hell Kaiser Cyberdark Underworld',
    archetype: 'Cyberdark / Dragon Equip',
    description: 'Zane\'s ruthless underworld deck equipping high-level dragons to Cyberdark Horn, Edge, and Keel to forge the devastating Cyberdark Dragon.',
    signatureCards: ['Cyberdark Dragon', 'Cyberdark Horn', 'Cyberdark Impact!'],
    main: [
      ['Cyberdark Horn', 3],
      ['Cyberdark Edge', 3],
      ['Cyberdark Keel', 3],
      ['Infernal Dragon', 2],
      ['Hunter Dragon', 3],
      ['Exploder Dragon', 3],
      ['Twin-Headed Behemoth', 2],
      ['Masked Dragon', 3],
      ['Cyberdark Impact!', 2],
      ['Future Fusion', 1],
      ['Overload Fusion', 2],
      ['Dragon\'s Mirror', 2],
      ['Allure of Darkness', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Heavy Storm', 1],
      ['Crush Card Virus', 1],
      ['Call of the Haunted', 2],
      ['Bottomless Trap Hole', 2],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Cyberdark Dragon', 3],
      ['Five-Headed Dragon', 2],
    ],
  },

  // ===========================================================================
  // 3. Syrus Truesdale
  // ===========================================================================
  {
    id: 'syrus-truesdale_deck_1',
    characterId: 'syrus-truesdale',
    name: 'Vehicroid Assembly Connection',
    archetype: 'Vehicroid / Machine',
    description: 'Syrus Truesdale\'s brave machine deck uniting Ambulanceroid, Rescueroid, Gyroid, and Drillroid to construct Super Vehicroid Jumbo Drill.',
    signatureCards: ['Super Vehicroid Jumbo Drill', 'Submarineroid', 'Vehicroid Connection Zone'],
    main: [
      ['Submarineroid', 3],
      ['Drillroid', 3],
      ['Gyroid', 3],
      ['Steamroid', 3],
      ['Ambulanceroid', 2],
      ['Rescueroid', 2],
      ['Expressroid', 3],
      ['Decoyroid', 2],
      ['Armoroid', 1],
      ['Truckroid', 2],
      ['Vehicroid Connection Zone', 3],
      ['Megaroid City', 3],
      ['Polymerization', 2],
      ['Limiter Removal', 1],
      ['Shield Crush', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Supercharge', 3],
      ['Wonder Garage', 2],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Super Vehicroid Jumbo Drill', 3],
      ['Super Vehicroid - Stealth Union', 2],
      ['Steam Gyroid', 2],
      ['Ambulance Rescueroid', 2],
    ],
  },

  // ===========================================================================
  // 4. Chazz Princeton
  // ===========================================================================
  {
    id: 'chazz-princeton_deck_1',
    characterId: 'chazz-princeton',
    name: 'Armed Dragon & Ojama Trio',
    archetype: 'Armed Dragon / Ojama',
    description: 'Chazz Princeton\'s legendary deck combining the explosive destruction of Ojama Delta Hurricane!! with the level-evolving power of Armed Dragon LV10.',
    signatureCards: ['Armed Dragon LV10', 'Armed Dragon LV7', 'Ojama King'],
    main: [
      ['Armed Dragon LV3', 3],
      ['Armed Dragon LV5', 3],
      ['Armed Dragon LV7', 2],
      ['Armed Dragon LV10', 1],
      ['Ojama Yellow', 2],
      ['Ojama Green', 2],
      ['Ojama Black', 2],
      ['Ojama Blue', 3],
      ['Ojama Red', 2],
      ['Polymerization', 2],
      ['Ojama Delta Hurricane!!', 2],
      ['Ojamagic', 2],
      ['Ojamuscle', 1],
      ['Level Up!', 2],
      ['Level Modulation', 1],
      ['Magical Mallet', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Ojama Country', 3],
      ['Ojama Duo', 2],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Ojama King', 3],
      ['Ojama Knight', 3],
    ],
  },
  {
    id: 'chazz-princeton_deck_2',
    characterId: 'chazz-princeton',
    name: 'VWXYZ Catapult Cannon Union',
    archetype: 'VWXYZ / Machine Union',
    description: 'Chazz\'s elite North Academy machine union deck combining V-Tiger Jet, W-Wing Catapult, and XYZ-Dragon Cannon into VWXYZ-Dragon Catapult Cannon.',
    signatureCards: ['VWXYZ-Dragon Catapult Cannon', 'VW-Tiger Catapult', 'XYZ-Dragon Cannon'],
    main: [
      ['V-Tiger Jet', 3],
      ['W-Wing Catapult', 3],
      ['X-Head Cannon', 3],
      ['Y-Dragon Head', 3],
      ['Z-Metal Tank', 3],
      ['Heavy Mech Support Platform', 3],
      ['Frontline Base', 3],
      ['Roll Out!', 3],
      ['Limiter Removal', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Enemy Controller', 2],
      ['Bottomless Trap Hole', 2],
      ['Call of the Haunted', 2],
      ['Mirror Force', 1],
      ['Formation Union', 3],
    ],
    extra: [
      ['VWXYZ-Dragon Catapult Cannon', 3],
      ['VW-Tiger Catapult', 3],
      ['XYZ-Dragon Cannon', 2],
      ['XY-Dragon Cannon', 1],
      ['XZ-Tank Cannon', 1],
    ],
  },

  // ===========================================================================
  // 5. Alexis Rhodes
  // ===========================================================================
  {
    id: 'alexis-rhodes_deck_1',
    characterId: 'alexis-rhodes',
    name: 'Cyber Angel Ritual Grace',
    archetype: 'Cyber Angel / Fairy Ritual',
    description: 'The Queen of Obelisk Blue\'s pure ritual deck commanding Cyber Angel Benten, Idaten, and the supreme ritual executor Cyber Angel Dakini.',
    signatureCards: ['Cyber Angel Dakini', 'Cyber Angel Benten', 'Machine Angel Ritual'],
    main: [
      ['Cyber Angel Dakini', 2],
      ['Cyber Angel Benten', 3],
      ['Cyber Angel Idaten', 3],
      ['Cyber Petit Angel', 3],
      ['Sonic Bird', 3],
      ['Manju of the Ten Thousand Hands', 3],
      ['Senju of the Thousand Hands', 3],
      ['Machine Angel Ritual', 3],
      ['Fulfillment of the Contract', 2],
      ['Ritual Sanctuary', 3],
      ['Preparation of Rites', 2],
      ['Terraforming', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Ritual Weapon', 2],
      ['Waboku', 3],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
    ],
  },
  {
    id: 'alexis-rhodes_deck_2',
    characterId: 'alexis-rhodes',
    name: 'Cyber Girl Ballet Fusion',
    archetype: 'Cyber Girl / Warrior Fusion',
    description: 'Alexis\'s athletic combat deck fusing Blade Skater and Etoile Cyber into Cyber Blader to lock down opposing monsters, spells, and traps.',
    signatureCards: ['Cyber Blader', 'Blade Skater', 'Etoile Cyber'],
    main: [
      ['Blade Skater', 3],
      ['Etoile Cyber', 3],
      ['Cyber Tutu', 3],
      ['Cyber Prima', 2],
      ['Cyber Gymnast', 3],
      ['Warrior of Zera', 2],
      ['Command Knight', 2],
      ['Polymerization', 3],
      ['Fusion Sage', 2],
      ['Fusion Weapon', 2],
      ['Doble Passe', 2],
      ['Reinforcement of the Army', 1],
      ['The Warrior Returning Alive', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Waboku', 3],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
      ['Call of the Haunted', 2],
    ],
    extra: [
      ['Cyber Blader', 3],
    ],
  },

  // ===========================================================================
  // 6. Bastion Misawa
  // ===========================================================================
  {
    id: 'bastion-misawa_deck_1',
    characterId: 'bastion-misawa',
    name: 'Chemical Bonding & Water Dragon',
    archetype: 'Dinosaur / Water Dragon',
    description: 'Bastion Misawa\'s scientific deck combining 2 Hydrogeddon and 1 Oxygeddon via Bonding - H2O to summon the fire-quenching Water Dragon.',
    signatureCards: ['Water Dragon', 'Hydrogeddon', 'Bonding - H2O'],
    main: [
      ['Water Dragon', 2],
      ['Hydrogeddon', 3],
      ['Oxygeddon', 3],
      ['Carboneddon', 3],
      ['Hyozanryu', 2],
      ['Labyrinth Wall', 2],
      ['Giga Gagagigo', 2],
      ['Warrior of Atlantis', 3],
      ['Bonding - H2O', 3],
      ['A Legendary Ocean', 3],
      ['Fossil Dig', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Cursed Seal of the Forbidden Spell', 2],
      ['Seal of the Ancients', 2],
      ['Ring of Destruction', 1],
      ['Magic Cylinder', 1],
      ['Mirror Force', 1],
      ['Torrential Tribute', 1],
      ['Bottomless Trap Hole', 2],
    ],
  },

  // ===========================================================================
  // 7. Chumley Huffington
  // ===========================================================================
  {
    id: 'chumley-huffington_deck_1',
    characterId: 'chumley-huffington',
    name: 'Australian Beasts & Master of Oz',
    archetype: 'Beast / Fusion',
    description: 'Chumley\'s Australian wildlife deck fusing Big Koala and Des Kangaroo into the 4200 ATK behemoth Master of Oz with Ayers Rock Sunrise.',
    signatureCards: ['Master of Oz', 'Big Koala', 'Ayers Rock Sunrise'],
    main: [
      ['Big Koala', 3],
      ['Des Kangaroo', 3],
      ['Des Koala', 3],
      ['Gyaku-Gire Panda', 2],
      ['Sea Koala', 2],
      ['Tree Otter', 2],
      ['Giant Rat', 3],
      ['Nimble Momonga', 3],
      ['Polymerization', 3],
      ['Fusion Sage', 2],
      ['Ayers Rock Sunrise', 3],
      ['The Big March of Animals', 3],
      ['Gaia Power', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Destruction Punch', 2],
      ['Threatening Roar', 2],
      ['Mirror Force', 1],
    ],
    extra: [
      ['Master of Oz', 3],
    ],
  },

  // ===========================================================================
  // 8. Aster Phoenix
  // ===========================================================================
  {
    id: 'aster-phoenix_deck_1',
    characterId: 'aster-phoenix',
    name: 'Destiny HERO Clock Tower',
    archetype: 'Destiny HERO',
    description: 'Aster Phoenix\'s professional league deck counting down Clock Tower Prison to summon Dreadmaster, Dogma, and the supreme Destiny HERO - Plasma.',
    signatureCards: ['Destiny HERO - Plasma', 'Destiny HERO - Dreadmaster', 'Clock Tower Prison'],
    main: [
      ['Destiny HERO - Plasma', 2],
      ['Destiny HERO - Dogma', 2],
      ['Destiny HERO - Dreadmaster', 2],
      ['Destiny HERO - Malicious', 2],
      ['Destiny HERO - Dasher', 2],
      ['Destiny HERO - Diamond Dude', 3],
      ['Destiny HERO - Fear Monger', 3],
      ['Destiny HERO - Doom Lord', 3],
      ['Elemental HERO Stratos', 1],
      ['Clock Tower Prison', 3],
      ['Destiny Draw', 3],
      ['Allure of Darkness', 2],
      ['Reinforcement of the Army', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Heavy Storm', 1],
      ['D - Time', 2],
      ['D - Shield', 2],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
      ['Call of the Haunted', 2],
    ],
  },

  // ===========================================================================
  // 9. Jesse Anderson
  // ===========================================================================
  {
    id: 'jesse-anderson_deck_1',
    characterId: 'jesse-anderson',
    name: 'Crystal Beast Rainbow Dragon',
    archetype: 'Crystal Beast',
    description: 'Jesse Anderson\'s beloved deck gathering all 7 Crystal Beasts in the Spell & Trap Zone to awaken the incandescent Rainbow Dragon.',
    signatureCards: ['Rainbow Dragon', 'Crystal Beast Sapphire Pegasus', 'Crystal Abundance'],
    main: [
      ['Rainbow Dragon', 2],
      ['Crystal Beast Sapphire Pegasus', 3],
      ['Crystal Beast Topaz Tiger', 3],
      ['Crystal Beast Ruby Carbuncle', 2],
      ['Crystal Beast Amethyst Cat', 2],
      ['Crystal Beast Emerald Tortoise', 2],
      ['Crystal Beast Amber Mammoth', 2],
      ['Crystal Beast Cobalt Eagle', 2],
      ['Rare Value', 2],
      ['Crystal Promise', 3],
      ['Crystal Beacon', 3],
      ['Crystal Blessing', 2],
      ['Crystal Abundance', 2],
      ['Ancient City - Rainbow Ruins', 3],
      ['Terraforming', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Crystal Raigeki', 2],
      ['Crystal Tree', 2],
      ['Mirror Force', 1],
    ],
  },

  // ===========================================================================
  // 10. Dr. Vellian Crowler
  // ===========================================================================
  {
    id: 'vellian-crowler_deck_1',
    characterId: 'vellian-crowler',
    name: 'Ancient Gear Mechanical Dominion',
    archetype: 'Ancient Gear / Machine Beatdown',
    description: 'Duel Academy\'s Department Head unleashing un-negatable attacks with Ancient Gear Golem and fusing into Ultimate Ancient Gear Golem.',
    signatureCards: ['Ancient Gear Golem', 'Ultimate Ancient Gear Golem', 'Geartown'],
    main: [
      ['Ancient Gear Golem', 3],
      ['Ancient Gear Beast', 2],
      ['Ancient Gear Engineer', 2],
      ['Ancient Gear Knight', 3],
      ['Ancient Gear Soldier', 3],
      ['Ancient Gear Wyvern', 3],
      ['Geartown', 3],
      ['Ancient Gear Castle', 2],
      ['Ancient Gear Workshop', 2],
      ['Polymerization', 2],
      ['Limiter Removal', 1],
      ['Terraforming', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Ancient Gear Reborn', 2],
      ['Ancient Gear Drill', 2],
      ['Mirror Force', 1],
      ['Call of the Haunted', 2],
      ['Bottomless Trap Hole', 2],
    ],
    extra: [
      ['Ultimate Ancient Gear Golem', 3],
    ],
  },

  // ===========================================================================
  // 11. Atticus Rhodes
  // ===========================================================================
  {
    id: 'atticus-rhodes_deck_1',
    characterId: 'atticus-rhodes',
    name: 'Red-Eyes Darkness Metal Inferno',
    archetype: 'Red-Eyes / Dragon Swarm',
    description: 'Atticus Rhodes\'s blazing dragon deck unleashing Red-Eyes Darkness Metal Dragon and burning the opponent with Inferno Fire Blast.',
    signatureCards: ['Red-Eyes Darkness Metal Dragon', 'Red-Eyes Darkness Dragon', 'Inferno Fire Blast'],
    main: [
      ['Red-Eyes Black Dragon', 3],
      ['Red-Eyes Darkness Dragon', 2],
      ['Red-Eyes Darkness Metal Dragon', 2],
      ['Red-Eyes Wyvern', 3],
      ['Black Dragon\'s Chick', 2],
      ['Red-Eyes Retro Dragon', 2],
      ['Masked Dragon', 3],
      ['Mirage Dragon', 2],
      ['Inferno Fire Blast', 3],
      ['Cards of the Red Stone', 3],
      ['Dragon Shrine', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Heavy Storm', 1],
      ['Red-Eyes Spirit', 3],
      ['Return of the Red-Eyes', 2],
      ['Call of the Haunted', 2],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
    ],
  },

  // ===========================================================================
  // 12. Tyranno Hassleberry
  // ===========================================================================
  {
    id: 'tyranno-hassleberry_deck_1',
    characterId: 'tyranno-hassleberry',
    name: 'Ultimate Dinosaur Rampage',
    archetype: 'Dinosaur / Beatdown',
    description: 'Hassleberry\'s prehistoric dinosaur DNA deck attacking every opposing monster with Ultimate Tyranno and Super Conductor Tyranno.',
    signatureCards: ['Ultimate Tyranno', 'Super Conductor Tyranno', 'Jurassic World'],
    main: [
      ['Ultimate Tyranno', 2],
      ['Super Conductor Tyranno', 2],
      ['Black Tyranno', 2],
      ['Gilasaurus', 3],
      ['Babycerasaurus', 3],
      ['Hydrogeddon', 3],
      ['Hyper Hammerhead', 2],
      ['Giant Rex', 2],
      ['Jurassic World', 3],
      ['Fossil Dig', 3],
      ['Big Evolution Pill', 2],
      ['Tail Swipe', 3],
      ['Terraforming', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Survival Instinct', 2],
      ['Fossil Excavation', 2],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
    ],
  },

  // ===========================================================================
  // 13. Jim Crocodile Cook
  // ===========================================================================
  {
    id: 'jim-crocodile-cook_deck_1',
    characterId: 'jim-crocodile-cook',
    name: 'Prehistoric Fossil Fusion',
    archetype: 'Fossil / Rock Fusion',
    description: 'Jim Crocodile Cook\'s paleontologist deck banishing monsters from either player\'s graveyard to summon Fossil Dragon Skullgios.',
    signatureCards: ['Fossil Dragon Skullgios', 'Fossil Fusion', 'Fossil Dyna Pachycephalo'],
    main: [
      ['Fossil Dyna Pachycephalo', 3],
      ['Weathering Soldier', 3],
      ['Flint Cragger', 3],
      ['Shell Knight', 3],
      ['Gigantes', 2],
      ['Megarock Dragon', 1],
      ['Gaia Plate the Earth Giant', 1],
      ['Morphing Jar', 1],
      ['Fossil Fusion', 3],
      ['Time Stream', 2],
      ['Specimen Inspection', 2],
      ['Rock Bombardment', 3],
      ['Foolish Burial', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Call of the Haunted', 2],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
      ['Solemn Judgment', 2],
    ],
    extra: [
      ['Fossil Dragon Skullgios', 3],
      ['Fossil Dragon Skullgar', 3],
      ['Fossil Machine Skull Buggy', 3],
    ],
  },

  // ===========================================================================
  // 14. Axel Brodie
  // ===========================================================================
  {
    id: 'axel-brodie_deck_1',
    characterId: 'axel-brodie',
    name: 'Volcanic Blaze Accelerator',
    archetype: 'Volcanic / Pyro Burn',
    description: 'Axel Brodie\'s tactical military burn deck launching Volcanic Shell and Scattershot through Blaze Accelerator to summon Volcanic Doomfire.',
    signatureCards: ['Volcanic Doomfire', 'Volcanic Rocket', 'Tri-Blaze Accelerator'],
    main: [
      ['Volcanic Doomfire', 2],
      ['Volcanic Rocket', 3],
      ['Volcanic Scattershot', 3],
      ['Volcanic Shell', 3],
      ['Volcanic Blaster', 3],
      ['Volcanic Hammerer', 2],
      ['Royal Firestorm Guards', 3],
      ['Blaze Accelerator', 3],
      ['Tri-Blaze Accelerator', 2],
      ['Volcanic Blaze Accelerator', 1],
      ['Wild Fire', 3],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Volcanic Recharge', 2],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
      ['Call of the Haunted', 2],
    ],
  },

  // ===========================================================================
  // 15. Adrian Gecko
  // ===========================================================================
  {
    id: 'adrian-gecko_deck_1',
    characterId: 'adrian-gecko',
    name: 'Cloudian Eye of the Typhoon',
    archetype: 'Cloudian / Fog Counter',
    description: 'Adrian Gecko\'s indestructible battle cloud deck accumulating Fog Counters to unleash the devastating storm of Eye of the Typhoon.',
    signatureCards: ['Cloudian - Eye of the Typhoon', 'Cloudian - Nimbusman', 'The Sanctuary in the Sky'],
    main: [
      ['Cloudian - Eye of the Typhoon', 2],
      ['Cloudian - Nimbusman', 3],
      ['Cloudian - Acid Cloud', 3],
      ['Cloudian - Cirrostratus', 3],
      ['Cloudian - Altus', 2],
      ['Cloudian - Ghost Fog', 3],
      ['The Sanctuary in the Sky', 3],
      ['Diamond-Dust Cyclone', 2],
      ['Fog Control', 3],
      ['Summon Cloud', 2],
      ['Terraforming', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Spirit Barrier', 3],
      ['Rain Storm', 2],
      ['Mirror Force', 1],
      ['Call of the Haunted', 2],
      ['Bottomless Trap Hole', 2],
      ['Solemn Judgment', 1],
    ],
  },

  // ===========================================================================
  // 16. Sartorius Kumar
  // ===========================================================================
  {
    id: 'sartorius-kumar_deck_1',
    characterId: 'sartorius-kumar',
    name: 'Arcana Force Tarot of Fate',
    archetype: 'Arcana Force / Coin Toss',
    description: 'The Society of Light leader reading the tarot cards of destiny to freeze opponent turns with Arcana Force XXI - The World.',
    signatureCards: ['Arcana Force XXI - The World', 'Arcana Force EX - The Light Ruler', 'Light Barrier'],
    main: [
      ['Arcana Force XXI - The World', 2],
      ['Arcana Force EX - The Light Ruler', 2],
      ['Arcana Force 0 - The Fool', 3],
      ['Arcana Force I - The Magician', 2],
      ['Arcana Force III - The Empress', 2],
      ['Arcana Force IV - The Emperor', 2],
      ['Arcana Force VII - The Chariot', 3],
      ['Arcana Force XIV - Temperance', 3],
      ['Light Barrier', 3],
      ['Terraforming', 1],
      ['Second Coin Toss', 2],
      ['Cup of Ace', 3],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Reversal of Fate', 3],
      ['Arcana Call', 2],
      ['Mirror Force', 1],
      ['Call of the Haunted', 2],
      ['Solemn Judgment', 2],
    ],
  },

  // ===========================================================================
  // 17. Yubel
  // ===========================================================================
  {
    id: 'yubel_deck_1',
    characterId: 'yubel',
    name: 'Nightmare Reincarnation',
    archetype: 'Yubel / Damage Reflection',
    description: 'The ancient spirit of eternal love and torment evolving through Terror Incarnate into The Ultimate Nightmare to reflect all battle damage.',
    signatureCards: ['Yubel', 'Yubel - Terror Incarnate', 'Yubel - The Ultimate Nightmare'],
    main: [
      ['Yubel', 3],
      ['Yubel - Terror Incarnate', 2],
      ['Yubel - The Ultimate Nightmare', 1],
      ['Samsara Lotus', 3],
      ['Mystic Tomato', 3],
      ['Grinder Golem', 2],
      ['Grave Squirmer', 3],
      ['Sangan', 1],
      ['Armageddon Knight', 2],
      ['Dark Hole', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Allure of Darkness', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Limit Reverse', 3],
      ['Hate Buster', 3],
      ['Damage Condenser', 2],
      ['Call of the Haunted', 2],
      ['Mirror Force', 1],
      ['Torrential Tribute', 1],
    ],
  },

  // ===========================================================================
  // 18. Nightshroud
  // ===========================================================================
  {
    id: 'nightshroud_deck_1',
    characterId: 'nightshroud',
    name: 'Darkness World & Neosphere',
    archetype: 'Darkness / High Level Fiend & Dragon',
    description: 'The embodiment of universal nothingness commanding Darkness Neosphere, Darkness Destroyer, and Red-Eyes Darkness Metal Dragon.',
    signatureCards: ['Darkness Neosphere', 'Darkness Destroyer', 'Red-Eyes Darkness Metal Dragon'],
    main: [
      ['Darkness Neosphere', 2],
      ['Darkness Destroyer', 2],
      ['Red-Eyes Darkness Metal Dragon', 2],
      ['Red-Eyes Darkness Dragon', 1],
      ['Red-Eyes Wyvern', 3],
      ['Mirage Dragon', 3],
      ['Mystic Tomato', 3],
      ['Gravekeeper\'s Spy', 3],
      ['Sangan', 1],
      ['Allure of Darkness', 3],
      ['Dragon Shrine', 2],
      ['Trade-In', 2],
      ['Heavy Storm', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Call of the Haunted', 3],
      ['Bottomless Trap Hole', 2],
      ['Mirror Force', 1],
      ['Torrential Tribute', 1],
      ['Solemn Judgment', 2],
      ['Waboku', 2],
    ],
  },

  // ===========================================================================
  // 19. Yusuke Fujiwara
  // ===========================================================================
  {
    id: 'yusuke-fujiwara_deck_1',
    characterId: 'yusuke-fujiwara',
    name: 'Clear World Attribute Void',
    archetype: 'Clear / Anti-Attribute',
    description: 'Fujiwara\'s hollow attribute void deck penalizing every monster attribute with Clear World while attacking with the invincible Clear Vice Dragon.',
    signatureCards: ['Clear Vice Dragon', 'Clear World', 'Clear Kuriboh'],
    main: [
      ['Clear Vice Dragon', 3],
      ['Clear Kuriboh', 3],
      ['Mystic Tomato', 3],
      ['Snipe Hunter', 2],
      ['Breaker the Magical Warrior', 2],
      ['Chaos Sorcerer', 2],
      ['Dark Armed Dragon', 1],
      ['Sangan', 1],
      ['Clear World', 3],
      ['Terraforming', 2],
      ['Field Barrier', 2],
      ['Allure of Darkness', 3],
      ['Dark Eruption', 2],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Heavy Storm', 1],
      ['Bottomless Trap Hole', 2],
      ['Dimensional Prison', 2],
      ['Mirror Force', 1],
      ['Call of the Haunted', 2],
      ['Torrential Tribute', 1],
      ['Solemn Judgment', 1],
    ],
  },

  // ===========================================================================
  // 20. Supreme King Jaden
  // ===========================================================================
  {
    id: 'supreme-king-jaden_deck_1',
    characterId: 'supreme-king-jaden',
    name: 'Evil HERO Dark Calling',
    archetype: 'Evil HERO / Dark Fusion',
    description: 'The cold and merciless Supreme King commanding corrupted Fiends through Dark Fusion and Dark Calling to summon Evil HERO Dark Gaia and Malicious Bane.',
    signatureCards: ['Evil HERO Dark Gaia', 'Dark Calling', 'Evil HERO Malicious Edge'],
    main: [
      ['Evil HERO Malicious Edge', 3],
      ['Evil HERO Infernal Prodigy', 3],
      ['Evil HERO Infernal Gainer', 3],
      ['Valkyrion the Magna Warrior', 2],
      ['Morphing Jar', 1],
      ['Elemental HERO Stratos', 1],
      ['Elemental HERO Prisma', 2],
      ['King of the Swamp', 3],
      ['Dark Fusion', 3],
      ['Dark Calling', 3],
      ['Super Polymerization', 2],
      ['E - Emergency Call', 2],
      ['Reinforcement of the Army', 1],
      ['Pot of Greed', 1],
      ['Monster Reborn', 1],
      ['Heavy Storm', 1],
      ['Call of the Haunted', 2],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
      ['Solemn Judgment', 2],
      ['Torrential Tribute', 1],
    ],
    extra: [
      ['Evil HERO Dark Gaia', 3],
      ['Evil HERO Lightning Golem', 2],
      ['Evil HERO Inferno Wing', 2],
    ],
  },

  // ===========================================================================
  // Additional Authentic Canon Expansions
  // ===========================================================================

  // 12. Jaden Yuki - Masked HERO Transformation (GX Manga / Video Games)
  {
    id: 'jaden-yuki_deck_4',
    characterId: 'jaden-yuki',
    name: 'Masked HERO Transformation',
    archetype: 'Masked HERO / Quick-Play',
    description: 'Jaden\'s official GX manga deck utilizing Mask Change and Form Change to transform Elemental HEROs into Masked HERO Dark Law, Koga, and Dian.',
    signatureCards: ['Masked HERO Dark Law', 'Masked HERO Koga', 'Mask Change'],
    main: [
      ['Elemental HERO Shadow Mist', 3],
      ['Elemental HERO Stratos', 1],
      ['Elemental HERO Solid Soldier', 3],
      ['Elemental HERO Blazeman', 2],
      ['Elemental HERO Bubbleman', 2],
      ['Elemental HERO Sparkman', 2],
      ['Elemental HERO Wildheart', 2],
      ['Mask Change', 3],
      ['Mask Change II', 2],
      ['Form Change', 2],
      ['A Hero Lives', 2],
      ['E - Emergency Call', 3],
      ['Reinforcement of the Army', 1],
      ['The Warrior Returning Alive', 2],
      ['Polymerization', 2],
      ['Miracle Fusion', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Hero Signal', 2],
      ['Mirror Force', 1],
      ['Bottomless Trap Hole', 2],
      ['Solemn Judgment', 1],
    ],
    extra: [
      ['Masked HERO Dark Law', 2],
      ['Masked HERO Koga', 2],
      ['Masked HERO Dian', 2],
      ['Masked HERO Acid', 2],
      ['Masked HERO Vapor', 1],
      ['Masked HERO Goka', 1],
      ['Elemental HERO Flame Wingman', 1],
      ['Elemental HERO The Shining', 1],
      ['Elemental HERO Absolute Zero', 1],
      ['Elemental HERO Nova Master', 1],
    ],
  },

  // 13. Bastion Misawa - Yokai Zombie Spirit Realm (GX Manga / Tag Force 3-5)
  {
    id: 'bastion-misawa_deck_2',
    characterId: 'bastion-misawa',
    name: 'Yokai Zombie Spirit Realm',
    archetype: 'Yokai / Zombie Synchro',
    description: 'Bastion\'s legendary GX manga deck commanding Japanese Yokai spirits Gozuki, Mezuki, and Shutendoji to manipulate the graveyard and summon Revived King Ha Des.',
    signatureCards: ['Gozuki', 'Mezuki', 'Revived King Ha Des'],
    main: [
      ['Gozuki', 3],
      ['Mezuki', 3],
      ['Shutendoji', 2],
      ['Kasha', 2],
      ['Plaguespreader Zombie', 2],
      ['Zombie Master', 3],
      ['Goblin Zombie', 3],
      ['Pyramid Turtle', 3],
      ['Red-Eyes Zombie Dragon', 2],
      ['Book of Life', 3],
      ['Zombie World', 2],
      ['Terraforming', 1],
      ['Burial from a Different Dimension', 1],
      ['Foolish Burial', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Call of the Haunted', 2],
      ['Mirror Force', 1],
      ['Torrential Tribute', 1],
      ['Bottomless Trap Hole', 2],
      ['Solemn Judgment', 1],
    ],
    extra: [
      ['Revived King Ha Des', 3],
      ['Doomkaiser Dragon', 3],
      ['Archfiend Zombie-Skull', 2],
    ],
  },

  // 14. Aster Phoenix - Destiny End Dragoon Turbo (GX Season 3/4 & Tag Force 2/3)
  {
    id: 'aster-phoenix_deck_2',
    characterId: 'aster-phoenix',
    name: 'Destiny End Dragoon Turbo',
    archetype: 'Destiny HERO / Dragoon Fusion',
    description: 'Aster\'s supreme anime evolution fusing his ultimate destiny creations Plasma and Dogma into Destiny End Dragoon to incinerate enemy monsters with effect burn.',
    signatureCards: ['Destiny End Dragoon', 'Destiny HERO - Plasma', 'Destiny HERO - Dogma'],
    main: [
      ['Destiny HERO - Plasma', 2],
      ['Destiny HERO - Dogma', 2],
      ['Destiny HERO - Malicious', 3],
      ['Destiny HERO - Dasher', 2],
      ['Destiny HERO - Diamond Dude', 3],
      ['Destiny HERO - Doom Lord', 2],
      ['Destiny HERO - Fear Monger', 2],
      ['Elemental HERO Stratos', 1],
      ['Destiny Draw', 3],
      ['Allure of Darkness', 2],
      ['Polymerization', 3],
      ['Fusion Sage', 2],
      ['Reinforcement of the Army', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Heavy Storm', 1],
      ['D - Time', 2],
      ['D - Chain', 2],
      ['Destiny Signal', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 1],
    ],
    extra: [
      ['Destiny End Dragoon', 3],
    ],
  },

  // 15. Alexis Rhodes - Blizzard Princess & White Night (GX Manga / Tag Force 2/3)
  {
    id: 'alexis-rhodes_deck_3',
    characterId: 'alexis-rhodes',
    name: 'Blizzard Princess & White Night',
    archetype: 'Ice / Water Beatdown',
    description: 'Alexis\'s elegant GX manga deck freezing opposing spells and traps with Blizzard Princess and commanding the majestic White Night Dragon.',
    signatureCards: ['Blizzard Princess', 'White Night Dragon', 'Ice Master'],
    main: [
      ['Blizzard Princess', 3],
      ['White Night Dragon', 2],
      ['Ice Master', 2],
      ['Cold Enchanter', 3],
      ['Blizzard Warrior', 3],
      ['Abyss Soldier', 3],
      ['Skreech', 3],
      ['Hydrogeddon', 3],
      ['Cyber Gymnast', 2],
      ['Salvage', 3],
      ['A Legendary Ocean', 2],
      ['Terraforming', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Spiritual Water Art - Aoi', 2],
      ['Mirror Force', 1],
      ['Torrential Tribute', 1],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 1],
    ],
  },

  // 16. Chazz Princeton - Light and Darkness Dragon Dominion (GX Manga / Tag Force 2/3)
  {
    id: 'chazz-princeton_deck_3',
    characterId: 'chazz-princeton',
    name: 'Light and Darkness Dragon Dominion',
    archetype: 'Dragon / LADD Control',
    description: 'Chazz\'s legendary GX manga deck commanding Light and Darkness Dragon alongside Dragonic Knight and White-Horned Dragon to negate all opponent activations.',
    signatureCards: ['Light and Darkness Dragon', 'Dragonic Knight', 'White-Horned Dragon'],
    main: [
      ['Light and Darkness Dragon', 3],
      ['Dragonic Knight', 2],
      ['White-Horned Dragon', 2],
      ['Armed Dragon LV7', 1],
      ['Armed Dragon LV5', 2],
      ['Armed Dragon LV3', 3],
      ['Decoy Dragon', 3],
      ['Mirage Dragon', 3],
      ['Masked Dragon', 3],
      ['Trade-In', 3],
      ['Dragon\'s Mirror', 2],
      ['Foolish Burial', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Mirror Force', 1],
      ['Torrential Tribute', 1],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 2],
      ['Bottomless Trap Hole', 2],
    ],
    extra: [
      ['Five-Headed Dragon', 2],
    ],
  },

  // 17. Dr. Vellian Crowler - Ultimate Ancient Gear Golem Fusion (GX Season 4 & Tag Force 2/3)
  {
    id: 'vellian-crowler_deck_2',
    characterId: 'vellian-crowler',
    name: 'Ultimate Ancient Gear Golem Fusion',
    archetype: 'Ancient Gear / Heavy Fusion',
    description: 'Crowler\'s ultimate mechanical lesson fusing three Ancient Gear titans with Power Bond into the 4400 ATK unstoppable Ultimate Ancient Gear Golem.',
    signatureCards: ['Ultimate Ancient Gear Golem', 'Ancient Gear Golem', 'Power Bond'],
    main: [
      ['Ancient Gear Golem', 3],
      ['Ancient Gear Beast', 3],
      ['Ancient Gear Engineer', 2],
      ['Ancient Gear Knight', 3],
      ['Ancient Gear Soldier', 3],
      ['Heavy Mech Support Platform', 3],
      ['Power Bond', 3],
      ['Polymerization', 3],
      ['Ancient Gear Castle', 3],
      ['Ancient Gear Workshop', 2],
      ['Ancient Gear Factory', 2],
      ['Limiter Removal', 1],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Heavy Storm', 1],
      ['Mystical Space Typhoon', 2],
      ['Mirror Force', 1],
      ['Solemn Judgment', 1],
      ['Call of the Haunted', 2],
      ['Bottomless Trap Hole', 2],
    ],
    extra: [
      ['Ultimate Ancient Gear Golem', 3],
    ],
  },

  // 18. Jesse Anderson - Yubel-Possessed Advanced Crystal Beasts (GX Season 3 & Tag Force 3)
  {
    id: 'jesse-anderson_deck_2',
    characterId: 'jesse-anderson',
    name: 'Yubel-Possessed Advanced Crystal Beasts',
    archetype: 'Advanced Crystal Beast / Dark Dragon',
    description: 'Jesse under Yubel\'s dark corruption transforming his Crystal Beasts with Advanced Dark to summon the 4000 ATK dark beast Rainbow Dark Dragon.',
    signatureCards: ['Rainbow Dark Dragon', 'Advanced Dark', 'Crystal Beast Sapphire Pegasus'],
    main: [
      ['Rainbow Dark Dragon', 2],
      ['Crystal Beast Sapphire Pegasus', 3],
      ['Crystal Beast Topaz Tiger', 3],
      ['Crystal Beast Ruby Carbuncle', 2],
      ['Crystal Beast Amber Mammoth', 3],
      ['Crystal Beast Cobalt Eagle', 2],
      ['Crystal Beast Amethyst Cat', 2],
      ['Crystal Beast Emerald Tortoise', 2],
      ['Advanced Dark', 3],
      ['Terraforming', 1],
      ['Crystal Release', 3],
      ['Crystal Promise', 3],
      ['Crystal Beacon', 2],
      ['Crystal Abundance', 2],
      ['Crystal Blessing', 2],
      ['Monster Reborn', 1],
      ['Pot of Greed', 1],
      ['Heavy Storm', 1],
      ['Mirror Force', 1],
      ['Torrential Tribute', 1],
      ['Solemn Judgment', 1],
      ['Crystal Raigeki', 1],
    ],
  },
];

