import { buildDeck, DM_GX_STAPLES } from '../deckGenHelper.js';
import type { CustomDeck } from '../../src/shared/types/deck.js';

interface RawPopularDeckDef {
  id: string;
  name: string;
  series: 'DM' | 'GX';
  archetype: string;
  keyCards: (string | number)[];
  criteria: {
    race?: string;
    type?: string;
    attribute?: string;
    nameContains?: string;
    era?: string;
  };
  extra?: (string | number)[];
}

const POPULAR_100_DEFS: RawPopularDeckDef[] = [
  // =========================================================================
  // 1–20: Classic Formats, Tournament Meta & High-Power Combos
  // =========================================================================
  {
    id: 'pop-goat-control',
    name: 'Goat Control Classic',
    series: 'DM',
    archetype: 'Goat Control',
    keyCards: [
      'Black Luster Soldier - Envoy of the Beginning', 'Scapegoat', 'Scapegoat', 'Tsukuyomi',
      'Magician of Faith', 'Magician of Faith', 'Sinister Serpent', 'Airknight Parshath',
      'Breaker the Magical Warrior', 'Sangan', 'Tribe-Infecting Virus', 'Morphing Jar',
      'Pot of Greed', 'Graceful Charity', 'Delinquent Duo', 'Snatch Steal', 'Premature Burial',
      'Heavy Storm', 'Mystical Space Typhoon', 'Book of Moon', 'Book of Moon',
      'Metamorphosis', 'Metamorphosis', 'Mirror Force', 'Torrential Tribute', 'Call of the Haunted',
      'Ring of Destruction',
    ],
    criteria: { era: 'DM' },
    extra: ['Thousand-Eyes Restrict', 'Dark Balter the Terrible', 'Ryu Senshi', 'Giltia the D. Knight'],
  },
  {
    id: 'pop-chaos-yata-lock',
    name: 'Chaos Yata-Lock Emperor',
    series: 'DM',
    archetype: 'Chaos / Hand Lockdown',
    keyCards: [
      'Chaos Emperor Dragon - Envoy of the End', 'Black Luster Soldier - Envoy of the Beginning',
      'Yata-Garasu', 'Sangan', 'Witch of the Black Forest', 'Cyber Jar', 'D.D. Warrior Lady',
      'Breaker the Magical Warrior', 'Kycoo the Ghost Destroyer', 'Exiled Force', 'Sinister Serpent',
      'Pot of Greed', 'Graceful Charity', 'Raigeki', 'Harpie\'s Feather Duster', 'Dark Hole',
      'Monster Reborn', 'Premature Burial', 'Snatch Steal', 'Change of Heart', 'Painful Choice',
      'The Forceful Sentry', 'Confiscation', 'Delinquent Duo', 'Mirage of Nightmare', 'Imperial Order',
      'Mirror Force', 'Ring of Destruction',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-chaos-sorcerer-control',
    name: 'Chaos Sorcerer Twilight Control',
    series: 'DM',
    archetype: 'Chaos / Banish Removal',
    keyCards: [
      'Chaos Sorcerer', 'Chaos Sorcerer', 'Chaos Sorcerer',
      'Black Luster Soldier - Envoy of the Beginning', 'D.D. Warrior Lady', 'Breaker the Magical Warrior',
      'Magician of Faith', 'Magician of Faith', 'Apprentice Magician', 'Old Vindictive Magician',
      'Kycoo the Ghost Destroyer', 'Spirit Reaper', 'Sangan', 'Morphing Jar',
      'Pot of Greed', 'Graceful Charity', 'Snatch Steal', 'Premature Burial', 'Monster Reborn',
      'Heavy Storm', 'Mystical Space Typhoon', 'Book of Moon', 'Nobleman of Crossout',
      'Mirror Force', 'Torrential Tribute', 'Call of the Haunted', 'Ring of Destruction',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-perfect-circle-monarchs',
    name: 'Perfect Circle Monarchs',
    series: 'GX',
    archetype: 'Destiny HERO / Monarchs',
    keyCards: [
      'Caius the Shadow Monarch', 'Caius the Shadow Monarch', 'Raiza the Storm Monarch', 'Thestalos the Firestorm Monarch',
      'Destiny HERO - Disk Commander', 'Destiny HERO - Malicious', 'Destiny HERO - Malicious', 'Destiny HERO - Malicious',
      'Destiny HERO - Fear Monger', 'Elemental HERO Stratos', 'Treeborn Frog', 'Sangan',
      'Destiny Draw', 'Destiny Draw', 'Destiny Draw', 'Allure of Darkness', 'Allure of Darkness',
      'Reinforcement of the Army', 'Foolish Burial', 'Soul Exchange', 'Brain Control', 'Monster Reborn',
      'Heavy Storm', 'Mystical Space Typhoon', 'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-airblade-turbo',
    name: 'Airblade Turbo OTK',
    series: 'GX',
    archetype: 'HERO / Dimension Fusion',
    keyCards: [
      'Elemental HERO Stratos', 'Elemental HERO Stratos', 'Destiny HERO - Diamond Dude', 'Destiny HERO - Diamond Dude',
      'Destiny HERO - Malicious', 'Destiny HERO - Malicious', 'Dark Magician of Chaos', 'Sacred Crane',
      'Divine Sword - Phoenix Blade', 'Dimension Fusion', 'Reasoning', 'Monster Gate',
      'Destiny Draw', 'Destiny Draw', 'Reinforcement of the Army', 'Reinforcement of the Army',
      'Magical Stone Excavation', 'Spell Reproduction', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn',
      'Heavy Storm', 'Giant Trunade', 'Premature Burial', 'Snatch Steal',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-dimension-fusion-turbo',
    name: 'Dimension Fusion Turbo',
    series: 'DM',
    archetype: 'Spell Economics / Banish',
    keyCards: [
      'Dark Magician of Chaos', 'Sacred Crane', 'Cyber-Stein', 'D.D. Scout Plane',
      'Dimension Fusion', 'Dimension Fusion', 'Dimension Fusion', 'Spell Economics', 'Spell Economics',
      'Reasoning', 'Reasoning', 'Monster Gate', 'Monster Gate',
      'Card of Safe Return', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Premature Burial',
      'Heavy Storm', 'Giant Trunade', 'Card Destruction', 'Morphing Jar', 'Sangan',
    ],
    criteria: { era: 'DM' },
    extra: ['Cyber End Dragon', 'Blue-Eyes Ultimate Dragon', 'Master of Oz'],
  },
  {
    id: 'pop-troop-dupe-scoop',
    name: 'Troop Dupe Scoop OTK',
    series: 'GX',
    archetype: 'Machine Duplication / Beatdown',
    keyCards: [
      'Card Trooper', 'Card Trooper', 'Card Trooper',
      'Cyber Dragon', 'Cyber Dragon', 'Cyber Dragon',
      'Machine Duplication', 'Machine Duplication', 'Machine Duplication',
      'Limiter Removal', 'Overload Fusion', 'Future Fusion',
      'Sangan', 'Cyber Valley', 'Cyber Valley', 'Snipe Hunter',
      'Heavy Storm', 'Giant Trunade', 'Mystical Space Typhoon', 'Pot of Greed', 'Graceful Charity',
      'Monster Reborn', 'Premature Burial', 'Mirror Force', 'Torrential Tribute', 'Call of the Haunted',
    ],
    criteria: { race: 'Machine', era: 'GX' },
    extra: ['Chimeratech Overdragon', 'Cyber Twin Dragon'],
  },
  {
    id: 'pop-diamond-dude-turbo',
    name: 'Diamond Dude Turbo (DDT)',
    series: 'GX',
    archetype: 'Destiny HERO / Spell Turbo',
    keyCards: [
      'Destiny HERO - Diamond Dude', 'Destiny HERO - Diamond Dude', 'Destiny HERO - Diamond Dude',
      'Destiny HERO - Dasher', 'Dark Magician of Chaos', 'Sacred Crane',
      'Destiny Draw', 'Destiny Draw', 'Destiny Draw',
      'Reasoning', 'Reasoning', 'Reasoning', 'Monster Gate', 'Monster Gate', 'Monster Gate',
      'Reinforcement of the Army', 'Reinforcement of the Army', 'Magical Stone Excavation',
      'Mega Ton Magical Cannon', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Heavy Storm', 'Giant Trunade',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-reasoning-gate',
    name: 'Reasoning Gate Chaos',
    series: 'DM',
    archetype: 'Reasoning / Monster Gate',
    keyCards: [
      'Dark Magician of Chaos', 'Jinzo', 'Black Luster Soldier - Envoy of the Beginning',
      'Chaos Sorcerer', 'Sacred Crane', 'Sacred Crane', 'Cyber Valley', 'Cyber Valley',
      'Reasoning', 'Reasoning', 'Reasoning', 'Monster Gate', 'Monster Gate', 'Monster Gate',
      'Card of Safe Return', 'Divine Sword - Phoenix Blade', 'Dimension Fusion',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Premature Burial', 'Heavy Storm',
      'Giant Trunade', 'Mystical Space Typhoon', 'Mirror Force',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-reversal-quiz-otk',
    name: 'Reversal Quiz Sudden Death',
    series: 'DM',
    archetype: 'Spell OTK / Life Swap',
    keyCards: [
      'Reversal Quiz', 'Reversal Quiz', 'Reversal Quiz',
      'Black Pendant', 'Black Pendant', 'Black Pendant',
      'Fuh-Rin-Ka-Zan', 'Fuh-Rin-Ka-Zan',
      'Wall of Revealing Light', 'Inspection',
      'Scapegoat', 'Scapegoat', 'Swords of Revealing Light',
      'Pot of Greed', 'Graceful Charity', 'Card Destruction', 'Reload', 'Magical Mallet',
      'Upstart Goblin', 'Upstart Goblin', 'Upstart Goblin', 'Toon Table of Contents', 'Toon Table of Contents',
      'Toon Table of Contents', 'Toon World',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-ben-kei-otk',
    name: 'Armed Samurai Ben Kei 1-Turn OTK',
    series: 'DM',
    archetype: 'Equip OTK / Multi-Attack',
    keyCards: [
      'Armed Samurai - Ben Kei', 'Armed Samurai - Ben Kei', 'Armed Samurai - Ben Kei',
      'Iron Blacksmith Kotetsu', 'Iron Blacksmith Kotetsu', 'Iron Blacksmith Kotetsu',
      'Maha Vailo', 'Maha Vailo',
      'Mage Power', 'Mage Power', 'Mage Power',
      'United We Stand', 'United We Stand',
      'Axe of Despair', 'Axe of Despair', 'Axe of Despair',
      'Malevolent Nuzzler', 'Malevolent Nuzzler',
      'Reinforcement of the Army', 'Reinforcement of the Army',
      'Giant Trunade', 'Heavy Storm', 'Mystical Space Typhoon', 'Pot of Greed', 'Graceful Charity',
      'Monster Reborn', 'Snatch Steal', 'Premature Burial',
    ],
    criteria: { race: 'Warrior', era: 'DM' },
  },
  {
    id: 'pop-chimeratech-overload',
    name: 'Chimeratech Overload OTK',
    series: 'GX',
    archetype: 'Machine / Overload Fusion',
    keyCards: [
      'Cyber Dragon', 'Cyber Dragon', 'Cyber Dragon',
      'Proto-Cyber Dragon', 'Proto-Cyber Dragon', 'Proto-Cyber Dragon',
      'Cyber Phoenix', 'Cyber Phoenix', 'Cyber Phoenix',
      'Overload Fusion', 'Overload Fusion', 'Overload Fusion',
      'Future Fusion', 'Power Bond', 'Limiter Removal',
      'Heavy Storm', 'Giant Trunade', 'Mystical Space Typhoon', 'Pot of Greed', 'Graceful Charity',
      'Monster Reborn', 'Premature Burial', 'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { race: 'Machine', era: 'GX' },
    extra: ['Chimeratech Overdragon', 'Cyber Twin Dragon', 'Cyber End Dragon'],
  },
  {
    id: 'pop-cyber-stein-megamorph',
    name: 'Cyber-Stein Megamorph Blitz',
    series: 'DM',
    archetype: 'Fusion Summon / Beatdown',
    keyCards: [
      'Cyber-Stein', 'Cyber-Stein', 'Cyber-Stein',
      'Megamorph', 'Megamorph', 'Megamorph',
      'Giant Trunade', 'Heavy Storm', 'Mystical Space Typhoon',
      'Limiter Removal', 'Poison of the Old Man', 'Upstart Goblin', 'Upstart Goblin',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Premature Burial', 'Snatch Steal',
      'Sangan', 'Witch of the Black Forest', 'Swords of Revealing Light', 'Solemn Judgment',
      'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'DM' },
    extra: ['Blue-Eyes Ultimate Dragon', 'Cyber End Dragon', 'Master of Oz', 'Gatling Dragon'],
  },
  {
    id: 'pop-library-exodia-ftk',
    name: 'Royal Magical Library Exodia FTK',
    series: 'DM',
    archetype: 'Exodia / Infinite Draw',
    keyCards: [
      'Exodia the Forbidden One', 'Right Arm of the Forbidden One', 'Left Arm of the Forbidden One',
      'Right Leg of the Forbidden One', 'Left Leg of the Forbidden One',
      'Royal Magical Library', 'Royal Magical Library', 'Royal Magical Library',
      'Toon Table of Contents', 'Toon Table of Contents', 'Toon Table of Contents', 'Toon World',
      'Upstart Goblin', 'Upstart Goblin', 'Upstart Goblin',
      'Pot of Greed', 'Graceful Charity', 'Card Destruction', 'Reload', 'Magical Mallet',
      'Hand Destruction', 'Spell Absorption', 'Swords of Revealing Light',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-chain-burn-lock',
    name: 'Chain Burn Speed Counter',
    series: 'GX',
    archetype: 'Chain Burn / Trap OTK',
    keyCards: [
      'Chain Strike', 'Chain Strike', 'Chain Strike',
      'Just Desserts', 'Just Desserts', 'Just Desserts',
      'Secret Barrel', 'Secret Barrel', 'Secret Barrel',
      'Ojama Trio', 'Ojama Trio', 'Ojama Trio',
      'Accumulated Fortune', 'Accumulated Fortune', 'Accumulated Fortune',
      'Legacy of Yata-Garasu', 'Jar of Greed', 'Reckless Greed', 'Reckless Greed',
      'Waboku', 'Threatening Roar', 'Threatening Roar', 'Marshmallon', 'Lava Golem', 'Lava Golem',
      'Pot of Greed', 'Graceful Charity', 'Card Destruction',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-macro-cosmos-banish',
    name: 'Macro Cosmos Survivor Lockdown',
    series: 'GX',
    archetype: 'Banish Control / Helios',
    keyCards: [
      'Macro Cosmos', 'Macro Cosmos', 'Macro Cosmos',
      'Dimensional Fissure', 'Dimensional Fissure', 'Dimensional Fissure',
      'D.D. Survivor', 'D.D. Survivor', 'D.D. Survivor',
      'D.D. Scout Plane', 'D.D. Scout Plane', 'D.D. Scout Plane',
      'Helios - The Primordial Sun', 'Helios Duo Megistus', 'Golden Homunculus',
      'Banisher of the Radiance', 'Banisher of the Light',
      'Solemn Judgment', 'Solemn Judgment', 'Dark Bribe', 'Mirror Force', 'Torrential Tribute',
      'Pot of Greed', 'Graceful Charity', 'Heavy Storm', 'Mystical Space Typhoon',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-skill-drain-beatdown',
    name: 'Skill Drain Absolute Beatdown',
    series: 'DM',
    archetype: 'Skill Drain / Heavy ATK',
    keyCards: [
      'Skill Drain', 'Skill Drain', 'Skill Drain',
      'Beast King Barbaros', 'Beast King Barbaros', 'Beast King Barbaros',
      'Fusilier Dragon, the Dual-Mode Beast', 'Fusilier Dragon, the Dual-Mode Beast',
      'Chainsaw Insect', 'Chainsaw Insect', 'Chainsaw Insect',
      'Goblin Attack Force', 'Goblin Attack Force', 'Giant Orc',
      'Gene-Warped Warwolf', 'Gene-Warped Warwolf', 'Archfiend Soldier',
      'Pot of Greed', 'Graceful Charity', 'Raigeki', 'Dark Hole', 'Heavy Storm',
      'Mystical Space Typhoon', 'Monster Reborn', 'Mirror Force', 'Solemn Judgment', 'Solemn Judgment',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-gravekeepers-royal-tribute',
    name: "Gravekeeper's Royal Tribute Stun",
    series: 'DM',
    archetype: "Gravekeeper's / Necrovalley",
    keyCards: [
      'Necrovalley', 'Necrovalley', 'Necrovalley',
      'Royal Tribute', 'Royal Tribute', 'Royal Tribute',
      'Gravekeeper\'s Spy', 'Gravekeeper\'s Spy', 'Gravekeeper\'s Spy',
      'Gravekeeper\'s Commandant', 'Gravekeeper\'s Commandant', 'Gravekeeper\'s Commandant',
      'Gravekeeper\'s Assailant', 'Gravekeeper\'s Assailant', 'Gravekeeper\'s Guard',
      'Gravekeeper\'s Chief', 'Gravekeeper\'s Spear Soldier', 'Rite of Spirit',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
      'Solemn Judgment', 'Solemn Judgment', 'Mystical Space Typhoon',
    ],
    criteria: { era: 'DM', race: 'Spellcaster' },
  },
  {
    id: 'pop-hand-control-don-zaloog',
    name: 'Hand Control Discard Lockdown',
    series: 'DM',
    archetype: 'Hand Discard / Control',
    keyCards: [
      'Don Zaloog', 'Don Zaloog', 'Don Zaloog',
      'Spirit Reaper', 'Spirit Reaper', 'Spirit Reaper',
      'Drop Off', 'Drop Off', 'Time Seal',
      'Delinquent Duo', 'Confiscation', 'The Forceful Sentry',
      'Robbin\' Goblin', 'Robbin\' Zombie',
      'Sangan', 'Witch of the Black Forest', 'Breaker the Magical Warrior',
      'Pot of Greed', 'Graceful Charity', 'Raigeki', 'Dark Hole', 'Monster Reborn', 'Snatch Steal',
      'Premature Burial', 'Mirror Force', 'Torrential Tribute', 'Ring of Destruction',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-exodia-necross-immortal',
    name: 'Exodia Necross Immortal Realm',
    series: 'DM',
    archetype: 'Exodia Necross / Graveyard',
    keyCards: [
      'Exodia Necross', 'Exodia Necross', 'Exodia Necross',
      'Contract with Exodia', 'Contract with Exodia', 'Contract with Exodia',
      'Exodia the Forbidden One', 'Right Arm of the Forbidden One', 'Left Arm of the Forbidden One',
      'Right Leg of the Forbidden One', 'Left Leg of the Forbidden One',
      'Emissary of the Afterlife', 'Emissary of the Afterlife',
      'Foolish Burial', 'Foolish Burial', 'Armageddon Knight',
      'Pot of Greed', 'Graceful Charity', 'Card Destruction', 'Monster Reborn', 'Swords of Revealing Light',
      'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { era: 'DM' },
  },

  // =========================================================================
  // 21–40: GX Powerhouses & Archetypes
  // =========================================================================
  {
    id: 'pop-e-hero-omni-super-poly',
    name: 'Elemental HERO Super Poly Omni',
    series: 'GX',
    archetype: 'Elemental HERO / Fusion',
    keyCards: [
      'Elemental HERO Stratos', 'Elemental HERO Neos Alius', 'Elemental HERO Neos Alius',
      'Elemental HERO Prisma', 'Elemental HERO Ocean', 'Elemental HERO Woodsman',
      'Super Polymerization', 'Super Polymerization', 'Polymerization', 'Polymerization',
      'Miracle Fusion', 'Miracle Fusion', 'Parallel World Fusion',
      'E - Emergency Call', 'E - Emergency Call', 'Reinforcement of the Army',
      'Hero Flash!!', 'Hero Heart', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn',
      'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { race: 'Warrior', era: 'GX' },
    extra: ['Elemental HERO Absolute Zero', 'Elemental HERO The Shining', 'Elemental HERO Gaia', 'Elemental HERO Nova Master', 'Elemental HERO Great Tornado', 'Elemental HERO Flame Wingman'],
  },
  {
    id: 'pop-cyber-dragon-power-bond',
    name: 'Cyber Dragon Power Bond Surge',
    series: 'GX',
    archetype: 'Cyber Dragon / OTK',
    keyCards: [
      'Cyber Dragon', 'Cyber Dragon', 'Cyber Dragon',
      'Proto-Cyber Dragon', 'Proto-Cyber Dragon', 'Cyber Valley', 'Cyber Valley',
      'Power Bond', 'Power Bond', 'Power Bond',
      'Overload Fusion', 'Future Fusion', 'Evolution Burst', 'Limiter Removal',
      'Cyber Repair Plant', 'Megamorph', 'Heavy Storm', 'Mystical Space Typhoon',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { race: 'Machine', era: 'GX' },
    extra: ['Cyber Twin Dragon', 'Cyber End Dragon', 'Chimeratech Overdragon'],
  },
  {
    id: 'pop-destiny-hero-clock-tower',
    name: 'Destiny HERO Dreadmaster Clock Tower',
    series: 'GX',
    archetype: 'Destiny HERO / Clock Tower',
    keyCards: [
      'Destiny HERO - Dreadmaster', 'Destiny HERO - Dreadmaster',
      'Clock Tower Prison', 'Clock Tower Prison', 'Clock Tower Prison',
      'Destiny HERO - Captain Tenacious', 'Destiny HERO - Diamond Dude', 'Destiny HERO - Malicious', 'Destiny HERO - Malicious',
      'Destiny HERO - Dasher', 'Destiny HERO - Double Dude',
      'Destiny Draw', 'Destiny Draw', 'Destiny Draw', 'Allure of Darkness', 'Reinforcement of the Army',
      'D - Time', 'D - Shield', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { era: 'GX', race: 'Warrior' },
  },
  {
    id: 'pop-evil-hero-dark-gaia-ruin',
    name: 'Evil HERO Dark Gaia 6000 ATK Ruin',
    series: 'GX',
    archetype: 'Evil HERO / Dark Fusion',
    keyCards: [
      'Dark Fusion', 'Dark Fusion', 'Dark Fusion',
      'Dark Calling', 'Dark Calling', 'Dark Calling',
      'Evil HERO Malicious Edge', 'Evil HERO Malicious Edge',
      'Valkyrion the Magna Warrior', 'Megarock Dragon', 'Golem Sentry',
      'Gorz the Emissary of Darkness', 'Sangan',
      'Pot of Greed', 'Graceful Charity', 'Heavy Storm', 'Giant Trunade', 'Monster Reborn',
      'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { era: 'GX' },
    extra: ['Evil HERO Dark Gaia', 'Evil HERO Malicious Fiend', 'Evil HERO Lightning Golem'],
  },
  {
    id: 'pop-volcanic-doomfire-inferno',
    name: 'Volcanic Doomfire Blaze Inferno',
    series: 'GX',
    archetype: 'Volcanic / Burn',
    keyCards: [
      'Volcanic Doomfire', 'Volcanic Doomfire',
      'Volcanic Rocket', 'Volcanic Rocket', 'Volcanic Rocket',
      'Volcanic Scattershot', 'Volcanic Scattershot', 'Volcanic Scattershot',
      'Volcanic Shell', 'Volcanic Shell', 'Volcanic Shell',
      'Blaze Accelerator', 'Blaze Accelerator', 'Tri-Blaze Accelerator',
      'Royal Firestorm Guards', 'Wild Fire',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mystical Space Typhoon',
      'Mirror Force', 'Torrential Tribute', 'Secret Barrel', 'Solemn Judgment',
    ],
    criteria: { race: 'Pyro', era: 'GX' },
  },
  {
    id: 'pop-ancient-gear-overlord',
    name: 'Ancient Gear Ultimate Overlord',
    series: 'GX',
    archetype: 'Ancient Gear / Machines',
    keyCards: [
      'Ancient Gear Golem', 'Ancient Gear Golem', 'Ancient Gear Golem',
      'Ancient Gear Beast', 'Ancient Gear Engineer', 'Ancient Gear Knight',
      'Ancient Gear Castle', 'Ancient Gear Castle', 'Ancient Gear Drill',
      'Ancient Gear Workshop', 'Polymerization', 'Polymerization',
      'Power Bond', 'Limiter Removal', 'Heavy Storm', 'Pot of Greed', 'Graceful Charity',
      'Monster Reborn', 'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { race: 'Machine', era: 'GX' },
    extra: ['Ultimate Ancient Gear Golem'],
  },
  {
    id: 'pop-crystal-beast-abundance',
    name: 'Crystal Beast Rainbow Abundance',
    series: 'GX',
    archetype: 'Crystal Beast / Rainbow',
    keyCards: [
      'Rainbow Dragon', 'Rainbow Dragon',
      'Crystal Beast Sapphire Pegasus', 'Crystal Beast Sapphire Pegasus', 'Crystal Beast Sapphire Pegasus',
      'Crystal Beast Ruby Carbuncle', 'Crystal Beast Ruby Carbuncle', 'Crystal Beast Ruby Carbuncle',
      'Crystal Beast Topaz Tiger', 'Crystal Beast Amber Mammoth', 'Crystal Beast Cobalt Eagle',
      'Crystal Abundance', 'Crystal Abundance', 'Crystal Beacon', 'Crystal Beacon', 'Crystal Promise',
      'Ancient City - Rainbow Ruins', 'Ancient City - Rainbow Ruins',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-cyberdark-darkness-impact',
    name: 'Cyberdark Darkness Dragon Impact',
    series: 'GX',
    archetype: 'Cyberdark / Dragons',
    keyCards: [
      'Cyberdark Horn', 'Cyberdark Horn', 'Cyberdark Horn',
      'Cyberdark Edge', 'Cyberdark Edge', 'Cyberdark Edge',
      'Cyberdark Keel', 'Cyberdark Keel', 'Cyberdark Keel',
      'Cyberdark Impact!', 'Cyberdark Impact!',
      'Red-Eyes Darkness Metal Dragon', 'Hunter Dragon', 'Twin-Headed Behemoth',
      'Future Fusion', 'Overload Fusion', 'Polymerization',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'GX' },
    extra: ['Cyberdark Dragon', 'Five-Headed Dragon'],
  },
  {
    id: 'pop-arcana-force-the-world',
    name: 'Arcana Force The World Turn Skip',
    series: 'GX',
    archetype: 'Arcana Force / Turn Skip',
    keyCards: [
      'Arcana Force XXI - The World', 'Arcana Force XXI - The World', 'Arcana Force XXI - The World',
      'Arcana Force EX - The Light Ruler', 'Arcana Force EX - The Dark Ruler',
      'Arcana Force 0 - The Fool', 'Arcana Force 0 - The Fool',
      'Light Barrier', 'Light Barrier', 'Light Barrier',
      'Reversal of Fate', 'Reversal of Fate', 'Cup of Ace', 'Cup of Ace',
      'Samsara Lotus', 'Treeborn Frog',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Swords of Revealing Light', 'Mirror Force',
    ],
    criteria: { era: 'GX', race: 'Fairy' },
  },
  {
    id: 'pop-ojama-delta-hurricane-king',
    name: 'Ojama Delta Hurricane King OTK',
    series: 'GX',
    archetype: 'Ojama / Beast',
    keyCards: [
      'Ojama Green', 'Ojama Green', 'Ojama Green',
      'Ojama Yellow', 'Ojama Yellow', 'Ojama Yellow',
      'Ojama Black', 'Ojama Black', 'Ojama Black',
      'Ojama Delta Hurricane!!', 'Ojama Delta Hurricane!!', 'Ojama Delta Hurricane!!',
      'Ojamagic', 'Ojamagic', 'Ojama Trio', 'Ojama Trio',
      'Polymerization', 'Polymerization', 'Super Polymerization',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Beast', era: 'GX' },
    extra: ['Ojama King', 'Ojama Knight'],
  },
  {
    id: 'pop-cloudian-nimbusman-storm',
    name: 'Cloudian Nimbusman Fog Storm',
    series: 'GX',
    archetype: 'Cloudian / Battle Immune',
    keyCards: [
      'Cloudian - Nimbusman', 'Cloudian - Nimbusman', 'Cloudian - Nimbusman',
      'Cloudian - Eye of the Typhoon', 'Cloudian - Eye of the Typhoon',
      'Cloudian - Turbulence', 'Cloudian - Turbulence', 'Cloudian - Smoke Ball', 'Cloudian - Smoke Ball',
      'Cloudian - Acid Cloud', 'Cloudian - Cirrostratus',
      'Cloudian Squall', 'Cloudian Squall', 'Fog Control', 'Diamond-Dust Cyclone', 'Spirit Barrier',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'GX', race: 'Fairy' },
  },
  {
    id: 'pop-fossil-dynasty-rock-excavation',
    name: 'Fossil Dynasty Rock Excavation',
    series: 'GX',
    archetype: 'Rock Stun / Excavation',
    keyCards: [
      'Megarock Dragon', 'Megarock Dragon', 'Granmarg the Rock Monarch',
      'Legendary Jujitsu Master', 'Legendary Jujitsu Master', 'Golem Sentry', 'Golem Sentry',
      'Guardian Sphinx', 'Giant Soldier of Stone',
      'Rock Bombardment', 'Rock Bombardment', 'Fossil Excavation', 'Fossil Excavation',
      'Pot of Greed', 'Graceful Charity', 'Raigeki', 'Dark Hole', 'Monster Reborn',
      'Swords of Revealing Light', 'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { race: 'Rock', era: 'GX' },
  },
  {
    id: 'pop-neo-spacian-contact-fusion',
    name: 'Neo-Spacian Contact Fusion Realm',
    series: 'GX',
    archetype: 'Elemental HERO / Neo-Spacian',
    keyCards: [
      'Elemental HERO Neos', 'Elemental HERO Neos', 'Elemental HERO Neos',
      'Neo-Spacian Grand Mole', 'Neo-Spacian Flare Scarab', 'Neo-Spacian Dark Panther',
      'Neo-Spacian Air Hummingbird', 'Neo-Spacian Glow Moss', 'Neo-Spacian Aqua Dolphin',
      'Neo Space', 'Neo Space', 'Fake Hero', 'Convert Contact', 'Contact Out',
      'NEX', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn',
      'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'GX' },
    extra: ['Elemental HERO Magma Neos', 'Elemental HERO Storm Neos', 'Elemental HERO Flare Neos', 'Elemental HERO Dark Neos', 'Elemental HERO Grand Neos'],
  },
  {
    id: 'pop-venom-deity-vennominaga',
    name: 'Venom Deity Vennominaga Poison',
    series: 'GX',
    archetype: 'Reptile / Venom / Counters',
    keyCards: [
      'Vennominaga the Deity of Poisonous Snakes', 'Vennominaga the Deity of Poisonous Snakes',
      'Vennominon the King of Poisonous Snakes', 'Vennominon the King of Poisonous Snakes',
      'Rise of the Snake Deity', 'Rise of the Snake Deity', 'Rise of the Snake Deity',
      'Snake Rain', 'Snake Rain', 'Snake Rain',
      'Venom Snake', 'Venom Serpent', 'Venom Boa',
      'Venom Swamp', 'Venom Swamp', 'Venom Burn',
      'Damage = Reptile', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { race: 'Reptile', era: 'GX' },
  },
  {
    id: 'pop-alien-a-counter-mass-hypnosis',
    name: 'Alien \'A\' Counter Mass Hypnosis',
    series: 'GX',
    archetype: 'Alien / Control',
    keyCards: [
      'Alien Shocktrooper', 'Alien Shocktrooper', 'Alien Shocktrooper',
      'Alien Mother', 'Alien Telepath', 'Alien Hypno', 'Alien Psychic',
      'Mass Hypnosis', 'Mass Hypnosis', 'Orbital Bombardment',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Reptile', era: 'GX' },
  },
  {
    id: 'pop-lightsworn-judgment-dragon',
    name: 'Lightsworn Judgment Dragon Mill',
    series: 'GX',
    archetype: 'Lightsworn / Mill',
    keyCards: [
      'Judgment Dragon', 'Judgment Dragon', 'Judgment Dragon',
      'Lumina, Lightsworn Summoner', 'Lumina, Lightsworn Summoner', 'Lumina, Lightsworn Summoner',
      'Lyla, Lightsworn Sorceress', 'Lyla, Lightsworn Sorceress', 'Lyla, Lightsworn Sorceress',
      'Wulf, Lightsworn Beast', 'Wulf, Lightsworn Beast', 'Wulf, Lightsworn Beast',
      'Garoth, Lightsworn Warrior', 'Ehren, Lightsworn Monk', 'Celestia, Lightsworn Angel',
      'Solar Recharge', 'Solar Recharge', 'Solar Recharge', 'Charge of the Light Brigade',
      'Honest', 'Honest', 'Necro Gardna', 'Monster Reborn', 'Pot of Greed', 'Graceful Charity',
    ],
    criteria: { era: 'GX', attribute: 'LIGHT' },
  },
  {
    id: 'pop-gladiator-beast-gyzarus',
    name: 'Gladiator Beast Gyzarus Tag-Out',
    series: 'GX',
    archetype: 'Gladiator Beast / Contact Fusion',
    keyCards: [
      'Gladiator Beast Bestiari', 'Gladiator Beast Bestiari',
      'Gladiator Beast Laquari', 'Gladiator Beast Laquari', 'Gladiator Beast Laquari',
      'Gladiator Beast Darius', 'Gladiator Beast Darius', 'Gladiator Beast Equeste',
      'Gladiator Beast Murmillo', 'Gladiator Beast Secutor',
      'Gladiator Proving Ground', 'Gladiator Proving Ground', 'Gladiator Beast\'s Respite',
      'Gladiator Beast War Chariot', 'Gladiator Beast War Chariot', 'Gladiator Beast War Chariot',
      'Waboku', 'Threatening Roar', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { era: 'GX' },
    extra: ['Gladiator Beast Gyzarus', 'Gladiator Beast Gyzarus', 'Gladiator Beast Heraklinos'],
  },
  {
    id: 'pop-dark-world-dealings-discard',
    name: 'Dark World Goldd Discard Turbo',
    series: 'GX',
    archetype: 'Dark World / Fiends',
    keyCards: [
      'Goldd, Wu-Lord of Dark World', 'Goldd, Wu-Lord of Dark World', 'Goldd, Wu-Lord of Dark World',
      'Sillva, Warlord of Dark World', 'Sillva, Warlord of Dark World', 'Sillva, Warlord of Dark World',
      'Broww, Huntsman of Dark World', 'Broww, Huntsman of Dark World', 'Broww, Huntsman of Dark World',
      'Beiige, Vanguard of Dark World', 'Brron, Mad King of Dark World',
      'Dark World Dealings', 'Dark World Dealings', 'Dark World Dealings',
      'Gateway to Dark World', 'Dark World Lightning', 'The Cheerful Coffin',
      'Card Destruction', 'Morphing Jar', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn',
    ],
    criteria: { race: 'Fiend', era: 'GX' },
  },
  {
    id: 'pop-batteryman-short-circuit',
    name: 'Batteryman Short Circuit OTK',
    series: 'GX',
    archetype: 'Batteryman / Thunder OTK',
    keyCards: [
      'Batteryman AA', 'Batteryman AA', 'Batteryman AA',
      'Batteryman Micro-Cell', 'Batteryman Micro-Cell', 'Batteryman Micro-Cell',
      'Batteryman Charger', 'Batteryman Charger', 'Batteryman Industrial Strength',
      'Short Circuit', 'Short Circuit', 'Short Circuit',
      'Battery Charger', 'Battery Charger', 'Portable Battery Pack',
      'Machine Duplication', 'Inferno Reckless Summon', 'Honest',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Heavy Storm', 'Mirror Force',
    ],
    criteria: { race: 'Thunder', era: 'GX' },
  },
  {
    id: 'pop-six-samurai-united-rush',
    name: 'Six Samurai Grandmaster United',
    series: 'GX',
    archetype: 'Six Samurai / Warriors',
    keyCards: [
      'Grandmaster of the Six Samurai', 'Grandmaster of the Six Samurai', 'Grandmaster of the Six Samurai',
      'Great Shogun Shien', 'Great Shogun Shien',
      'The Six Samurai - Zanji', 'The Six Samurai - Zanji', 'The Six Samurai - Irou',
      'The Six Samurai - Yaichi', 'The Six Samurai - Kamon',
      'Six Samurai United', 'Six Samurai United', 'Six Samurai United',
      'Reinforcement of the Army', 'Reinforcement of the Army', 'The Warrior Returning Alive',
      'Double Summon', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Warrior', era: 'GX' },
  },

  // =========================================================================
  // 41–60: Classic DM Iconic Decks
  // =========================================================================
  {
    id: 'pop-dark-magician-paladin',
    name: 'Dark Magician Paladin Arcana',
    series: 'DM',
    archetype: 'Spellcaster / Dark Magician',
    keyCards: [
      'Dark Magician', 'Dark Magician', 'Dark Magician',
      'Dark Magician Girl', 'Buster Blader', 'Skilled Dark Magician', 'Skilled Dark Magician',
      'Magician\'s Valkyria', 'Apprentice Magician', 'Old Vindictive Magician',
      'Dark Magic Attack', 'Dark Magic Curtain', 'Thousand Knives', 'Magical Dimension',
      'Polymerization', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn',
      'Swords of Revealing Light', 'Mirror Force', 'Magical Hats',
    ],
    criteria: { race: 'Spellcaster', era: 'DM' },
    extra: ['Dark Paladin'],
  },
  {
    id: 'pop-blue-eyes-master-knight',
    name: 'Blue-Eyes Dragon Master Knight',
    series: 'DM',
    archetype: 'Dragon / Blue-Eyes',
    keyCards: [
      'Blue-Eyes White Dragon', 'Blue-Eyes White Dragon', 'Blue-Eyes White Dragon',
      'Black Luster Soldier', 'Black Luster Ritual', 'Lord of D.', 'Lord of D.',
      'The Flute of Summoning Dragon', 'The Flute of Summoning Dragon',
      'King of the Swamp', 'King of the Swamp', 'Polymerization', 'Polymerization',
      'Burst Stream of Destruction', 'Dragon\'s Mirror',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Raigeki', 'Mirror Force',
    ],
    criteria: { race: 'Dragon', era: 'DM' },
    extra: ['Blue-Eyes Ultimate Dragon', 'Dragon Master Knight'],
  },
  {
    id: 'pop-red-eyes-darkness-dragon-blast',
    name: 'Red-Eyes Darkness Dragon Blast',
    series: 'DM',
    archetype: 'Dragon / Red-Eyes Burn',
    keyCards: [
      'Red-Eyes Black Dragon', 'Red-Eyes Black Dragon', 'Red-Eyes Black Dragon',
      'Red-Eyes Darkness Dragon', 'Red-Eyes Darkness Dragon', 'Red-Eyes Darkness Metal Dragon',
      'Red-Eyes Wyvern', 'Red-Eyes Wyvern', 'Black Dragon\'s Chick',
      'Inferno Fire Blast', 'Inferno Fire Blast', 'Red-Eyes Spirit',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Dragon', era: 'DM' },
  },
  {
    id: 'pop-slifer-sky-dragon-hand',
    name: 'Slifer the Sky Dragon Infinite Power',
    series: 'DM',
    archetype: 'Egyptian God / Slifer',
    keyCards: [
      'Slifer the Sky Dragon', 'Slifer the Sky Dragon', 'Slifer the Sky Dragon',
      'Gorz the Emissary of Darkness', 'Cyber Valley', 'Cyber Valley',
      'Treeborn Frog', 'Marshmallon', 'Spirit Reaper', 'Sangan',
      'Infinite Cards', 'Infinite Cards', 'Card of Safe Return',
      'Soul Exchange', 'Brain Control', 'Double Summon', 'Swords of Revealing Light',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Solemn Judgment',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-obelisk-tormentor-crush',
    name: 'Obelisk the Tormentor Megaton Crush',
    series: 'DM',
    archetype: 'Egyptian God / Obelisk',
    keyCards: [
      'Obelisk the Tormentor', 'Obelisk the Tormentor', 'Obelisk the Tormentor',
      'Nimble Momonga', 'Nimble Momonga', 'Nimble Momonga',
      'Giant Germ', 'Giant Germ', 'Giant Germ',
      'Soul Exchange', 'Soul Exchange', 'Double Summon', 'Double Summon',
      'Mound of the Bound Creator',
      'Pot of Greed', 'Graceful Charity', 'Raigeki', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-winged-dragon-ra-phoenix',
    name: 'Winged Dragon of Ra Immortal Phoenix',
    series: 'DM',
    archetype: 'Egyptian God / Ra',
    keyCards: [
      'The Winged Dragon of Ra', 'The Winged Dragon of Ra', 'The Winged Dragon of Ra',
      'Marshmallon', 'Marshmallon', 'Cyber Valley', 'Cyber Valley',
      'Poison of the Old Man', 'Solemn Wishes', 'Solemn Wishes',
      'Mound of the Bound Creator', 'Double Summon', 'Soul Exchange',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-toon-world-kingdom-direct',
    name: 'Toon World Direct Assault',
    series: 'DM',
    archetype: 'Toon Monsters',
    keyCards: [
      'Toon Dark Magician Girl', 'Toon Dark Magician Girl', 'Toon Dark Magician Girl',
      'Toon Gemini Elf', 'Toon Gemini Elf', 'Toon Summoned Skull', 'Toon Mermaid',
      'Toon World', 'Toon World', 'Toon Table of Contents', 'Toon Table of Contents', 'Toon Table of Contents',
      'Toon Defense', 'Toon Briefcase',
      'Pot of Greed', 'Graceful Charity', 'Raigeki', 'Dark Hole', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-harpie-ladies-hunting-ground',
    name: 'Harpie Ladies Hunting Ground',
    series: 'DM',
    archetype: 'Winged Beast / Harpie',
    keyCards: [
      'Harpie Lady 1', 'Harpie Lady 1', 'Harpie Lady 1',
      'Harpie Lady Sisters', 'Harpie Lady Sisters',
      'Harpie Queen', 'Harpie Queen', 'Harpie Queen',
      'Harpies\' Hunting Ground', 'Harpies\' Hunting Ground', 'Harpies\' Hunting Ground',
      'Elegant Egotist', 'Elegant Egotist', 'Harpie\'s Feather Duster', 'Harpie\'s Feather Duster',
      'Triangle Ecstasy Spark', 'Icarus Attack', 'Icarus Attack',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { race: 'Winged Beast', era: 'DM' },
  },
  {
    id: 'pop-buster-blader-dragon-slayer',
    name: 'Buster Blader Dragon Slayer',
    series: 'DM',
    archetype: 'Warrior / Buster Blader',
    keyCards: [
      'Buster Blader', 'Buster Blader', 'Buster Blader',
      'Skilled White Magician', 'Skilled White Magician',
      'Emblem of Dragon Destroyer', 'Emblem of Dragon Destroyer',
      'Dark Magician', 'Polymerization', 'Polymerization',
      'Reinforcement of the Army', 'The Warrior Returning Alive',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Raigeki', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Warrior', era: 'DM' },
    extra: ['Dark Paladin'],
  },
  {
    id: 'pop-amazoness-warrior-pride',
    name: 'Amazoness Warrior Empress Pride',
    series: 'DM',
    archetype: 'Warrior / Amazoness',
    keyCards: [
      'Amazoness Swords Woman', 'Amazoness Swords Woman', 'Amazoness Swords Woman',
      'Amazoness Paladin', 'Amazoness Paladin', 'Amazoness Archer', 'Amazoness Chain Master',
      'Amazoness Tiger', 'Amazoness Fighter', 'Amazoness Archers',
      'Reinforcement of the Army', 'The Warrior Returning Alive',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Warrior', era: 'DM' },
  },
  {
    id: 'pop-magnet-magna-valkyrion',
    name: 'Magnet Warriors Magna Overlord',
    series: 'DM',
    archetype: 'Rock / Magnet Warriors',
    keyCards: [
      'Valkyrion the Magna Warrior', 'Valkyrion the Magna Warrior',
      'Alpha The Magnet Warrior', 'Alpha The Magnet Warrior',
      'Beta The Magnet Warrior', 'Beta The Magnet Warrior',
      'Gamma The Magnet Warrior', 'Gamma The Magnet Warrior',
      'Golem Sentry', 'Legendary Jujitsu Master',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Rock', era: 'DM' },
  },
  {
    id: 'pop-relinquished-illusion-ritual',
    name: 'Relinquished Illusion Ritual',
    series: 'DM',
    archetype: 'Spellcaster / Ritual Steal',
    keyCards: [
      'Relinquished', 'Relinquished', 'Relinquished',
      'Black Illusion Ritual', 'Black Illusion Ritual', 'Black Illusion Ritual',
      'Senju of the Thousand Hands', 'Senju of the Thousand Hands',
      'Sonic Bird', 'Sonic Bird', 'Manju of the Ten Thousand Hands',
      'Thousand-Eyes Idol', 'Polymerization',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Swords of Revealing Light', 'Mirror Force',
    ],
    criteria: { era: 'DM' },
    extra: ['Thousand-Eyes Restrict', 'Thousand-Eyes Restrict'],
  },
  {
    id: 'pop-zera-the-mant-ritual',
    name: 'Zera the Mant Dark Fiends',
    series: 'DM',
    archetype: 'Fiend / Ritual',
    keyCards: [
      'Zera the Mant', 'Zera the Mant', 'Zera the Mant',
      'Zera Ritual', 'Zera Ritual', 'Zera Ritual',
      'Manju of the Ten Thousand Hands', 'Senju of the Thousand Hands', 'Sonic Bird',
      'Mystic Tomato', 'Mystic Tomato', 'Giant Germ', 'Giant Germ',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Raigeki', 'Dark Hole', 'Mirror Force',
    ],
    criteria: { race: 'Fiend', era: 'DM' },
  },
  {
    id: 'pop-gradius-starship-option',
    name: 'Gradius Starship Laser Option',
    series: 'DM',
    archetype: 'Machine / Gradius',
    keyCards: [
      'Gradius', 'Gradius', 'Gradius',
      'Gradius\' Option', 'Gradius\' Option', 'Gradius\' Option',
      'Cyclon Laser', 'Cyclon Laser',
      'Limiter Removal', 'Machine Duplication', 'Honest',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Machine', era: 'DM' },
  },
  {
    id: 'pop-legendary-ocean-daedalus',
    name: 'Legendary Ocean Daedalus Tsunami',
    series: 'DM',
    archetype: 'Aqua / Sea Serpent / Water',
    keyCards: [
      'A Legendary Ocean', 'A Legendary Ocean', 'A Legendary Ocean',
      'Levia-Dragon - Daedalus', 'Levia-Dragon - Daedalus', 'Ocean Dragon Lord - Neo-Daedalus',
      'Amphibious Bugroth MK-3', 'Amphibious Bugroth MK-3', 'Giga Gagagigo',
      'Tornado Wall', 'Gravity Bind', 'Salvage', 'Salvage',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { attribute: 'WATER', era: 'DM' },
  },
  {
    id: 'pop-gate-guardian-labyrinth',
    name: 'Gate Guardian Labyrinth Fortress',
    series: 'DM',
    archetype: 'Labyrinth / Elements',
    keyCards: [
      'Gate Guardian', 'Gate Guardian',
      'Suijin', 'Suijin', 'Kazejin', 'Kazejin', 'Sanga of the Thunder', 'Sanga of the Thunder',
      'Magical Labyrinth', 'Labyrinth Wall', 'Wall Shadow',
      'Double Summon', 'Soul Exchange', 'Mausoleum of the Emperor',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-gravekeepers-catacomb-lock',
    name: "Gravekeeper's Catacomb Lockdown",
    series: 'DM',
    archetype: "Gravekeeper's Spellcasters",
    keyCards: [
      'Necrovalley', 'Necrovalley', 'Necrovalley',
      'Gravekeeper\'s Chief', 'Gravekeeper\'s Chief',
      'Gravekeeper\'s Spy', 'Gravekeeper\'s Spy', 'Gravekeeper\'s Commandant', 'Gravekeeper\'s Commandant',
      'Gravekeeper\'s Assailant', 'Gravekeeper\'s Spear Soldier', 'Rite of Spirit',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { race: 'Spellcaster', era: 'DM' },
  },
  {
    id: 'pop-zombie-vampire-genesis',
    name: 'Zombie Madness Vampire Genesis',
    series: 'DM',
    archetype: 'Zombie / Graveyard Reborn',
    keyCards: [
      'Vampire Lord', 'Vampire Lord', 'Vampire Genesis',
      'Pyramid Turtle', 'Pyramid Turtle', 'Pyramid Turtle',
      'Zombie Master', 'Zombie Master', 'Mezuki',
      'Book of Life', 'Book of Life', 'Book of Life',
      'Call of the Mummy', 'Call of the Mummy',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Zombie', era: 'DM' },
  },
  {
    id: 'pop-dinosaur-jurassic-crush',
    name: 'Dinosaur Jurassic Tyranno Crush',
    series: 'DM',
    archetype: 'Dinosaur / Beatdown',
    keyCards: [
      'Black Tyranno', 'Super Conductor Tyranno', 'Ultimate Tyranno',
      'Hydrogeddon', 'Hydrogeddon', 'Hydrogeddon',
      'Oxygeddon', 'Oxygeddon', 'Babycerasaurus',
      'Jurassic World', 'Jurassic World', 'Ultra Evolution Pill',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Raigeki', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Dinosaur', era: 'DM' },
  },
  {
    id: 'pop-spell-counter-marionette',
    name: 'Spell Counter Magical Marionette',
    series: 'DM',
    archetype: 'Spellcaster / Counters',
    keyCards: [
      'Magical Marionette', 'Magical Marionette',
      'Skilled Dark Magician', 'Skilled Dark Magician',
      'Apprentice Magician', 'Apprentice Magician', 'Old Vindictive Magician',
      'Spell Absorption', 'Magical Dimension', 'Mega Ton Magical Cannon',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Swords of Revealing Light', 'Mirror Force',
    ],
    criteria: { race: 'Spellcaster', era: 'DM' },
  },

  // =========================================================================
  // 61–80: GX Combos, Boss Engines & Meta
  // =========================================================================
  {
    id: 'pop-frog-monarchs-control',
    name: 'Des Frog Monarchs Tribute Lock',
    series: 'GX',
    archetype: 'Monarch / Frog Control',
    keyCards: [
      'Caius the Shadow Monarch', 'Caius the Shadow Monarch', 'Caius the Shadow Monarch',
      'Raiza the Storm Monarch', 'Mobius the Frost Monarch', 'Thestalos the Firestorm Monarch',
      'Treeborn Frog', 'Des Frog', 'Des Frog', 'Des Frog', 'Poison Draw Frog',
      'Soul Exchange', 'Soul Exchange', 'Brain Control', 'Enemy Controller', 'Enemy Controller',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Heavy Storm', 'Mirror Force',
    ],
    criteria: { era: 'GX' },
    extra: ['D.3.S. Frog'],
  },
  {
    id: 'pop-zombie-master-synchro-rebirth',
    name: 'Zombie Master Rebirth Horde',
    series: 'GX',
    archetype: 'Zombie / Swarm',
    keyCards: [
      'Zombie Master', 'Zombie Master', 'Zombie Master',
      'Il Blud', 'Il Blud', 'Mezuki', 'Mezuki', 'Goblin Zombie', 'Goblin Zombie',
      'Pyramid Turtle', 'Despair from the Dark',
      'Book of Life', 'Book of Life', 'Book of Life', 'Foolish Burial', 'Burial from a Different Dimension',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Zombie', era: 'GX' },
  },
  {
    id: 'pop-sacred-phoenix-nephthys',
    name: 'Sacred Phoenix of Nephthys Reborn',
    series: 'DM',
    archetype: 'Winged Beast / Heavy Storm Reborn',
    keyCards: [
      'Sacred Phoenix of Nephthys', 'Sacred Phoenix of Nephthys', 'Sacred Phoenix of Nephthys',
      'Hand of Nephthys', 'Hand of Nephthys', 'Hand of Nephthys',
      'Apprentice Magician', 'Apprentice Magician', 'Old Vindictive Magician',
      'Foolish Burial', 'Monster Reborn', 'Premature Burial', 'Call of the Haunted',
      'Pot of Greed', 'Graceful Charity', 'Mirror Force', 'Torrential Tribute', 'Solemn Judgment',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-dark-scorpion-burglars',
    name: 'Dark Scorpions Heist Squad',
    series: 'DM',
    archetype: 'Warrior / Dark Scorpion',
    keyCards: [
      'Don Zaloog', 'Don Zaloog', 'Don Zaloog',
      'Dark Scorpion - Meanae the Thorn', 'Dark Scorpion - Meanae the Thorn',
      'Dark Scorpion - Cliff the Trap Remover', 'Dark Scorpion - Gorg the Strong', 'Dark Scorpion - Chick the Yellow',
      'Mustering of the Dark Scorpions', 'Dark Scorpion Combination',
      'Reinforcement of the Army', 'Reinforcement of the Army', 'The Warrior Returning Alive',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { race: 'Warrior', era: 'DM' },
  },
  {
    id: 'pop-twilight-chaos-dragon',
    name: 'Twilight Chaos Judgment',
    series: 'GX',
    archetype: 'Chaos / Lightsworn',
    keyCards: [
      'Judgment Dragon', 'Judgment Dragon', 'Dark Armed Dragon',
      'Chaos Sorcerer', 'Chaos Sorcerer', 'Black Luster Soldier - Envoy of the Beginning',
      'Lumina, Lightsworn Summoner', 'Lyla, Lightsworn Sorceress', 'Wulf, Lightsworn Beast',
      'Solar Recharge', 'Solar Recharge', 'Charge of the Light Brigade', 'Allure of Darkness',
      'Necro Gardna', 'Honest', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-destiny-hero-plasma-lock',
    name: 'Destiny HERO Plasma Absolute Negate',
    series: 'GX',
    archetype: 'Destiny HERO / Negation',
    keyCards: [
      'Destiny HERO - Plasma', 'Destiny HERO - Plasma', 'Destiny HERO - Plasma',
      'Destiny HERO - Malicious', 'Destiny HERO - Malicious', 'Destiny HERO - Malicious',
      'Elemental HERO Stratos', 'Destiny HERO - Diamond Dude', 'Destiny HERO - Disk Commander',
      'Destiny Draw', 'Destiny Draw', 'Destiny Draw', 'Allure of Darkness', 'Reinforcement of the Army',
      'Scapegoat', 'Stray Lambs', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { era: 'GX', race: 'Warrior' },
  },
  {
    id: 'pop-machina-fortress-cannon',
    name: 'Machina Fortress Armored Unit',
    series: 'GX',
    archetype: 'Machina / Machines',
    keyCards: [
      'Machina Fortress', 'Machina Fortress', 'Machina Fortress',
      'Machina Armored Unit', 'Machina Armored Unit', 'Machina Cannon', 'Machina Cannon',
      'Red Gadget', 'Red Gadget', 'Green Gadget', 'Green Gadget', 'Yellow Gadget', 'Yellow Gadget',
      'Limiter Removal', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Machine', era: 'GX' },
  },
  {
    id: 'pop-counter-fairy-sanctuary',
    name: 'Counter Fairy Sanctuary Judgment',
    series: 'GX',
    archetype: 'Fairy / Counter Traps',
    keyCards: [
      'Bountiful Artemis', 'Bountiful Artemis', 'Bountiful Artemis',
      'Meltiel, Sage of the Sky', 'Harvest Angel of Wisdom', 'Layard the Liberator',
      'The Sanctuary in the Sky', 'The Sanctuary in the Sky',
      'Solemn Judgment', 'Solemn Judgment', 'Solemn Judgment',
      'Dark Bribe', 'Dark Bribe', 'Magic Jammer', 'Seven Tools of the Bandit',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { race: 'Fairy', era: 'GX' },
  },
  {
    id: 'pop-yubel-nightmare-evolution-wall',
    name: 'Yubel Nightmare Evolution Wall',
    series: 'GX',
    archetype: 'Fiend / Yubel Evolution',
    keyCards: [
      'Yubel', 'Yubel', 'Yubel',
      'Yubel - Terror Incarnate', 'Yubel - The Ultimate Nightmare',
      'Limit Reverse', 'Limit Reverse', 'Limit Reverse',
      'Samsara Lotus', 'Samsara Lotus', 'Mystic Tomato', 'Armageddon Knight',
      'Allure of Darkness', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { race: 'Fiend', era: 'GX' },
  },
  {
    id: 'pop-clear-world-attribute-chaos',
    name: 'Clear World Attribute Nullification',
    series: 'GX',
    archetype: 'Clear World / Attributes',
    keyCards: [
      'Clear World', 'Clear World', 'Clear World',
      'Clear Vice Dragon', 'Clear Vice Dragon', 'Clear Vice Dragon',
      'Terraforming', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn',
      'Torrential Tribute', 'Mirror Force', 'Solemn Judgment',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-sacred-beast-armityle-phantasm',
    name: 'Sacred Beasts Armityle Chaos Phantasm',
    series: 'GX',
    archetype: 'Sacred Beasts / Phantasms',
    keyCards: [
      'Uria, Lord of Searing Flames', 'Hamon, Lord of Striking Thunder', 'Raviel, Lord of Phantasms',
      'Phantom Skyblaster', 'Phantom Skyblaster', 'Phantasmal Martyrs',
      'Swords of Revealing Light', 'Metal Reflect Slime', 'Embodiment of Apophis',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'GX' },
    extra: ['Armityle the Chaos Phantasm'],
  },
  {
    id: 'pop-uria-lord-searing-flames',
    name: 'Uria Lord of Searing Flames Trap Burn',
    series: 'GX',
    archetype: 'Sacred Beasts / Uria',
    keyCards: [
      'Uria, Lord of Searing Flames', 'Uria, Lord of Searing Flames', 'Uria, Lord of Searing Flames',
      'Nightmare Wheel', 'Nightmare Wheel', 'Nightmare Wheel',
      'Metal Reflect Slime', 'Metal Reflect Slime', 'Embodiment of Apophis', 'Embodiment of Apophis',
      'Zoma the Spirit', 'Zoma the Spirit', 'Mirror Wall',
      'Pot of Greed', 'Graceful Charity', 'Card Destruction', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-hamon-lord-striking-thunder',
    name: 'Hamon Lord of Striking Thunder Lock',
    series: 'GX',
    archetype: 'Sacred Beasts / Hamon',
    keyCards: [
      'Hamon, Lord of Striking Thunder', 'Hamon, Lord of Striking Thunder', 'Hamon, Lord of Striking Thunder',
      'Swords of Revealing Light', 'Spell Absorption', 'Spell Absorption',
      'Messenger of Peace', 'Wave-Motion Cannon', 'Wave-Motion Cannon',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'GX' },
  },
  {
    id: 'pop-raviel-lord-phantasms',
    name: 'Raviel Lord of Phantasms Fiend Horde',
    series: 'GX',
    archetype: 'Sacred Beasts / Raviel',
    keyCards: [
      'Raviel, Lord of Phantasms', 'Raviel, Lord of Phantasms', 'Raviel, Lord of Phantasms',
      'Phantom Skyblaster', 'Phantom Skyblaster', 'Giant Germ', 'Giant Germ', 'Giant Germ',
      'Mystic Tomato', 'Mystic Tomato', 'Sangan',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Raigeki', 'Mirror Force',
    ],
    criteria: { race: 'Fiend', era: 'GX' },
  },
  {
    id: 'pop-cyber-valley-dupe-turbo',
    name: 'Cyber Valley Machine Dupe Engine',
    series: 'GX',
    archetype: 'Machine / Hand Advantage',
    keyCards: [
      'Cyber Valley', 'Cyber Valley', 'Cyber Valley',
      'Machine Duplication', 'Machine Duplication', 'Machine Duplication',
      'Cyber Dragon', 'Cyber Dragon', 'D.D. Survivor',
      'Dimension Fusion',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Heavy Storm', 'Mirror Force', 'Solemn Judgment',
    ],
    criteria: { race: 'Machine', era: 'GX' },
  },
  {
    id: 'pop-ojama-knight-lockdown',
    name: 'Ojama Knight Arena Lockdown',
    series: 'GX',
    archetype: 'Ojama / Fusion Lock',
    keyCards: [
      'Ojama Green', 'Ojama Yellow', 'Ojama Black',
      'Ojamagic', 'Ojamagic', 'Ojama Trio', 'Ojama Trio',
      'Polymerization', 'Polymerization', 'Super Polymerization',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Beast', era: 'GX' },
    extra: ['Ojama Knight', 'Ojama King'],
  },
  {
    id: 'pop-chimeratech-fortress-devour',
    name: 'Chimeratech Fortress Machine Devour',
    series: 'GX',
    archetype: 'Machine / Contact Devour',
    keyCards: [
      'Cyber Dragon', 'Cyber Dragon', 'Cyber Dragon',
      'Cyber Valley', 'Cyber Valley', 'Proto-Cyber Dragon',
      'Overload Fusion', 'Future Fusion', 'Limiter Removal',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Machine', era: 'GX' },
    extra: ['Chimeratech Fortress Dragon', 'Chimeratech Overdragon'],
  },
  {
    id: 'pop-volcanic-chain-blaze-burn',
    name: 'Volcanic Chain Trap Burn',
    series: 'GX',
    archetype: 'Volcanic / Burn Traps',
    keyCards: [
      'Volcanic Rocket', 'Volcanic Rocket', 'Volcanic Rocket',
      'Volcanic Scattershot', 'Volcanic Scattershot', 'Volcanic Scattershot',
      'Blaze Accelerator', 'Secret Barrel', 'Secret Barrel',
      'Just Desserts', 'Just Desserts', 'Ceasefire', 'Ring of Destruction',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { race: 'Pyro', era: 'GX' },
  },
  {
    id: 'pop-ancient-gear-gadget-clockwork',
    name: 'Ancient Gear Gadget Clockwork',
    series: 'GX',
    archetype: 'Ancient Gear / Gadgets',
    keyCards: [
      'Ancient Gear Golem', 'Ancient Gear Golem',
      'Red Gadget', 'Red Gadget', 'Green Gadget', 'Green Gadget', 'Yellow Gadget', 'Yellow Gadget',
      'Ancient Gear Castle', 'Ancient Gear Castle', 'Limiter Removal',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Heavy Storm', 'Mirror Force',
    ],
    criteria: { race: 'Machine', era: 'GX' },
  },
  {
    id: 'pop-destiny-hero-dogma-drain',
    name: 'Destiny HERO Dogma Halve LP Burn',
    series: 'GX',
    archetype: 'Destiny HERO / LP Halve',
    keyCards: [
      'Destiny HERO - Dogma', 'Destiny HERO - Dogma', 'Destiny HERO - Dogma',
      'Destiny HERO - Plasma', 'Destiny HERO - Malicious', 'Destiny HERO - Malicious',
      'Destiny HERO - Diamond Dude', 'Destiny HERO - Disk Commander', 'Elemental HERO Stratos',
      'Destiny Draw', 'Destiny Draw', 'Destiny Draw', 'Allure of Darkness', 'Reinforcement of the Army',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { era: 'GX', race: 'Warrior' },
    extra: ['Destiny End Dragoon'],
  },

  // =========================================================================
  // 81–100: Tricky, Niche, Loved & Fun Engine Decks
  // =========================================================================
  {
    id: 'pop-cyberdark-armed-dragon-lv',
    name: 'Armed Dragon LV Level-Up',
    series: 'GX',
    archetype: 'Armed Dragon / Level Up',
    keyCards: [
      'Armed Dragon LV10', 'Armed Dragon LV7', 'Armed Dragon LV7',
      'Armed Dragon LV5', 'Armed Dragon LV5', 'Armed Dragon LV3', 'Armed Dragon LV3',
      'Level Up!', 'Level Up!', 'Level Up!',
      'Level Modulation', 'Level Modulation', 'Ojama Trio',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Dragon', era: 'GX' },
  },
  {
    id: 'pop-simochi-bad-reaction-burn',
    name: 'Simochi Bad Reaction Healing Burn',
    series: 'DM',
    archetype: 'Burn / Life Point Reverse',
    keyCards: [
      'Bad Reaction to Simochi', 'Bad Reaction to Simochi', 'Bad Reaction to Simochi',
      'Upstart Goblin', 'Upstart Goblin', 'Upstart Goblin',
      'Rain of Mercy', 'Rain of Mercy', 'Rain of Mercy',
      'Soul Taker', 'Soul Taker', 'The Eye of Truth', 'The Eye of Truth',
      'Pot of Greed', 'Graceful Charity', 'Card Destruction', 'Swords of Revealing Light', 'Mirror Force',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-pac-man-flip-control',
    name: 'PAC-MAN Flip Control Stall',
    series: 'DM',
    archetype: 'Flip Effect / Burn',
    keyCards: [
      'Stealth Bird', 'Stealth Bird', 'Stealth Bird',
      'Des Lacooda', 'Des Lacooda', 'Des Lacooda',
      'Swarm of Scarabs', 'Swarm of Scarabs', 'Swarm of Locusts',
      'Wave-Motion Cannon', 'Wave-Motion Cannon',
      'Gravity Bind', 'Level Limit - Area B', 'Wall of Revealing Light',
      'Solemn Judgment', 'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-horus-black-flame-lock',
    name: 'Horus the Black Flame Dragon Lock',
    series: 'DM',
    archetype: 'Dragon / Spell Negation',
    keyCards: [
      'Horus the Black Flame Dragon LV8', 'Horus the Black Flame Dragon LV8',
      'Horus the Black Flame Dragon LV6', 'Horus the Black Flame Dragon LV6', 'Horus the Black Flame Dragon LV4',
      'Level Up!', 'Level Up!', 'Level Modulation',
      'Royal Decree', 'Royal Decree', 'Jinzo',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Raigeki', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Dragon', era: 'DM' },
  },
  {
    id: 'pop-final-countdown-stall',
    name: 'Final Countdown 20-Turn Victory',
    series: 'DM',
    archetype: 'Alternate Win / Defense Stall',
    keyCards: [
      'Final Countdown', 'Final Countdown', 'Final Countdown',
      'Waboku', 'Waboku', 'Waboku',
      'Threatening Roar', 'Threatening Roar', 'Threatening Roar',
      'Thunder of Ruler', 'Frozen Soul',
      'Marshmallon', 'Spirit Reaper', 'Gellenduo',
      'Pot of Greed', 'Graceful Charity', 'Card Destruction', 'Swords of Revealing Light', 'Mirror Force',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-destiny-board-spirit-message',
    name: 'Destiny Board Spirit Message F-I-N-A-L',
    series: 'DM',
    archetype: 'Alternate Win / Destiny Board',
    keyCards: [
      'Destiny Board', 'Destiny Board', 'Destiny Board',
      'Spirit Message "I"', 'Spirit Message "N"', 'Spirit Message "A"', 'Spirit Message "L"',
      'Marshmallon', 'Spirit Reaper', 'Waboku', 'Threatening Roar',
      'Pot of Greed', 'Graceful Charity', 'Swords of Revealing Light', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-clown-control-stumbling',
    name: 'Clown Control Stumbling Carnival',
    series: 'DM',
    archetype: 'Position Change / Bounce',
    keyCards: [
      'Crass Clown', 'Crass Clown', 'Crass Clown',
      'Dream Clown', 'Dream Clown', 'Dream Clown',
      'Blade Rabbit', 'Blade Rabbit',
      'Stumbling', 'Stumbling', 'Stumbling',
      'Labyrinth of Nightmare', 'Labyrinth of Nightmare',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-dark-snake-syndrome-escalation',
    name: 'Dark Snake Syndrome Escalation',
    series: 'DM',
    archetype: 'Continuous Spell / Burn',
    keyCards: [
      'Dark Snake Syndrome', 'Dark Snake Syndrome', 'Dark Snake Syndrome',
      'Prime Material Dragon', 'Prime Material Dragon', 'Des Wombat', 'Des Wombat',
      'Spirit Barrier', 'Spirit Barrier', 'Marshmallon',
      'Poison of the Old Man', 'Solemn Wishes',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-virus-eradicator-crush',
    name: 'Crush Card & Virus Annihilation',
    series: 'DM',
    archetype: 'Virus Traps / Hand Destruction',
    keyCards: [
      'Crush Card Virus', 'Deck Devastation Virus', 'Eradicator Epidemic Virus',
      'Sangan', 'Giant Germ', 'Giant Germ', 'Dark Jeroid',
      'Dark Necrofear', 'Mystic Tomato', 'Mystic Tomato',
      'Pot of Greed', 'Graceful Charity', 'Card Destruction', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { race: 'Fiend', era: 'DM' },
  },
  {
    id: 'pop-dd-assailant-warrior-toolbox',
    name: 'D.D. Assailant Warrior Toolbox',
    series: 'DM',
    archetype: 'Warrior / Banish Toolbox',
    keyCards: [
      'D.D. Assailant', 'D.D. Assailant', 'D.D. Assailant',
      'D.D. Warrior Lady', 'Exiled Force', 'Exiled Force',
      'Don Zaloog', 'Marauding Captain', 'Command Knight',
      'Reinforcement of the Army', 'Reinforcement of the Army', 'The Warrior Returning Alive',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Warrior', era: 'DM' },
  },
  {
    id: 'pop-sea-stealth-water-stealth',
    name: 'Sea Stealth Amphibious Stealth',
    series: 'DM',
    archetype: 'Water / Direct Attack',
    keyCards: [
      'A Legendary Ocean', 'A Legendary Ocean', 'A Legendary Ocean',
      'Amphibious Bugroth MK-3', 'Amphibious Bugroth MK-3', 'Amphibious Bugroth MK-3',
      'Giga Gagagigo', 'Tornado Wall',
      'Salvage', 'Salvage', 'Gravity Bind',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { attribute: 'WATER', era: 'DM' },
  },
  {
    id: 'pop-spiritual-earth-gigantes',
    name: 'Spiritual Earth Gigantes Quake',
    series: 'DM',
    archetype: 'Rock / Earth Beatdown',
    keyCards: [
      'Gigantes', 'Gigantes', 'Gigantes',
      'Megarock Dragon',
      'Giant Soldier of Stone', 'Golem Sentry',
      'Rock Bombardment', 'Fossil Excavation',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { attribute: 'EARTH', era: 'DM' },
  },
  {
    id: 'pop-holactie-sacred-gods',
    name: 'Egyptian God Tri-Power Awakening',
    series: 'DM',
    archetype: 'Egyptian God / Divinity',
    keyCards: [
      'Slifer the Sky Dragon', 'Obelisk the Tormentor', 'The Winged Dragon of Ra',
      'Card of Safe Return', 'Mound of the Bound Creator', 'Mound of the Bound Creator',
      'Double Summon', 'Soul Exchange', 'Gorz the Emissary of Darkness',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-fire-princess-healing-burn',
    name: 'Fire Princess & Solemn Wishes Burn',
    series: 'DM',
    archetype: 'Pyro / Healing Burn',
    keyCards: [
      'Fire Princess', 'Fire Princess', 'Fire Princess',
      'Solemn Wishes', 'Solemn Wishes', 'Solemn Wishes',
      'Nimble Momonga', 'Nimble Momonga', 'Nimble Momonga',
      'Darklord Marie', 'Poison of the Old Man', 'Poison of the Old Man',
      'Swords of Revealing Light', 'Gravity Bind', 'Wall of Revealing Light',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force',
    ],
    criteria: { era: 'DM' },
  },
  {
    id: 'pop-gearfried-smoke-grenade-strip',
    name: 'Gearfried Smoke Grenade Hand Snatch',
    series: 'DM',
    archetype: 'Warrior / Equip Destruction',
    keyCards: [
      'Gearfried the Iron Knight', 'Gearfried the Iron Knight', 'Gearfried the Iron Knight',
      'Gearfried the Swordmaster', 'Release Restraint',
      'Smoke Grenade of the Thief', 'Smoke Grenade of the Thief', 'Smoke Grenade of the Thief',
      'Blast with Chain', 'Blast with Chain', 'Iron Blacksmith Kotetsu',
      'Reinforcement of the Army', 'The Warrior Returning Alive',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Warrior', era: 'DM' },
  },
  {
    id: 'pop-barrel-dragon-russian-roulette',
    name: 'Barrel Dragon Coin Toss Roulette',
    series: 'DM',
    archetype: 'Machine / Coin Flip',
    keyCards: [
      'Blowback Dragon', 'Blowback Dragon', 'Blowback Dragon',
      'Roulette Barrel', 'Roulette Barrel', 'Second Coin Toss', 'Second Coin Toss',
      'Snipe Hunter', 'Time Wizard', 'Barrel Behind the Door',
      'Heavy Storm', 'Limiter Removal', 'Polymerization',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Machine', era: 'DM' },
    extra: ['Gatling Dragon', 'Gatling Dragon'],
  },
  {
    id: 'pop-masked-beast-des-gardius',
    name: 'Masked Beast Des Gardius Curse',
    series: 'DM',
    archetype: 'Fiend / Mask Possession',
    keyCards: [
      'Masked Beast Des Gardius', 'Masked Beast Des Gardius', 'Masked Beast Des Gardius',
      'The Masked Beast', 'Curse of the Masked Beast',
      'Grand Tiki Elder', 'Grand Tiki Elder', 'Melchid the Four-Face Beast', 'Melchid the Four-Face Beast',
      'Mask of Remnants', 'Mask of Remnants', 'Mask of Dispel', 'Mask of Brutality', 'Mask of Restrict',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Fiend', era: 'DM' },
  },
  {
    id: 'pop-jinzo-trap-negation-beat',
    name: 'Jinzo Psycho Shocker Trap Negate',
    series: 'DM',
    archetype: 'Machine / Trap Lockdown',
    keyCards: [
      'Jinzo', 'Jinzo', 'Jinzo',
      'Jinzo - Returner', 'Jinzo - Returner', 'Jinzo - Lord',
      'Amplifier', 'Amplifier',
      'Limiter Removal', 'Machine Duplication', 'Heavy Mech Support Platform',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Snatch Steal', 'Premature Burial',
      'Raigeki', 'Dark Hole', 'Heavy Storm', 'Mystical Space Typhoon',
    ],
    criteria: { race: 'Machine', era: 'DM' },
  },
  {
    id: 'pop-insect-queen-cocoon-swarm',
    name: 'Insect Queen Great Moth Swarm',
    series: 'DM',
    archetype: 'Insect / Swarm',
    keyCards: [
      'Insect Queen', 'Insect Queen',
      'Perfectly Ultimate Great Moth', 'Great Moth', 'Larvae Moth', 'Petit Moth',
      'Cocoon of Evolution', 'Cocoon of Evolution', 'Cocoon of Evolution',
      'Pinch Hopper', 'Pinch Hopper', 'Howling Insect', 'Howling Insect',
      'Insect Barrier', 'DNA Surgery', 'Multiplication of Ants',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { race: 'Insect', era: 'DM' },
  },
  {
    id: 'pop-guardian-eatos-arsenal',
    name: 'Guardian Dreadscythe & Arsenal',
    series: 'DM',
    archetype: 'Guardian / Equips',
    keyCards: [
      'Guardian Eatos', 'Guardian Eatos', 'Guardian Eatos',
      'Guardian Grarl', 'Guardian Ceal', 'Guardian Baou',
      'Celestial Sword - Eatos', 'Gravity Axe - Grarl', 'Shooting Star Bow - Ceal', 'Wicked-Breaking Flamberge - Baou',
      'Arsenal Summoner', 'Arsenal Summoner',
      'Pot of Greed', 'Graceful Charity', 'Monster Reborn', 'Mirror Force', 'Torrential Tribute',
    ],
    criteria: { era: 'DM' },
  },
];

export function getPopularDecks(): CustomDeck[] {
  const decks: CustomDeck[] = [];

  for (let i = 0; i < POPULAR_100_DEFS.length; i++) {
    const def = POPULAR_100_DEFS[i];
    const { main, extra } = buildDeck(def.keyCards, def.criteria, def.extra || []);

    const customDeck: CustomDeck = {
      id: def.id,
      name: def.name,
      main,
      extra,
      createdAt: 1710000000000 + i * 1000,
      updatedAt: 1710000000000 + i * 1000,
      series: def.series,
      archetype: def.archetype,
      characterId: 'popular',
      characterName: 'Community Popular',
      avatar: 'app-resource://characters/avatars/generic.png',
      portrait: 'app-resource://characters/avatars/generic.png',
      category: def.series === 'DM' ? 'popular-dm' : 'popular-gx',
    };

    decks.push(customDeck);
  }

  return decks;
}
