import { OcgAttribute, OcgRace } from 'ocgcore-wasm';
// Bitmask constants for card types
export const TYPE_MONSTER = 0x1;
export const TYPE_SPELL = 0x2;
export const TYPE_TRAP = 0x4;
export const TYPE_NORMAL = 0x10;
export const TYPE_EFFECT = 0x20;
export const TYPE_FLIP = 0x200000;
export const SAMPLE_CARDS = [
    // --- Normal Monsters ---
    {
        code: 91152256,
        name: 'Celtic Guardian',
        desc: 'An elf who learned to wield a sword, he baffles enemies with lightning-fast attacks.',
        alias: 0,
        setcodes: [0],
        type: TYPE_MONSTER | TYPE_NORMAL,
        level: 4,
        attribute: OcgAttribute.EARTH,
        race: OcgRace.WARRIOR,
        attack: 1400,
        defense: 1200,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 70781052,
        name: 'Summoned Skull',
        desc: 'A fiend with dark powers for confusing the enemy. Among the Fiend-Type monsters, this monster boasts considerable strength.',
        alias: 0,
        setcodes: [0x45], // Archfiend
        type: TYPE_MONSTER | TYPE_NORMAL,
        level: 6,
        attribute: OcgAttribute.DARK,
        race: OcgRace.FIEND,
        attack: 2500,
        defense: 1200,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 46986414,
        name: 'Dark Magician',
        desc: 'The ultimate wizard in terms of attack and defense.',
        alias: 0,
        setcodes: [0x10a2], // Dark Magician
        type: TYPE_MONSTER | TYPE_NORMAL,
        level: 7,
        attribute: OcgAttribute.DARK,
        race: OcgRace.SPELLCASTER,
        attack: 2500,
        defense: 2100,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 89631139,
        name: 'Blue-Eyes White Dragon',
        desc: 'This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome beast and lived to tell the tale.',
        alias: 0,
        setcodes: [0xdd], // Blue-Eyes
        type: TYPE_MONSTER | TYPE_NORMAL,
        level: 8,
        attribute: OcgAttribute.LIGHT,
        race: OcgRace.DRAGON,
        attack: 3000,
        defense: 2500,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    // --- Effect Monsters ---
    {
        code: 40640057,
        name: 'Kuriboh',
        desc: "During damage calculation, if your opponent's monster attacks (Quick Effect): You can discard this card; you take no battle damage from that battle.",
        alias: 0,
        setcodes: [0xa4], // Kuriboh
        type: TYPE_MONSTER | TYPE_EFFECT,
        level: 1,
        attribute: OcgAttribute.DARK,
        race: OcgRace.FIEND,
        attack: 300,
        defense: 200,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 54652250,
        name: 'Man-Eater Bug',
        desc: 'FLIP: Target 1 monster on the field; destroy that target.',
        alias: 0,
        setcodes: [0],
        type: TYPE_MONSTER | TYPE_EFFECT | TYPE_FLIP,
        level: 2,
        attribute: OcgAttribute.EARTH,
        race: OcgRace.INSECT,
        attack: 450,
        defense: 600,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 26202165,
        name: 'Sangan',
        desc: 'If this card is sent from the field to the GY: Add 1 monster with 1500 or less ATK from your Deck to your hand.',
        alias: 0,
        setcodes: [0],
        type: TYPE_MONSTER | TYPE_EFFECT,
        level: 3,
        attribute: OcgAttribute.DARK,
        race: OcgRace.FIEND,
        attack: 1000,
        defense: 600,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    // --- Normal Spells ---
    {
        code: 55144522,
        name: 'Pot of Greed',
        desc: 'Draw 2 cards.',
        alias: 0,
        setcodes: [0],
        type: TYPE_SPELL,
        level: 0,
        attribute: 0,
        race: 0n,
        attack: 0,
        defense: 0,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 46130346,
        name: 'Hinotama',
        desc: "Inflict 500 points of damage to your opponent's Life Points.",
        alias: 0,
        setcodes: [0],
        type: TYPE_SPELL,
        level: 0,
        attribute: 0,
        race: 0n,
        attack: 0,
        defense: 0,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 12580477,
        name: 'Raigeki',
        desc: 'Destroy all monsters your opponent controls.',
        alias: 0,
        setcodes: [0],
        type: TYPE_SPELL,
        level: 0,
        attribute: 0,
        race: 0n,
        attack: 0,
        defense: 0,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 53129443,
        name: 'Dark Hole',
        desc: 'Destroy all monsters on the field.',
        alias: 0,
        setcodes: [0],
        type: TYPE_SPELL,
        level: 0,
        attribute: 0,
        race: 0n,
        attack: 0,
        defense: 0,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 25833572,
        name: 'Ookazi',
        desc: 'Inflict 800 damage to your opponent.',
        alias: 0,
        setcodes: [0],
        type: TYPE_SPELL,
        level: 0,
        attribute: 0,
        race: 0n,
        attack: 0,
        defense: 0,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 38480590,
        name: 'Sparks',
        desc: 'Inflict 50 damage to your opponent.',
        alias: 0,
        setcodes: [0],
        type: TYPE_SPELL,
        level: 0,
        attribute: 0,
        race: 0n,
        attack: 0,
        defense: 0,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    // --- Normal Traps ---
    {
        code: 4206964,
        name: 'Trap Hole',
        desc: 'When your opponent Normal or Flip Summons a monster with 1000 or more ATK: Target that monster; destroy that target.',
        alias: 0,
        setcodes: [0x4c], // Hole
        type: TYPE_TRAP,
        level: 0,
        attribute: 0,
        race: 0n,
        attack: 0,
        defense: 0,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
    {
        code: 24068492,
        name: 'Just Desserts',
        desc: 'Inflict 500 damage to your opponent for each monster they control.',
        alias: 0,
        setcodes: [0],
        type: TYPE_TRAP,
        level: 0,
        attribute: 0,
        race: 0n,
        attack: 0,
        defense: 0,
        lscale: 0,
        rscale: 0,
        link_marker: 0,
    },
];
export const CARD_DATABASE = new Map(SAMPLE_CARDS.map((card) => [card.code, card]));
