import type { CharacterPersonality } from '../../../shared/types/character.js';

export const DEFAULT_PERSONALITY: CharacterPersonality = {
  aggression: 0.65,
  defensiveness: 0.50,
  riskTolerance: 0.50,
  comboFocus: 0.70,
  cardAdvantageWeight: 1.00,
  signatureFavoritism: 0.75,
  thinkDelayBaseMs: 650,
  thinkDelayJitterMs: 200,
};

export const CHARACTER_PERSONALITIES: Record<string, CharacterPersonality> = {
  'yugi-muto': {
    aggression: 0.50,
    defensiveness: 0.80,
    riskTolerance: 0.40,
    comboFocus: 0.75,
    cardAdvantageWeight: 1.40,
    signatureFavoritism: 0.80,
    thinkDelayBaseMs: 750,
    thinkDelayJitterMs: 200,
  },
  'yami-yugi': {
    aggression: 0.75,
    defensiveness: 0.50,
    riskTolerance: 0.65,
    comboFocus: 0.85,
    cardAdvantageWeight: 1.30,
    signatureFavoritism: 0.95,
    thinkDelayBaseMs: 700,
    thinkDelayJitterMs: 200,
  },
  'seto-kaiba': {
    aggression: 0.95,
    defensiveness: 0.15,
    riskTolerance: 0.85,
    comboFocus: 0.70,
    cardAdvantageWeight: 1.00,
    signatureFavoritism: 0.95,
    thinkDelayBaseMs: 600,
    thinkDelayJitterMs: 150,
  },
  'joey-wheeler': {
    aggression: 0.88,
    defensiveness: 0.25,
    riskTolerance: 0.95,
    comboFocus: 0.45,
    cardAdvantageWeight: 0.90,
    signatureFavoritism: 0.85,
    thinkDelayBaseMs: 550,
    thinkDelayJitterMs: 200,
  },
  'tea-gardner': {
    aggression: 0.35,
    defensiveness: 0.90,
    riskTolerance: 0.25,
    comboFocus: 0.60,
    cardAdvantageWeight: 1.30,
    signatureFavoritism: 0.70,
    thinkDelayBaseMs: 800,
    thinkDelayJitterMs: 250,
  },
  'tristan-taylor': {
    aggression: 0.80,
    defensiveness: 0.40,
    riskTolerance: 0.60,
    comboFocus: 0.30,
    cardAdvantageWeight: 0.80,
    signatureFavoritism: 0.65,
    thinkDelayBaseMs: 550,
    thinkDelayJitterMs: 150,
  },
  'mai-valentine': {
    aggression: 0.80,
    defensiveness: 0.40,
    riskTolerance: 0.65,
    comboFocus: 0.85,
    cardAdvantageWeight: 1.20,
    signatureFavoritism: 0.85,
    thinkDelayBaseMs: 650,
    thinkDelayJitterMs: 200,
  },
  'bakura-ryou': {
    aggression: 0.45,
    defensiveness: 0.85,
    riskTolerance: 0.60,
    comboFocus: 0.80,
    cardAdvantageWeight: 1.30,
    signatureFavoritism: 0.85,
    thinkDelayBaseMs: 800,
    thinkDelayJitterMs: 250,
  },
  'marik-ishtar': {
    aggression: 0.80,
    defensiveness: 0.55,
    riskTolerance: 0.85,
    comboFocus: 0.75,
    cardAdvantageWeight: 1.10,
    signatureFavoritism: 0.95,
    thinkDelayBaseMs: 700,
    thinkDelayJitterMs: 200,
  },
  'maximillion-pegasus': {
    aggression: 0.55,
    defensiveness: 0.75,
    riskTolerance: 0.65,
    comboFocus: 0.90,
    cardAdvantageWeight: 1.40,
    signatureFavoritism: 0.90,
    thinkDelayBaseMs: 750,
    thinkDelayJitterMs: 250,
  },
  'jaden-yuki': {
    aggression: 0.80,
    defensiveness: 0.40,
    riskTolerance: 0.70,
    comboFocus: 0.95,
    cardAdvantageWeight: 1.20,
    signatureFavoritism: 0.90,
    thinkDelayBaseMs: 600,
    thinkDelayJitterMs: 200,
  },
  'zane-truesdale': {
    aggression: 0.92,
    defensiveness: 0.20,
    riskTolerance: 0.80,
    comboFocus: 0.85,
    cardAdvantageWeight: 1.10,
    signatureFavoritism: 0.90,
    thinkDelayBaseMs: 600,
    thinkDelayJitterMs: 150,
  },
  'syrus-truesdale': {
    aggression: 0.45,
    defensiveness: 0.80,
    riskTolerance: 0.30,
    comboFocus: 0.75,
    cardAdvantageWeight: 1.20,
    signatureFavoritism: 0.75,
    thinkDelayBaseMs: 800,
    thinkDelayJitterMs: 250,
  },
  'chazz-princeton': {
    aggression: 0.85,
    defensiveness: 0.30,
    riskTolerance: 0.75,
    comboFocus: 0.70,
    cardAdvantageWeight: 1.00,
    signatureFavoritism: 0.85,
    thinkDelayBaseMs: 600,
    thinkDelayJitterMs: 200,
  },
  'alexis-rhodes': {
    aggression: 0.70,
    defensiveness: 0.60,
    riskTolerance: 0.55,
    comboFocus: 0.80,
    cardAdvantageWeight: 1.20,
    signatureFavoritism: 0.80,
    thinkDelayBaseMs: 700,
    thinkDelayJitterMs: 200,
  },
  'bastion-misawa': {
    aggression: 0.60,
    defensiveness: 0.70,
    riskTolerance: 0.35,
    comboFocus: 0.85,
    cardAdvantageWeight: 1.50,
    signatureFavoritism: 0.75,
    thinkDelayBaseMs: 850,
    thinkDelayJitterMs: 250,
  },
  'chumley-huffington': {
    aggression: 0.50,
    defensiveness: 0.85,
    riskTolerance: 0.40,
    comboFocus: 0.60,
    cardAdvantageWeight: 1.00,
    signatureFavoritism: 0.80,
    thinkDelayBaseMs: 800,
    thinkDelayJitterMs: 250,
  },
  'aster-phoenix': {
    aggression: 0.75,
    defensiveness: 0.65,
    riskTolerance: 0.60,
    comboFocus: 0.90,
    cardAdvantageWeight: 1.40,
    signatureFavoritism: 0.90,
    thinkDelayBaseMs: 700,
    thinkDelayJitterMs: 200,
  },
  'jesse-anderson': {
    aggression: 0.70,
    defensiveness: 0.55,
    riskTolerance: 0.65,
    comboFocus: 0.90,
    cardAdvantageWeight: 1.30,
    signatureFavoritism: 0.95,
    thinkDelayBaseMs: 650,
    thinkDelayJitterMs: 200,
  },
  'dr-vellian-crowler': {
    aggression: 0.85,
    defensiveness: 0.35,
    riskTolerance: 0.75,
    comboFocus: 0.75,
    cardAdvantageWeight: 1.10,
    signatureFavoritism: 0.90,
    thinkDelayBaseMs: 650,
    thinkDelayJitterMs: 200,
  },
};

export function getPersonalityForCharacter(characterId?: string): CharacterPersonality {
  if (characterId && CHARACTER_PERSONALITIES[characterId]) {
    return { ...CHARACTER_PERSONALITIES[characterId] };
  }
  return { ...DEFAULT_PERSONALITY };
}
